// This is your data file.
// Create a file named 'french.js' in the same directory as your HTML file.
// Copy and paste the following code into it, replacing the example with your full JSON data.
// Make sure your JSON objects are elements of a JavaScript array assigned to the 'words' variable.

const words = [
  {
    "word": "bonjour",
    "pronunciation_ipa": "[bɔ̃ˈʒuʁ]",
    "pronunciation_english": "bon-zhoor (R guttural, nasal 'on')",
    "pronunciation_persian": "بُژوغ (r فرانسوی = غ ته گلو)",
    "translation_english": "hello",
    "persian": "سلام",
    "sample_sentence": "Bonjour, comment ça va ?",
    "sentence_pronunciation_ipa": "[bɔ̃ˈʒuʁ kɔmɑ̃ sa va]",
    "sentence_pronunciation_english": "bon-zhoor, koh-mahn sa va (nasal 'on' & 'an', guttural R)",
    "sentence_pronunciation_persian": "بُژوغ، کُمان سا وا؟",
    "sentence_translation_english": "Hello, how are you?",
    "sentence_persian": "سلام، حالت چطوره؟"
  },
  {
    "word": "merci",
    "pronunciation_ipa": "[mɛʁˈsi]",
    "pronunciation_english": "mehr-see (R guttural)",
    "pronunciation_persian": "مِغسی (r فرانسوی = غ ته گلو)",
    "translation_english": "thank you",
    "persian": "ممنون / متشکرم",
    "sample_sentence": "Merci beaucoup pour votre aide.",
    "sentence_pronunciation_ipa": "[mɛʁˈsi boˈku puʁ votʁ ɛd]",
    "sentence_pronunciation_english": "mehr-see boh-koo poor votr ed (guttural R)",
    "sentence_pronunciation_persian": "مِغسی بوکو پور وُتغ اِد.",
    "sentence_translation_english": "Thank you very much for your help.",
    "sentence_persian": "خیلی ممنون بابت کمکتون."
  },
  {
    "word": "oui",
    "pronunciation_ipa": "[wi]",
    "pronunciation_english": "wee",
    "pronunciation_persian": "وی",
    "translation_english": "yes",
    "persian": "بله",
    "sample_sentence": "Oui, j’aime le café.",
    "sentence_pronunciation_ipa": "[wi ʒɛm lə kafe]",
    "sentence_pronunciation_english": "wee zhem luh ka-fay",
    "sentence_pronunciation_persian": "وی، ژِم لُ کافه.",
    "sentence_translation_english": "Yes, I like coffee.",
    "sentence_persian": "بله، من قهوه دوست دارم."
  },
  {
    "word": "non",
    "pronunciation_ipa": "[nɔ̃]",
    "pronunciation_english": "noh~ (nasal)",
    "pronunciation_persian": "نُ (ن دماغی)",
    "translation_english": "no",
    "persian": "نه",
    "sample_sentence": "Non, je ne veux pas.",
    "sentence_pronunciation_ipa": "[nɔ̃ ʒə nə vø pa]",
    "sentence_pronunciation_english": "noh~, zhuh nuh vuh pah",
    "sentence_pronunciation_persian": "نُ، ژُ نُ وُ پا.",
    "sentence_translation_english": "No, I don’t want (it).",
    "sentence_persian": "نه، من نمی‌خواهم."
  },
  {
    "word": "au revoir",
    "pronunciation_ipa": "[o ʁəˈvwaʁ]",
    "pronunciation_english": "oh r(gh)uh-vwar (guttural R)",
    "pronunciation_persian": "اوغُوغاغ",
    "translation_english": "goodbye",
    "persian": "خداحافظ",
    "sample_sentence": "Au revoir et à bientôt.",
    "sentence_pronunciation_ipa": "[o ʁəˈvwaʁ e a bjɛ̃to]",
    "sentence_pronunciation_english": "oh r(gh)uh-vwar ay ah byan-toh (guttural R, nasal 'an')",
    "sentence_pronunciation_persian": "اوغُوغاغ اِ آ بیانتو.",
    "sentence_translation_english": "Goodbye and see you soon.",
    "sentence_persian": "خداحافظ و به زودی می‌بینمت."
  },
  {
    "word": "s'il vous plaît",
    "pronunciation_ipa": "[sil vu plɛ]",
    "pronunciation_english": "seel voo pleh",
    "pronunciation_persian": "سیل وُ پله",
    "translation_english": "please",
    "persian": "لطفاً",
    "sample_sentence": "Un café, s’il vous plaît.",
    "sentence_pronunciation_ipa": "[ɛ̃ kafe sil vu plɛ]",
    "sentence_pronunciation_english": "eh~ ka-fay, seel voo pleh",
    "sentence_pronunciation_persian": "اَن کافه، سیل وُ پله.",
    "sentence_translation_english": "A coffee, please.",
    "sentence_persian": "یک قهوه، لطفاً."
  },
  {
    "word": "excusez-moi",
    "pronunciation_ipa": "[ɛkskyze mwa]",
    "pronunciation_english": "eks-kyu-zay mwah",
    "pronunciation_persian": "اِکس‌کیوزه موا",
    "translation_english": "excuse me",
    "persian": "ببخشید",
    "sample_sentence": "Excusez-moi, où sont les toilettes ?",
    "sentence_pronunciation_ipa": "[ɛkskyze mwa u sɔ̃ le twalɛt]",
    "sentence_pronunciation_english": "eks-kyu-zay mwah, oo so~ lay twah-let",
    "sentence_pronunciation_persian": "اِکس‌کیوزه موا، او سُن لِ توالت؟",
    "sentence_translation_english": "Excuse me, where are the toilets?",
    "sentence_persian": "ببخشید، دستشویی‌ها کجاست؟"
  },
  {
    "word": "comment",
    "pronunciation_ipa": "[kɔmɑ̃]",
    "pronunciation_english": "koh-mahn (nasal 'an')",
    "pronunciation_persian": "کُمان (ن دماغی)",
    "translation_english": "how",
    "persian": "چطور / چگونه",
    "sample_sentence": "Comment tu t’appelles ?",
    "sentence_pronunciation_ipa": "[kɔmɑ̃ ty tapɛl]",
    "sentence_pronunciation_english": "koh-mahn tu tah-pel",
    "sentence_pronunciation_persian": "کُمان تو تاپل؟",
    "sentence_translation_english": "What is your name?",
    "sentence_persian": "اسم شما چیه؟"
  },
  {
    "word": "je",
    "pronunciation_ipa": "[ʒə]",
    "pronunciation_english": "zhuh",
    "pronunciation_persian": "ژُ",
    "translation_english": "I",
    "persian": "من",
    "sample_sentence": "Je suis étudiant.",
    "sentence_pronunciation_ipa": "[ʒə sɥi zetydjɑ̃]",
    "sentence_pronunciation_english": "zhuh swee zay-tyu-dyan",
    "sentence_pronunciation_persian": "ژُ سوی زِتیودیَن.",
    "sentence_translation_english": "I am a student.",
    "sentence_persian": "من دانشجو هستم."
  },
  {
    "word": "vous",
    "pronunciation_ipa": "[vu]",
    "pronunciation_english": "voo",
    "pronunciation_persian": "وُ",
    "translation_english": "you (formal/plural)",
    "persian": "شما",
    "sample_sentence": "Vous parlez anglais ?",
    "sentence_pronunciation_ipa": "[vu paʁle ɑ̃ɡlɛ]",
    "sentence_pronunciation_english": "voo par-lay an-glay",
    "sentence_pronunciation_persian": "وُ پارلِ آنگلِ؟",
    "sentence_translation_english": "Do you speak English?",
    "sentence_persian": "انگلیسی صحبت می‌کنید؟"
  },
  {
    "word": "monsieur",
    "pronunciation_ipa": "[məsjø]",
    "pronunciation_english": "muh-syuh",
    "pronunciation_persian": "مُسیو",
    "translation_english": "sir / Mr.",
    "persian": "آقا / آقای",
    "sample_sentence": "Bonjour, monsieur.",
    "sentence_pronunciation_ipa": "[bɔ̃ˈʒuʁ məsjø]",
    "sentence_pronunciation_english": "bon-zhoor muh-syuh",
    "sentence_pronunciation_persian": "بُژوغ مُسیو.",
    "sentence_translation_english": "Hello, sir.",
    "sentence_persian": "سلام آقا."
  },
  {
    "word": "madame",
    "pronunciation_ipa": "[madam]",
    "pronunciation_english": "mah-dam",
    "pronunciation_persian": "مادام",
    "translation_english": "madam / Mrs.",
    "persian": "خانم",
    "sample_sentence": "Merci, madame.",
    "sentence_pronunciation_ipa": "[mɛʁˈsi madam]",
    "sentence_pronunciation_english": "mehr-see mah-dam",
    "sentence_pronunciation_persian": "مِغسی مادام.",
    "sentence_translation_english": "Thank you, madam.",
    "sentence_persian": "ممنون خانم."
  },
  {
    "word": "mademoiselle",
    "pronunciation_ipa": "[madmwazɛl]",
    "pronunciation_english": "mad-mwah-zel",
    "pronunciation_persian": "مادموآزل",
    "translation_english": "miss",
    "persian": "دوشیزه / خانم جوان",
    "sample_sentence": "Bonjour, mademoiselle.",
    "sentence_pronunciation_ipa": "[bɔ̃ˈʒuʁ madmwazɛl]",
    "sentence_pronunciation_english": "bon-zhoor mad-mwah-zel",
    "sentence_pronunciation_persian": "بُژوغ مادموآزل.",
    "sentence_translation_english": "Hello, miss.",
    "sentence_persian": "سلام دوشیزه."
  },
  {
    "word": "ami",
    "pronunciation_ipa": "[ami]",
    "pronunciation_english": "ah-mee",
    "pronunciation_persian": "آمی",
    "translation_english": "friend",
    "persian": "دوست",
    "sample_sentence": "C’est mon ami.",
    "sentence_pronunciation_ipa": "[sɛ mɔ̃n ami]",
    "sentence_pronunciation_english": "seh mohn ah-mee (nasal 'on')",
    "sentence_pronunciation_persian": "سِه مون آمی.",
    "sentence_translation_english": "He is my friend.",
    "sentence_persian": "او دوست من است."
  },
  {
    "word": "bien",
    "pronunciation_ipa": "[bjɛ̃]",
    "pronunciation_english": "byan~ (nasal 'in')",
    "pronunciation_persian": "بیَن (ن دماغی)",
    "translation_english": "well / good",
    "persian": "خوب",
    "sample_sentence": "Je vais bien.",
    "sentence_pronunciation_ipa": "[ʒə vɛ bjɛ̃]",
    "sentence_pronunciation_english": "zhuh veh byan~",
    "sentence_pronunciation_persian": "ژُ وِ بیَن.",
    "sentence_translation_english": "I am well.",
    "sentence_persian": "من خوبم."
  },
  {
    "word": "mal",
    "pronunciation_ipa": "[mal]",
    "pronunciation_english": "mal",
    "pronunciation_persian": "مال",
    "translation_english": "bad",
    "persian": "بد",
    "sample_sentence": "Ce n’est pas mal.",
    "sentence_pronunciation_ipa": "[sə nɛ pa mal]",
    "sentence_pronunciation_english": "suh nay pah mal",
    "sentence_pronunciation_persian": "سِ نِ پا مال.",
    "sentence_translation_english": "It's not bad.",
    "sentence_persian": "بد نیست."
  },
  {
    "word": "pardon",
    "pronunciation_ipa": "[paʁdɔ̃]",
    "pronunciation_english": "par-don~ (R guttural, nasal 'on')",
    "pronunciation_persian": "پاغدُن (ن دماغی)",
    "translation_english": "sorry / pardon",
    "persian": "ببخشید / معذرت می‌خواهم",
    "sample_sentence": "Pardon, je suis en retard.",
    "sentence_pronunciation_ipa": "[paʁdɔ̃ ʒə sɥi zɑ̃ ʁətaʁ]",
    "sentence_pronunciation_english": "par-don~ zhuh swee zan r(gh)uh-tar",
    "sentence_pronunciation_persian": "پاغدُن، ژُ سوی زان غتاغ.",
    "sentence_translation_english": "Sorry, I’m late.",
    "sentence_persian": "ببخشید، دیر رسیدم."
  },
  {
    "word": "nom",
    "pronunciation_ipa": "[nɔ̃]",
    "pronunciation_english": "noh~ (nasal)",
    "pronunciation_persian": "نُم (ن دماغی)",
    "translation_english": "name",
    "persian": "اسم",
    "sample_sentence": "Quel est votre nom ?",
    "sentence_pronunciation_ipa": "[kɛl ɛ votʁ nɔ̃]",
    "sentence_pronunciation_english": "kel eh votr noh~",
    "sentence_pronunciation_persian": "کِل اِ وُتغ نُم؟",
    "sentence_translation_english": "What is your name?",
    "sentence_persian": "اسم شما چیست؟"
  },
  {
    "word": "où",
    "pronunciation_ipa": "[u]",
    "pronunciation_english": "oo",
    "pronunciation_persian": "او",
    "translation_english": "where",
    "persian": "کجا",
    "sample_sentence": "Où habitez-vous ?",
    "sentence_pronunciation_ipa": "[u abitɛ vu]",
    "sentence_pronunciation_english": "oo ah-bee-tay voo",
    "sentence_pronunciation_persian": "او اَبیتِ وُ؟",
    "sentence_translation_english": "Where do you live?",
    "sentence_persian": "کجا زندگی می‌کنید؟"
  },
  {
    "word": "quand",
    "pronunciation_ipa": "[kɑ̃]",
    "pronunciation_english": "kah~ (nasal)",
    "pronunciation_persian": "کان (ن دماغی)",
    "translation_english": "when",
    "persian": "کی",
    "sample_sentence": "Quand partons-nous ?",
    "sentence_pronunciation_ipa": "[kɑ̃ paʁtɔ̃ nu]",
    "sentence_pronunciation_english": "kah~ par-tohn noo (nasal 'an' & 'on')",
    "sentence_pronunciation_persian": "کان پاغتون نو؟",
    "sentence_translation_english": "When are we leaving?",
    "sentence_persian": "کی می‌رویم؟"
  }
,
{
    "word": "combien",
    "pronunciation_ipa": "[kɔ̃bjɛ̃]",
    "pronunciation_english": "kohm-byen~ (nasal 'om' & 'ien')",
    "pronunciation_persian": "کُمیَن (م و ن دماغی)",
    "translation_english": "how much / how many",
    "persian": "چقدر / چند تا",
    "sample_sentence": "Combien ça coûte ?",
    "sentence_pronunciation_ipa": "[kɔ̃bjɛ̃ sa kut]",
    "sentence_pronunciation_english": "kohm-byen~ sa koot",
    "sentence_pronunciation_persian": "کُمیَن سا کوت؟",
    "sentence_translation_english": "How much does it cost?",
    "sentence_persian": "چقدر قیمت دارد؟"
  },
  {
    "word": "quoi",
    "pronunciation_ipa": "[kwa]",
    "pronunciation_english": "kwah",
    "pronunciation_persian": "کوا",
    "translation_english": "what",
    "persian": "چه / چی",
    "sample_sentence": "C’est quoi, ça ?",
    "sentence_pronunciation_ipa": "[sɛ kwa sa]",
    "sentence_pronunciation_english": "seh kwah sa",
    "sentence_pronunciation_persian": "سِ کوا سا؟",
    "sentence_translation_english": "What is that?",
    "sentence_persian": "این چیه؟"
  },
  {
    "word": "où est",
    "pronunciation_ipa": "[u ɛ]",
    "pronunciation_english": "oo eh",
    "pronunciation_persian": "او اِ",
    "translation_english": "where is",
    "persian": "کجاست",
    "sample_sentence": "Où est la gare ?",
    "sentence_pronunciation_ipa": "[u ɛ la ɡaʁ]",
    "sentence_pronunciation_english": "oo eh la gar (R guttural)",
    "sentence_pronunciation_persian": "او اِ لا گاغ؟",
    "sentence_translation_english": "Where is the station?",
    "sentence_persian": "ایستگاه کجاست؟"
  },
  {
    "word": "ici",
    "pronunciation_ipa": "[isi]",
    "pronunciation_english": "ee-see",
    "pronunciation_persian": "ای‌سی",
    "translation_english": "here",
    "persian": "اینجا",
    "sample_sentence": "Venez ici, s’il vous plaît.",
    "sentence_pronunciation_ipa": "[vəne isi sil vu plɛ]",
    "sentence_pronunciation_english": "vuh-nay ee-see seel voo pleh",
    "sentence_pronunciation_persian": "وُنه ای‌سی سیل وُ پله.",
    "sentence_translation_english": "Come here, please.",
    "sentence_persian": "لطفاً بیایید اینجا."
  },
  {
    "word": "là",
    "pronunciation_ipa": "[la]",
    "pronunciation_english": "lah",
    "pronunciation_persian": "لا",
    "translation_english": "there",
    "persian": "آنجا",
    "sample_sentence": "C’est là-bas.",
    "sentence_pronunciation_ipa": "[sɛ laba]",
    "sentence_pronunciation_english": "seh lah-bah",
    "sentence_pronunciation_persian": "سِ لا با.",
    "sentence_translation_english": "It’s over there.",
    "sentence_persian": "اونجاست."
  },
  {
    "word": "maintenant",
    "pronunciation_ipa": "[mɛ̃tnɑ̃]",
    "pronunciation_english": "meh(n)-t-nahn~ (nasal 'en' & 'an')",
    "pronunciation_persian": "مَن‌تنا(ن دماغی)",
    "translation_english": "now",
    "persian": "الان",
    "sample_sentence": "Je pars maintenant.",
    "sentence_pronunciation_ipa": "[ʒə paʁ mɛ̃tnɑ̃]",
    "sentence_pronunciation_english": "zhuh par meh(n)-t-nahn~",
    "sentence_pronunciation_persian": "ژُ پار مَن‌تنا.",
    "sentence_translation_english": "I’m leaving now.",
    "sentence_persian": "الان میرم."
  },
  {
    "word": "toujours",
    "pronunciation_ipa": "[tuʒuʁ]",
    "pronunciation_english": "too-zhoor (R guttural)",
    "pronunciation_persian": "توزوغ",
    "translation_english": "always",
    "persian": "همیشه",
    "sample_sentence": "Il est toujours en retard.",
    "sentence_pronunciation_ipa": "[il ɛ tuʒuʁ ɑ̃ ʁətaʁ]",
    "sentence_pronunciation_english": "eel eh too-zhoor ahn r(gh)uh-tar",
    "sentence_pronunciation_persian": "ایل اِ توزوغ آن غتاغ.",
    "sentence_translation_english": "He is always late.",
    "sentence_persian": "او همیشه دیر می‌کند."
  },
  {
    "word": "jamais",
    "pronunciation_ipa": "[ʒamɛ]",
    "pronunciation_english": "zha-meh",
    "pronunciation_persian": "ژامه",
    "translation_english": "never",
    "persian": "هرگز / هیچ‌وقت",
    "sample_sentence": "Je ne fume jamais.",
    "sentence_pronunciation_ipa": "[ʒə nə fym ʒamɛ]",
    "sentence_pronunciation_english": "zhuh nuh fyum zha-meh",
    "sentence_pronunciation_persian": "ژُ نُ فیوم ژامه.",
    "sentence_translation_english": "I never smoke.",
    "sentence_persian": "من هرگز سیگار نمی‌کشم."
  },
  {
    "word": "parce que",
    "pronunciation_ipa": "[paʁs kə]",
    "pronunciation_english": "parss kuh (R guttural)",
    "pronunciation_persian": "پارْس کُ",
    "translation_english": "because",
    "persian": "چون که / زیرا",
    "sample_sentence": "Je viens parce que je t’aime.",
    "sentence_pronunciation_ipa": "[ʒə vjɛ̃ paʁs kə ʒə tɛm]",
    "sentence_pronunciation_english": "zhuh vyen~ parss kuh zhuh tem",
    "sentence_pronunciation_persian": "ژُ ویَن پارْس کُ ژُ تم.",
    "sentence_translation_english": "I come because I love you.",
    "sentence_persian": "میام چون دوستت دارم."
  },
  {
    "word": "avec",
    "pronunciation_ipa": "[avɛk]",
    "pronunciation_english": "ah-vek",
    "pronunciation_persian": "آوک",
    "translation_english": "with",
    "persian": "با",
    "sample_sentence": "Je viens avec un ami.",
    "sentence_pronunciation_ipa": "[ʒə vjɛ̃ avɛk ɛ̃n ami]",
    "sentence_pronunciation_english": "zhuh vyen~ ah-vek an ah-mee (nasal 'an')",
    "sentence_pronunciation_persian": "ژُ ویَن آوک آن آمی.",
    "sentence_translation_english": "I’m coming with a friend.",
    "sentence_persian": "با یک دوست میام."
  },
  {
    "word": "sans",
    "pronunciation_ipa": "[sɑ̃]",
    "pronunciation_english": "sahn~ (nasal)",
    "pronunciation_persian": "سان (ن دماغی)",
    "translation_english": "without",
    "persian": "بدون",
    "sample_sentence": "Je prends mon café sans sucre.",
    "sentence_pronunciation_ipa": "[ʒə pʁɑ̃ mɔ̃ kafe sɑ̃ sykʁ]",
    "sentence_pronunciation_english": "zhuh prahn~ mohn ka-fay sahn~ syukr",
    "sentence_pronunciation_persian": "ژُ پغان مون کافه سان سیوکر.",
    "sentence_translation_english": "I take my coffee without sugar.",
    "sentence_persian": "قهوه‌ام رو بدون شکر می‌خورم."
  },
  {
    "word": "très",
    "pronunciation_ipa": "[tʁɛ]",
    "pronunciation_english": "tray (R guttural)",
    "pronunciation_persian": "تغه",
    "translation_english": "very",
    "persian": "خیلی",
    "sample_sentence": "C’est très bon.",
    "sentence_pronunciation_ipa": "[sɛ tʁɛ bɔ̃]",
    "sentence_pronunciation_english": "seh tray boh~",
    "sentence_pronunciation_persian": "سِ تغه بُن.",
    "sentence_translation_english": "It’s very good.",
    "sentence_persian": "خیلی خوبه."
  },
  {
    "word": "beaucoup",
    "pronunciation_ipa": "[boku]",
    "pronunciation_english": "boh-koo",
    "pronunciation_persian": "بوکو",
    "translation_english": "a lot / much / many",
    "persian": "خیلی / زیاد",
    "sample_sentence": "Merci beaucoup.",
    "sentence_pronunciation_ipa": "[mɛʁsi boku]",
    "sentence_pronunciation_english": "mehr-see boh-koo (R guttural)",
    "sentence_pronunciation_persian": "مِغسی بوکو.",
    "sentence_translation_english": "Thank you very much.",
    "sentence_persian": "خیلی ممنون."
  },
  {
    "word": "peu",
    "pronunciation_ipa": "[pø]",
    "pronunciation_english": "puh (like 'peu' in French)",
    "pronunciation_persian": "پُ",
    "translation_english": "little / few",
    "persian": "کمی / اندکی",
    "sample_sentence": "J’ai peu d’argent.",
    "sentence_pronunciation_ipa": "[ʒe pø daʁʒɑ̃]",
    "sentence_pronunciation_english": "zheh puh dar-zhan~ (nasal 'an')",
    "sentence_pronunciation_persian": "ژه پُ دارژان.",
    "sentence_translation_english": "I have little money.",
    "sentence_persian": "پول کمی دارم."
  },
  {
    "word": "aussi",
    "pronunciation_ipa": "[osi]",
    "pronunciation_english": "oh-see",
    "pronunciation_persian": "اُسی",
    "translation_english": "also / too",
    "persian": "همچنین / هم",
    "sample_sentence": "Moi aussi.",
    "sentence_pronunciation_ipa": "[mwa osi]",
    "sentence_pronunciation_english": "mwah oh-see",
    "sentence_pronunciation_persian": "موا اُسی.",
    "sentence_translation_english": "Me too.",
    "sentence_persian": "من هم."
  },
  {
    "word": "toujours",
    "pronunciation_ipa": "[tuʒuʁ]",
    "pronunciation_english": "too-zhoor (R guttural)",
    "pronunciation_persian": "توزوغ",
    "translation_english": "always",
    "persian": "همیشه",
    "sample_sentence": "Je t’aimerai toujours.",
    "sentence_pronunciation_ipa": "[ʒə tɛmʁe tuʒuʁ]",
    "sentence_pronunciation_english": "zhuh tem-ray too-zhoor",
    "sentence_pronunciation_persian": "ژُ تمره توزوغ.",
    "sentence_translation_english": "I will always love you.",
    "sentence_persian": "همیشه دوستت خواهم داشت."
  },
  {
    "word": "jamais",
    "pronunciation_ipa": "[ʒamɛ]",
    "pronunciation_english": "zha-meh",
    "pronunciation_persian": "ژامه",
    "translation_english": "never",
    "persian": "هیچ‌وقت / هرگز",
    "sample_sentence": "On ne sait jamais.",
    "sentence_pronunciation_ipa": "[ɔ̃ nə sɛ ʒamɛ]",
    "sentence_pronunciation_english": "on~ nuh seh zha-meh (nasal 'on')",
    "sentence_pronunciation_persian": "آن نُ سِ ژامه.",
    "sentence_translation_english": "You never know.",
    "sentence_persian": "هیچ‌وقت آدم نمی‌دونه."
  },
  {
    "word": "trouver",
    "pronunciation_ipa": "[tʁuve]",
    "pronunciation_english": "troo-vay (R guttural)",
    "pronunciation_persian": "تغووه",
    "translation_english": "to find",
    "persian": "پیدا کردن",
    "sample_sentence": "Je vais trouver une solution.",
    "sentence_pronunciation_ipa": "[ʒə vɛ tʁuve yn sɔlysjɔ̃]",
    "sentence_pronunciation_english": "zhuh vay troo-vay uhn so-lyu-syon~",
    "sentence_pronunciation_persian": "ژُ وِ تغووه اون سُلیوسیون.",
    "sentence_translation_english": "I will find a solution.",
    "sentence_persian": "یه راه‌حل پیدا می‌کنم."
  },
  {
    "word": "prendre",
    "pronunciation_ipa": "[pʁɑ̃dʁ]",
    "pronunciation_english": "pran-dre (R guttural, nasal 'an')",
    "pronunciation_persian": "پغاندغ",
    "translation_english": "to take",
    "persian": "گرفتن",
    "sample_sentence": "Je vais prendre le train.",
    "sentence_pronunciation_ipa": "[ʒə vɛ pʁɑ̃dʁ lə tʁɛ̃]",
    "sentence_pronunciation_english": "zhuh vay pran-dre luh tran~",
    "sentence_pronunciation_persian": "ژُ وِ پغاندغ لُ تغن.",
    "sentence_translation_english": "I will take the train.",
    "sentence_persian": "قطار را می‌گیرم."
  },
];
