   
const themesData = {
  modernDark: [
    { id: 'theme-cyberpunk', name: 'سایبرپانک', primary: '#f9f871', bg: '#0c0c27', text: '#a6fffa', isDark: true },
    { id: 'theme-vaporwave', name: 'ویپورویو', primary: '#ff77cc', bg: '#200c38', text: '#00e5e5', isDark: true },
    { id: 'theme-twilight', name: 'گرگ و میش', primary: '#ffc880', bg: '#1e1e3f', text: '#d4d4ff', isDark: true },
    { id: 'theme-matrix', name: 'ماتریکس', primary: '#00ff41', bg: '#0d0208', text: '#008f11', isDark: true },
    { id: 'theme-deep-space', name: 'اعماق فضا', primary: '#9d80ff', bg: '#00001a', text: '#f0f0ff', isDark: true },
    { id: 'theme-oled', name: 'OLED', primary: '#ff3385', bg: '#000000', text: '#e5e5e5', isDark: true },
    { id: 'theme-8bit-sunset', name: 'غروب ۸ بیتی', primary: '#f9d868', bg: '#34294b', text: '#f0e5ff', isDark: true },
    { id: 'theme-arcade', name: 'آرکید', primary: '#ffcc00', bg: '#1d1a33', text: '#eeebff', isDark: true },
    { id: 'theme-midnight-city', name: 'شهر نیمه‌شب', primary: '#f1fa8c', bg: '#191a21', text: '#e1e1e6', isDark: true },
    { id: 'theme-snes-dark', name: 'SNES', primary: '#aca8dd', bg: '#212121', text: '#e0e0e0', isDark: true },
    { id: 'theme-playstation-dark', name: 'پلی‌استیشن', primary: '#006fcd', bg: '#1f1f2e', text: '#f0f0f5', isDark: true },
    { id: 'theme-blade-runner-dark', name: 'بلیدرانر', primary: '#f05a28', bg: '#0a1128', text: '#00f6ff', isDark: true },
    { id: 'theme-dune-dark', name: 'تل‌ماسه', primary: '#e89f48', bg: '#2c221c', text: '#d5c8b8', isDark: true },
    { id: 'theme-ocean-dark', name: 'اقیانوس', primary: '#5efff5', bg: '#0b192f', text: '#ccd6f6', isDark: true },
    { id: 'theme-blood-moon', name: 'ماه خونین', primary: '#ff4d4d', bg: '#1a0000', text: '#ffcccc', isDark: true },
    { id: 'theme-nebula', name: 'سحابی', primary: '#d67ae9', bg: '#1d0f2b', text: '#e1d8f5', isDark: true },
    { id: 'theme-volcano', name: 'آتشفشان', primary: '#ff7a00', bg: '#1f120c', text: '#ffd8c9', isDark: true },
    { id: 'theme-aurora', name: 'شفق قطبی', primary: '#45fcd1', bg: '#011627', text: '#d6deeb', isDark: true },
    { id: 'theme-synthwave-84', name: 'موج سینتی', primary: '#ff8b42', bg: '#2b213a', text: '#f9f7f2', isDark: true },
    { id: 'theme-atlantis', name: 'آتلانتیس', primary: '#96e072', bg: '#262a33', text: '#f8f8f2', isDark: true },
    // START of 50 new Modern Dark themes
    { id: 'theme-starry-night', name: 'شب پرستاره', primary: '#f2c641', bg: '#0b1a3b', text: '#e0e5f0', isDark: true },
    { id: 'theme-tokyo-neon', name: 'نئون توکیو', primary: '#f92a82', bg: '#1a1a3a', text: '#a6e1ff', isDark: true },
    { id: 'theme-holographic', name: 'هولوگرافیک', primary: '#00f6ff', bg: '#0d0d2b', text: '#e5d4ff', isDark: true },
    { id: 'theme-supernova', name: 'ابرنواختر', primary: '#ffae42', bg: '#200c28', text: '#fce5d4', isDark: true },
    { id: 'theme-quantum', name: 'کوانتوم', primary: '#8effba', bg: '#0f0f1f', text: '#d1d1f0', isDark: true },
    { id: 'theme-peacock-dark', name: 'طاووس تیره', primary: '#00a99d', bg: '#0b2e34', text: '#b3e0d6', isDark: true },
    { id: 'theme-firefly-forest', name: 'جنگل کرم شب‌تاب', primary: '#d4ff00', bg: '#0a1d0a', text: '#c8e6c9', isDark: true },
    { id: 'theme-black-hole', name: 'سیاهچاله', primary: '#ff9a00', bg: '#000000', text: '#cccccc', isDark: true },
    { id: 'theme-art-deco-night', name: 'شب آرت دکو', primary: '#e6c300', bg: '#1a1a1a', text: '#f0eada', isDark: true },
    { id: 'theme-zaha-hadid', name: 'زاها حدید', primary: '#c0c0c0', bg: '#1f2229', text: '#e1e3e8', isDark: true },
    { id: 'theme-amethyst', name: 'آمتیست', primary: '#c395f3', bg: '#291c3d', text: '#e9e0f9', isDark: true },
    { id: 'theme-bioluminescent', name: 'زیست‌تابی', primary: '#40e0d0', bg: '#0a1f2c', text: '#c0f0e8', isDark: true },
    { id: 'theme-miami-vice', name: 'میامی وایس', primary: '#ee00ff', bg: '#0f0c29', text: '#00eaff', isDark: true },
    { id: 'theme-lunar-eclipse', name: 'ماه‌گرفتگی', primary: '#ff6b6b', bg: '#1a141e', text: '#ffc3c3', isDark: true },
    { id: 'theme-martian-sky', name: 'آسمان مریخ', primary: '#e58d45', bg: '#2a140e', text: '#e8d8d2', isDark: true },
    { id: 'theme-orchid-noir', name: 'ارکیده نوآر', primary: '#da70d6', bg: '#1c1822', text: '#e6dced', isDark: true },
    { id: 'theme-andromeda', name: 'آندرومدا', primary: '#a79aff', bg: '#12122d', text: '#e3e0ff', isDark: true },
    { id: 'theme-geode-dark', name: 'ژئود تیره', primary: '#aa7de0', bg: '#2d2a42', text: '#e8e5f5', isDark: true },
    { id: 'theme-glitch', name: 'گلیچ', primary: '#ff003c', bg: '#101010', text: '#00ffc3', isDark: true },
    { id: 'theme-crystal-cave', name: 'غار کریستالی', primary: '#80dfff', bg: '#1e293b', text: '#e2f3ff', isDark: true },
    { id: 'theme-velvet-galaxy', name: 'کهکشان مخملی', primary: '#c8a2c8', bg: '#201b2f', text: '#e5ddeb', isDark: true },
    { id: 'theme-monarch-dark', name: 'پروانه مونارک', primary: '#fc6a03', bg: '#1a120b', text: '#f2e6de', isDark: true },
    { id: 'theme-city-lights', name: 'چراغ‌های شهر', primary: '#f9d749', bg: '#0d1b2a', text: '#e0e1dd', isDark: true },
    { id: 'theme-techno', name: 'تکنو', primary: '#7efd7e', bg: '#0a0a0a', text: '#c1c1c1', isDark: true },
    { id: 'theme-futuristic-femme', name: 'بانوی آینده', primary: '#f470b9', bg: '#190e28', text: '#f9d8f4', isDark: true },
    { id: 'theme-dark-matter', name: 'ماده تاریک', primary: '#9e9e9e', bg: '#0f0f0f', text: '#dddddd', isDark: true },
    { id: 'theme-coral-night', name: 'شب مرجانی', primary: '#ff7f50', bg: '#002538', text: '#ccebff', isDark: true },
    { id: 'theme-cyber-rose', name: 'رز سایبری', primary: '#ff007f', bg: '#1b001a', text: '#ffcce7', isDark: true },
    { id: 'theme-lava-lamp', name: 'لامپ گدازه', primary: '#f55734', bg: '#230a1f', text: '#f9e3de', isDark: true },
    { id: 'theme-arctic-night', name: 'شب قطبی', primary: '#86c5da', bg: '#1f2937', text: '#d1e0e8', isDark: true },
    { id: 'theme-brutalist-dark', name: 'بروتالیست تیره', primary: '#a0a0a0', bg: '#303030', text: '#e0e0e0', isDark: true },
    { id: 'theme-glass-frog', name: 'قورباغه شیشه‌ای', primary: '#a6ffcb', bg: '#0b211a', text: '#d1f2e9', isDark: true },
    { id: 'theme-electric-eel', name: 'مارماهی الکتریکی', primary: '#fff352', bg: '#08172c', text: '#d9e7ff', isDark: true },
    { id: 'theme-diamond-dark', name: 'الماس تیره', primary: '#b9f2ff', bg: '#1c2541', text: '#e2f4ff', isDark: true },
    { id: 'theme-retro-futurism', name: 'آینده‌گرایی رترو', primary: '#ff9f1c', bg: '#2b2d42', text: '#edf2f4', isDark: true },
    { id: 'theme-mood-ring', name: 'انگشتر خلق‌وخو', primary: '#4deeea', bg: '#242e3a', text: '#d3dce6', isDark: true },
    { id: 'theme-digital-rain', name: 'باران دیجیتال', primary: '#43ff43', bg: '#050a05', text: '#90ff90', isDark: true },
    { id: 'theme-enchanted-forest', name: 'جنگل سحرآمیز', primary: '#9a7fdd', bg: '#1a1c33', text: '#dcd6f0', isDark: true },
    { id: 'theme-havana-nights', name: 'شب‌های هاوانا', primary: '#f7b801', bg: '#3d1c02', text: '#f4e7d7', isDark: true },
    { id: 'theme-stardust', name: 'گرد ستاره', primary: '#d4c1f5', bg: '#19192a', text: '#ebe6f9', isDark: true },
    { id: 'theme-comet-tail', name: 'دنباله دنباله‌دار', primary: '#a6e1ff', bg: '#0d1a32', text: '#e1ecf7', isDark: true },
    { id: 'theme-motherboard', name: 'مادربورد', primary: '#00b57a', bg: '#0c231f', text: '#a0d9c9', isDark: true },
    { id: 'theme-deep-sea-glow', name: 'درخشش اعماق دریا', primary: '#44f2e8', bg: '#040f28', text: '#c8daff', isDark: true },
    { id: 'theme-cinematic', name: 'سینمایی', primary: '#ffc107', bg: '#121212', text: '#e0e0e0', isDark: true },
    { id: 'theme-graphene', name: 'گرافن', primary: '#b3b3b3', bg: '#1e1e1e', text: '#dcdcdc', isDark: true },
    { id: 'theme-alien-jungle', name: 'جنگل بیگانه', primary: '#bfff00', bg: '#17220e', text: '#dfffaa', isDark: true },
    { id: 'theme-80s-bedroom', name: 'اتاق خواب دهه ۸۰', primary: '#ff69b4', bg: '#2c003e', text: '#ffc1e3', isDark: true },
    { id: 'theme-london-night', name: 'شب لندن', primary: '#d7c378', bg: '#25283d', text: '#d2d3db', isDark: true },
    { id: 'theme-dieselpunk', name: 'دیزل‌پانک', primary: '#c9a46f', bg: '#3a322c', text: '#e2dacf', isDark: true },
    { id: 'theme-dark-rhodium', name: 'رودیوم تیره', primary: '#a2a7b1', bg: '#292d34', text: '#e3e5e8', isDark: true },
    // END of 50 new Modern Dark themes
        // START of 25 new Modern Dark themes
    { id: 'theme-black-diamond', name: 'الماس سیاه', primary: '#d1d1d1', bg: '#0f0f0f', text: '#a8a8a8', isDark: true },
    { id: 'theme-onyx-gold', name: 'اونیکس و طلا', primary: '#e6c300', bg: '#1a1a1a', text: '#e0d8c4', isDark: true },
    { id: 'theme-sapphire-velvet', name: 'مخمل یاقوت کبود', primary: '#6d85b5', bg: '#0f172a', text: '#d4dbee', isDark: true },
    { id: 'theme-versailles-night', name: 'شب ورسای', primary: '#cba32a', bg: '#1c1624', text: '#e7e2ee', isDark: true },
    { id: 'theme-crystal-noir', name: 'کریستال نوآر', primary: '#a497b2', bg: '#1e1a26', text: '#e3e0e8', isDark: true },
    { id: 'theme-liquid-gold', name: 'طلای مایع', primary: '#f2d479', bg: '#120f0b', text: '#e1d9cc', isDark: true },
    { id: 'theme-midnight-orchid', name: 'ارکیده نیمه‌شب', primary: '#c87dd2', bg: '#1b0f1d', text: '#e8d8ea', isDark: true },
    { id: 'theme-luxury-lounge', name: 'سالن لوکس', primary: '#bfa38f', bg: '#2a2522', text: '#e4e0dd', isDark: true },
    { id: 'theme-stained-glass-dark', name: 'شیشه رنگی تیره', primary: '#8ab4f8', bg: '#1f2428', text: '#e8eaed', isDark: true },
    { id: 'theme-black-swan', name: 'قوی سیاه', primary: '#c0c0c0', bg: '#111111', text: '#d8d8d8', isDark: true },
    { id: 'theme-dark-topaz', name: 'توپاز تیره', primary: '#ffc107', bg: '#251d00', text: '#e8e1c9', isDark: true },
    { id: 'theme-royal-purple', name: 'بنفش سلطنتی', primary: '#ab87ff', bg: '#201a30', text: '#e4dfff', isDark: true },
    { id: 'theme-dark-silk', name: 'ابریشم تیره', primary: '#b38b96', bg: '#291e22', text: '#e6dfe1', isDark: true },
    { id: 'theme-diamond-heist', name: 'سرقت الماس', primary: '#a6e1ff', bg: '#0d1a2b', text: '#d1e5f0', isDark: true },
    { id: 'theme-gilded-onyx', name: 'اونیکس طلاکاری‌شده', primary: '#e8c975', bg: '#141414', text: '#dcd5c4', isDark: true },
    { id: 'theme-night-jasmine', name: 'یاس شب', primary: '#e0c4a4', bg: '#231f1a', text: '#f0e9e1', isDark: true },
    { id: 'theme-shadow-crystal', name: 'کریستال سایه', primary: '#a0a0d0', bg: '#1a1a2e', text: '#e0e0f0', isDark: true },
    { id: 'theme-penthouse-view', name: 'نمای پنت‌هاوس', primary: '#89cff0', bg: '#0b1d28', text: '#d9e8f0', isDark: true },
    { id: 'theme-jet-black', name: 'مشکی مطلق', primary: '#c9c9c9', bg: '#0a0a0a', text: '#a0a0a0', isDark: true },
    { id: 'theme-vvs-dark', name: 'VVS تیره', primary: '#b0e0e6', bg: '#1f2a38', text: '#e1ebee', isDark: true },
    { id: 'theme-black-iris', name: 'زنبق سیاه', primary: '#a999d9', bg: '#1e1c26', text: '#e4e1ed', isDark: true },
    { id: 'theme-obsidian-gold', name: 'ابسیدین و طلا', primary: '#d4af37', bg: '#1c1c1c', text: '#e8e2d0', isDark: true },
    { id: 'theme-luxe-noir', name: 'لوکس نوآر', primary: '#c4b3a2', bg: '#222222', text: '#e8e4e0', isDark: true },
    { id: 'theme-dark-peacock', name: 'طاووس تیره', primary: '#00a99d', bg: '#0b2e34', text: '#b3e0d6', isDark: true },
    { id: 'theme-midnight-jewel', name: 'جواهر نیمه‌شب', primary: '#7f5af0', bg: '#16161a', text: '#dcdcdc', isDark: true },
    // END of 25 new Modern Dark themes
  ],
  classicDark: [
    { id: 'theme-dracula', name: 'دراکولا', primary: '#ff79c6', bg: '#282a36', text: '#f8f8f2', isDark: true },
    { id: 'theme-monokai', name: 'مونوکای', primary: '#f92672', bg: '#272822', text: '#f8f8f2', isDark: true },
    { id: 'theme-nord', name: 'نورد', primary: '#88c0d0', bg: '#2e3440', text: '#d8dee9', isDark: true },
    { id: 'theme-gruvbox-dark', name: 'گراوباکس', primary: '#fe8019', bg: '#282828', text: '#ebdbb2', isDark: true },
    { id: 'theme-solarized-dark', name: 'سولارایزد', primary: '#268bd2', bg: '#002b36', text: '#eee8d5', isDark: true },
    { id: 'theme-old-terminal', name: 'ترمینال', primary: '#33ff33', bg: '#000000', text: '#33ff33', isDark: true },
    { id: 'theme-forest', name: 'جنگل', primary: '#b4e982', bg: '#1a2b23', text: '#d3e5d7', isDark: true },
    { id: 'theme-noir', name: 'نوآر', primary: '#f4a261', bg: '#1c1c1c', text: '#e0e0e0', isDark: true },
    { id: 'theme-velvet', name: 'مخملی', primary: '#ffd700', bg: '#4a0404', text: '#fff0f0', isDark: true },
    { id: 'theme-sublime', name: 'کدنویسی', primary: '#fd971f', bg: '#232323', text: '#f8f8f2', isDark: true },
    { id: 'theme-evergreen', name: 'همیشه‌سبز', primary: '#f4a261', bg: '#2a3d34', text: '#e8e4d1', isDark: true },
    { id: 'theme-gameboy-dark', name: 'گیم‌بوی', primary: '#3f6946', bg: '#0f380f', text: '#9bbc0f', isDark: true },
    { id: 'theme-gold-dark', name: 'طلای تیره', primary: '#ffd700', bg: '#141414', text: '#e8e8e8', isDark: true },
    { id: 'theme-rose-gold-dark', name: 'رزگلد تیره', primary: '#b76e79', bg: '#2c2426', text: '#f5f1f2', isDark: true },
    { id: 'theme-silver-dark', name: 'نقره‌ای تیره', primary: '#c0c0c0', bg: '#25282a', text: '#f0f0f0', isDark: true },
    { id: 'theme-ios-dark', name: 'iOS تیره', primary: '#0a84ff', bg: '#000000', text: '#ffffff', isDark: true },
    { id: 'theme-gothic', name: 'گوتیک', primary: '#9400d3', bg: '#121212', text: '#c8c8c8', isDark: true },
    { id: 'theme-retro-orange', name: 'نارنجی رترو', primary: '#e27d60', bg: '#27211e', text: '#e4d7d0', isDark: true },
    { id: 'theme-emerald', name: 'زمرد', primary: '#50c878', bg: '#1f2e2a', text: '#d4e9e2', isDark: true },
    { id: 'theme-coffee', name: 'قهوه', primary: '#c4a68a', bg: '#2a211c', text: '#d1c7b7', isDark: true },
    // START of 50 new Classic Dark themes
    { id: 'theme-klimt', name: 'گوستاو کلیمت', primary: '#e6b422', bg: '#3a2e0a', text: '#e8dcb5', isDark: true },
    { id: 'theme-redwood-night', name: 'شب ردوود', primary: '#b55b4e', bg: '#261b1a', text: '#d8cbc9', isDark: true },
    { id: 'theme-gothic-cathedral', name: 'کلیسای گوتیک', primary: '#a04f91', bg: '#22222a', text: '#c8c8d0', isDark: true },
    { id: 'theme-library-dark', name: 'کتابخانه تیره', primary: '#a56a42', bg: '#2a201c', text: '#d9cec6', isDark: true },
    { id: 'theme-stormy-sea', name: 'دریای طوفانی', primary: '#7b95a3', bg: '#2a3439', text: '#d6dde0', isDark: true },
    { id: 'theme-mossy-stone', name: 'سنگ خزه‌ای', primary: '#7a9e7e', bg: '#353e35', text: '#dce4dc', isDark: true },
    { id: 'theme-film-noir', name: 'فیلم نوآر', primary: '#a0a0a0', bg: '#1c1c1c', text: '#e0e0e0', isDark: true },
    { id: 'theme-charcoal', name: 'زغالی', primary: '#b0b0b0', bg: '#2d2d2d', text: '#e8e8e8', isDark: true },
    { id: 'theme-victorian-manor', name: 'عمارت ویکتوریایی', primary: '#8b4513', bg: '#2a2223', text: '#e3d7d8', isDark: true },
    { id: 'theme-autumn-leaves', name: 'برگ‌های پاییزی', primary: '#d86e3f', bg: '#36241e', text: '#e7d8d2', isDark: true },
    { id: 'theme-ancient-scroll', name: 'طومار باستانی', primary: '#c2a57f', bg: '#3f3123', text: '#e2d8ca', isDark: true },
    { id: 'theme-deep-emerald', name: 'زمرد عمیق', primary: '#009b77', bg: '#0e2d25', text: '#b3e0d4', isDark: true },
    { id: 'theme-sapphire-night', name: 'شب یاقوتی', primary: '#5b86e5', bg: '#1a233b', text: '#d3dcf2', isDark: true },
    { id: 'theme-ruby-embers', name: 'اخگر یاقوت', primary: '#d13f3f', bg: '#3b1a1a', text: '#f2d3d3', isDark: true },

    { id: 'theme-baroque', name: 'باروک', primary: '#eec44f', bg: '#3a2e22', text: '#eaddd0', isDark: true },
    { id: 'theme-witching-hour', name: 'ساعت جادوگری', primary: '#9932cc', bg: '#1d1126', text: '#e4d3ee', isDark: true },
    { id: 'theme-smoky-quartz', name: 'کوارتز دودی', primary: '#a89d91', bg: '#3d3733', text: '#e5e1de', isDark: true },
    { id: 'theme-maroon', name: 'عنابی', primary: '#c35b5b', bg: '#3b1b1b', text: '#e8d0d0', isDark: true },
    { id: 'theme-oxford-blue', name: 'آبی آکسفورد', primary: '#8da9c4', bg: '#2a3a4a', text: '#dae3ec', isDark: true },
    { id: 'theme-hunter-green', name: 'سبز شکاری', primary: '#8dbca0', bg: '#2b3a32', text: '#dbe7e1', isDark: true },
    { id: 'theme-midnight-blue', name: 'آبی نیمه‌شب', primary: '#7a9dcc', bg: '#1c253d', text: '#d4deee', isDark: true },
    { id: 'theme-spiced-wine', name: 'شراب ادویه‌ای', primary: '#a24949', bg: '#331a1a', text: '#e3d2d2', isDark: true },
    { id: 'theme-walnut', name: 'گردویی', primary: '#bca68e', bg: '#3d302a', text: '#e4dcd6', isDark: true },
    { id: 'theme-old-map', name: 'نقشه قدیمی', primary: '#c9a87c', bg: '#403528', text: '#e7e0d5', isDark: true },
    { id: 'theme-faded-photo', name: 'عکس رنگ‌پریده', primary: '#9a8c8c', bg: '#3a3636', text: '#e3e0e0', isDark: true },
    { id: 'theme-dark-academia', name: 'آکادمیای تاریک', primary: '#a38a6f', bg: '#2a241f', text: '#d8d1ca', isDark: true },
    { id: 'theme-renaissance', name: 'رنسانس', primary: '#be9b7b', bg: '#3a2f26', text: '#e4dcd3', isDark: true },
    { id: 'theme-tudor', name: 'تودور', primary: '#a96e5b', bg: '#3a2a26', text: '#e4d9d6', isDark: true },
    { id: 'theme-cobblestone', name: 'سنگفرش', primary: '#a0a0a0', bg: '#3c3c3c', text: '#e3e3e3', isDark: true },
    { id: 'theme-parchment-dark', name: 'پوست تیره', primary: '#c1b49a', bg: '#423c30', text: '#e6e2d9', isDark: true },
    { id: 'theme-art-nouveau-dark', name: 'آرت نوو تیره', primary: '#a98b64', bg: '#342f27', text: '#e0dcd4', isDark: true },
    { id: 'theme-tarnished-gold', name: 'طلای کدر', primary: '#c0a060', bg: '#332b1b', text: '#e0d9ca', isDark: true },
    { id: 'theme-aged-wine', name: 'شراب کهنه', primary: '#9e4242', bg: '#321d1d', text: '#e1d2d2', isDark: true },
    { id: 'theme-speakeasy', name: 'اسپیک‌ایزی', primary: '#daa520', bg: '#221e1a', text: '#ecd8ac', isDark: true },
    { id: 'theme-sculptors-clay', name: 'خاک رس مجسمه‌سازی', primary: '#ad9e92', bg: '#3d3936', text: '#e5e2e0', isDark: true },
    { id: 'theme-hemlock', name: 'شوکران', primary: '#9abf9e', bg: '#354339', text: '#dae5de', isDark: true },
    { id: 'theme-mahogany', name: 'ماهون', primary: '#b04a4a', bg: '#3d1e1e', text: '#e5d1d1', isDark: true },
    { id: 'theme-verdigris', name: 'زنگار', primary: '#77a399', bg: '#303f3c', text: '#d9e4e2', isDark: true },
    { id: 'theme-night-owl', name: 'جغد شب', primary: '#be9e7d', bg: '#3a3229', text: '#e3dcd5', isDark: true },
    { id: 'theme-boreal-forest', name: 'جنگل شمالی', primary: '#7da493', bg: '#2d3b36', text: '#dce5e0', isDark: true },
    { id: 'theme-fossil', name: 'فسیل', primary: '#b3a89a', bg: '#403c37', text: '#e5e3e0', isDark: true },
    { id: 'theme-cigar-lounge', name: 'سالن سیگار', primary: '#b37d4e', bg: '#3b2f27', text: '#e4dcd3', isDark: true },
    { id: 'theme-cast-iron', name: 'چدن', primary: '#8a8a8a', bg: '#2e2e2e', text: '#d8d8d8', isDark: true },
    { id: 'theme-gargoyle', name: 'گارگویل', primary: '#9e9e9e', bg: '#383838', text: '#e0e0e0', isDark: true },
    { id: 'theme-inkwell', name: 'دوات', primary: '#9ca9b7', bg: '#2c3036', text: '#dee1e5', isDark: true },
    { id: 'theme-odyssey', name: 'ادیسه', primary: '#8999ae', bg: '#303947', text: '#d8dde3', isDark: true },
    { id: 'theme-slate', name: 'سنگ لوح', primary: '#92a1b1', bg: '#363d45', text: '#dadee3', isDark: true },
    { id: 'theme-raven', name: 'کلاغ', primary: '#a0a0a0', bg: '#1f1f1f', text: '#dcdcdc', isDark: true },
    { id: 'theme-expedition', name: 'اکتشاف', primary: '#b39c7d', bg: '#3f362b', text: '#e4dfd6', isDark: true },
    // END of 50 new Classic Dark themes
        // START of 25 new Classic Dark themes
    { id: 'theme-garnet-gold', name: 'گارنت و طلا', primary: '#d16b55', bg: '#3b201c', text: '#e9d6d2', isDark: true },
    { id: 'theme-antique-gold', name: 'طلای عتیقه', primary: '#c8a864', bg: '#3a2e1c', text: '#e7e0d1', isDark: true },
    { id: 'theme-gothic-palace', name: 'کاخ گوتیک', primary: '#a48fb8', bg: '#2a2633', text: '#e3e0e8', isDark: true },
    { id: 'theme-damask-silk', name: 'ابریشم داماسک', primary: '#b8860b', bg: '#3b2f1f', text: '#e4dccd', isDark: true },
    { id: 'theme-dark-rose', name: 'رز تیره', primary: '#c25b75', bg: '#3a1f26', text: '#e8d4d9', isDark: true },
    { id: 'theme-venetian-glass', name: 'شیشه ونیزی', primary: '#7aaac2', bg: '#222d36', text: '#d6e0e6', isDark: true },
    { id: 'theme-kings-jewel', name: 'جواهر پادشاه', primary: '#e0b43a', bg: '#2b200e', text: '#ebe2cc', isDark: true },
    { id: 'theme-ballroom-noir', name: 'تالار رقص نوآر', primary: '#a9a9a9', bg: '#1e1e1e', text: '#e1e1e1', isDark: true },
    { id: 'theme-dark-marquise', name: 'مارکیز تیره', primary: '#bfa7d4', bg: '#2d2538', text: '#e8e2f0', isDark: true },
    { id: 'theme-byzantine-gold', name: 'طلای بیزانس', primary: '#bd9b3e', bg: '#382b18', text: '#e5dccb', isDark: true },
    { id: 'theme-moonstone-dark', name: 'سنگ ماه تیره', primary: '#a0b0c0', bg: '#2c333b', text: '#dfe4e8', isDark: true },
    { id: 'theme-royal-tapestry', name: 'پرده نقش‌دار سلطنتی', primary: '#b08b6e', bg: '#382e27', text: '#e3dcd5', isDark: true },
    { id: 'theme-black-pearl', name: 'مروارید سیاه', primary: '#9e9e9e', bg: '#2a2a2a', text: '#dcdcdc', isDark: true },
    { id: 'theme-vintage-brooch', name: 'سنجاق سینه وینتج', primary: '#c0a080', bg: '#3a322a', text: '#e6e0d9', isDark: true },
    { id: 'theme-dark-lily', name: 'سوسن تیره', primary: '#d8a8d8', bg: '#261e26', text: '#f0e3f0', isDark: true },
    { id: 'theme-sultan-palace', name: 'کاخ سلطان', primary: '#daa520', bg: '#291d0a', text: '#e9e2cc', isDark: true },
    { id: 'theme-heirloom-gold', name: 'طلای موروثی', primary: '#c2a66c', bg: '#332b1e', text: '#e6e0d3', isDark: true },
    { id: 'theme-smoky-amethyst', name: 'آمتیست دودی', primary: '#a993b8', bg: '#2d2833', text: '#e4e0e8', isDark: true },
    { id: 'theme-dark-brocade', name: 'زربفت تیره', primary: '#b5926c', bg: '#332a22', text: '#e4e0d8', isDark: true },
    { id: 'theme-secret-garden-night', name: 'باغ اسرارآمیز شب', primary: '#8baf8b', bg: '#222e22', text: '#d8e2d8', isDark: true },
    { id: 'theme-regal-blue', name: 'آبی باشکوه', primary: '#6a89c0', bg: '#222a3b', text: '#d4dae6', isDark: true },
    { id: 'theme-maharaja-jewel', name: 'جواهر مهاراجه', primary: '#ff8c00', bg: '#3b220a', text: '#f2e5d1', isDark: true },
    { id: 'theme-dark-cashmere', name: 'ترمه تیره', primary: '#b3a595', bg: '#33302c', text: '#e6e3e0', isDark: true },
    { id: 'theme-winter-palace', name: 'کاخ زمستانی', primary: '#a4c6d5', bg: '#2c353b', text: '#dfe8ec', isDark: true },
    { id: 'theme-ancient-gold', name: 'طلای باستانی', primary: '#b89b58', bg: '#332a1a', text: '#e4deca', isDark: true },
    // END of 25 new Classic Dark themes
  ],
  modernLight: [
    { id: 'theme-joes', name: 'Joes', isDark: false, primary: '#004080', bg: '#F5F5DC', text: '#3A3A3A', card: '#BBDDFF', cellInactive: '#F5F5DC', completedBg: '#F5F5DC' },
    { id: 'theme-sakura', name: 'ساکورا', primary: '#db88b5', bg: '#fff6f9', text: '#5b4d53', isDark: false },
    { id: 'theme-seaside', name: 'ساحلی', primary: '#1d74c4', bg: '#eef7ff', text: '#0b3954', isDark: false },
    { id: 'theme-matcha', name: 'ماچا', primary: '#75a99c', bg: '#f5f5e8', text: '#4a4a42', isDark: false },
    { id: 'theme-peaches', name: 'هلو', primary: '#ff6b6b', bg: '#fff2f2', text: '#5e3b3b', isDark: false },
    { id: 'theme-lavender', name: 'اسطوخودوس', primary: '#8a63d2', bg: '#f7f4ff', text: '#4b3d60', isDark: false },
    { id: 'theme-cotton-candy', name: 'پشمک', primary: '#ff9dcb', bg: '#f0f8ff', text: '#5b6a78', isDark: false },
    { id: 'theme-gummybear', name: 'پاستیلی', primary: '#ef476f', bg: '#ffffff', text: '#073b4c', isDark: false },
    { id: 'theme-snes-light', name: 'SNES روشن', primary: '#e60012', bg: '#e8e8e8', text: '#2c2c2c', isDark: false },
    { id: 'theme-playstation-light', name: 'پلی‌استیشن روشن', primary: '#006fcd', bg: '#eef2f7', text: '#333333', isDark: false },
    { id: 'theme-gold-light', name: 'طلای روشن', primary: '#b59410', bg: '#fdfaf0', text: '#3d3419', isDark: false },
    { id: 'theme-rose-gold-light', name: 'رزگلد روشن', primary: '#b76e79', bg: '#fcf6f7', text: '#5c373d', isDark: false },
    { id: 'theme-silver-light', name: 'نقره‌ای روشن', primary: '#8c8c8c', bg: '#f7f7f7', text: '#333333', isDark: false },
    { id: 'theme-ios-light', name: 'iOS روشن', primary: '#007aff', bg: '#f2f2f7', text: '#000000', isDark: false },
    { id: 'theme-pastel-dream', name: 'رویای پاستلی', primary: '#ffc0cb', bg: '#fdf5f6', text: '#6d5458', isDark: false },
    { id: 'theme-floral', name: 'گل‌گلی', primary: '#de5b83', bg: '#f9f2f5', text: '#573a45', isDark: false },
    { id: 'theme-strawberry', name: 'توت‌فرنگی', primary: '#e53935', bg: '#fff2f2', text: '#5e3b3b', isDark: false },
    { id: 'theme-blueberry', name: 'بلوبری', primary: '#3f51b5', bg: '#f2f3ff', text: '#39405f', isDark: false },
    { id: 'theme-apricot', name: 'زردآلو', primary: '#fb8c00', bg: '#fff8f0', text: '#613800', isDark: false },
    { id: 'theme-sky', name: 'آسمان', primary: '#03a9f4', bg: '#f0f9ff', text: '#014361', isDark: false },
    { id: 'theme-lilac', name: 'یاسی', primary: '#b39ddb', bg: '#f9f7fd', text: '#512da8', isDark: false },
    // START of 50 new Modern Light themes
    { id: 'theme-santorini', name: 'سانتورینی', primary: '#0057b7', bg: '#f4f8ff', text: '#2a3a57', isDark: false },
    { id: 'theme-champagne', name: 'شامپاین', primary: '#c9a77d', bg: '#fcf8f0', text: '#5d4b35', isDark: false },
    { id: 'theme-pearl', name: 'مروارید', primary: '#a0d2d8', bg: '#f6fafd', text: '#4a6063', isDark: false },
    { id: 'theme-watercolor', name: 'آبرنگ', primary: '#b19cd9', bg: '#f9f7fd', text: '#5c4e6e', isDark: false },
    { id: 'theme-sorbet', name: 'سوربت', primary: '#ff8c94', bg: '#fff5f6', text: '#6e3c40', isDark: false },
    { id: 'theme-scandinavian', name: 'اسکاندیناوی', primary: '#8da9c4', bg: '#f5f7fa', text: '#3c4a57', isDark: false },
    { id: 'theme-golden-hour', name: 'ساعت طلایی', primary: '#ffc55c', bg: '#fff9ed', text: '#6b501e', isDark: false },
    { id: 'theme-blue-lagoon', name: 'تالاب آبی', primary: '#00bfff', bg: '#f0fbff', text: '#00536b', isDark: false },
    { id: 'theme-succulent', name: 'ساکولنت', primary: '#7aa98b', bg: '#f4faf6', text: '#43574b', isDark: false },
    { id: 'theme-couture', name: 'کوتور', primary: '#c0a0c0', bg: '#f9f5f9', text: '#5a4a5a', isDark: false },
    { id: 'theme-parisian-cafe', name: 'کافه پاریسی', primary: '#d4af37', bg: '#fdfcf7', text: '#5e4e24', isDark: false },
    { id: 'theme-minimal-tech', name: 'تک مینیمال', primary: '#6c757d', bg: '#f8f9fa', text: '#212529', isDark: false },
    { id: 'theme-glass-ui', name: 'رابط شیشه‌ای', primary: '#6a85e3', bg: '#f0f3ff', text: '#3c4873', isDark: false },
    { id: 'theme-silk', name: 'ابریشم', primary: '#d4b8c0', bg: '#fdf8f9', text: '#645458', isDark: false },
    { id: 'theme-lipstick-red', name: 'قرمز ماتیکی', primary: '#c71585', bg: '#fdf2f7', text: '#5b243e', isDark: false },
    { id: 'theme-diamond-light', name: 'الماس روشن', primary: '#80bdde', bg: '#f3f9fc', text: '#3d5966', isDark: false },
    { id: 'theme-holographic-light', name: 'هولوگرافیک روشن', primary: '#be93d4', bg: '#f9f5fc', text: '#584565', isDark: false },
    { id: 'theme-marshmallow', name: 'مارشمالو', primary: '#f4b6c2', bg: '#fdf7f9', text: '#675055', isDark: false },
    { id: 'theme-ice-cream', name: 'بستنی', primary: '#f999b7', bg: '#fff5f8', text: '#6b4352', isDark: false },
    { id: 'theme-kyoto-garden', name: 'باغ کیوتو', primary: '#6fa673', bg: '#f3f9f3', text: '#3e5840', isDark: false },
    { id: 'theme-spring-blossom', name: 'شکوفه بهاری', primary: '#ffb7c5', bg: '#fff8f9', text: '#6e5157', isDark: false },
    { id: 'theme-macaron', name: 'ماکارون', primary: '#f6a6b2', bg: '#fef6f7', text: '#69484d', isDark: false },
    { id: 'theme-clean-code', name: 'کد تمیز', primary: '#007acc', bg: '#fcfcfc', text: '#2d2d2d', isDark: false },

    { id: 'theme-candy-floss', name: 'پشمک صورتی', primary: '#f6a8cc', bg: '#fef6fa', text: '#6a4959', isDark: false },
    { id: 'theme-sunny-day', name: 'روز آفتابی', primary: '#ffd700', bg: '#fffdf0', text: '#665700', isDark: false },
    { id: 'theme-fresh-air', name: 'هوای تازه', primary: '#87ceeb', bg: '#f5fbfe', text: '#40606e', isDark: false },
    { id: 'theme-peony', name: 'گل صدتومانی', primary: '#e89ab8', bg: '#fdf5f8', text: '#654452', isDark: false },

    { id: 'theme-flamingo', name: 'فلامینگو', primary: '#fc8eac', bg: '#fff6f8', text: '#6b3d4a', isDark: false },
    { id: 'theme-tiffany-blue', name: 'آبی تیفانی', primary: '#0abab5', bg: '#f0fafa', text: '#054e4c', isDark: false },
    { id: 'theme-hummingbird', name: 'مرغ مگس‌خوار', primary: '#b15a9a', bg: '#f9f2f8', text: '#502945', isDark: false },
    { id: 'theme-bauhaus-light', name: 'باوهاوس روشن', primary: '#e63946', bg: '#f1faee', text: '#1d3557', isDark: false },
    { id: 'theme-coral-reef-light', name: 'صخره مرجانی', primary: '#ff6f61', bg: '#fef4f3', text: '#6e3029', isDark: false },
    { id: 'theme-white-orchid', name: 'ارکیده سفید', primary: '#a8a8a8', bg: '#fcfcfc', text: '#4d4d4d', isDark: false },
    { id: 'theme-daydream', name: 'رویاپردازی', primary: '#a0c4ff', bg: '#f6f9ff', text: '#4a5b78', isDark: false },
    { id: 'theme-moma', name: 'موما', primary: '#e63946', bg: '#ffffff', text: '#1d3557', isDark: false },
    { id: 'theme-angel-food', name: 'کیک آنجل', primary: '#dbcba8', bg: '#fdfbf5', text: '#655b49', isDark: false },
    { id: 'theme-frosted-glass', name: 'شیشه مات', primary: '#a9cce3', bg: '#f7fafc', text: '#4d5c66', isDark: false },
    { id: 'theme-coconut', name: 'نارگیل', primary: '#a4886e', bg: '#fbfaf8', text: '#493d31', isDark: false },
    { id: 'theme-lemonade', name: 'لیموناد', primary: '#fce16d', bg: '#fffdef', text: '#695f2e', isDark: false },
    { id: 'theme-sea-salt', name: 'نمک دریا', primary: '#a0b8c8', bg: '#f7f9fa', text: '#48535a', isDark: false },
    { id: 'theme-celadon', name: 'سبز سلادون', primary: '#ace1af', bg: '#f7fcf7', text: '#4d664f', isDark: false },
    { id: 'theme-cloud', name: 'ابر', primary: '#b0c4de', bg: '#f8f9fc', text: '#4e5a68', isDark: false },
    { id: 'theme-quartz', name: 'کوارتز', primary: '#d7c7d9', bg: '#fcfafc', text: '#625963', isDark: false },
    { id: 'theme-breeze', name: 'نسیم', primary: '#a9d6e5', bg: '#f7fbfe', text: '#4c626a', isDark: false },
    { id: 'theme-periwinkle', name: 'پیچ امین‌الدوله', primary: '#ccccff', bg: '#fafafe', text: '#5c5c73', isDark: false },
    { id: 'theme-baby-blue', name: 'آبی نوزادی', primary: '#89cff0', bg: '#f5faff', text: '#3f5e6e', isDark: false },
    { id: 'theme-peach-sorbet', name: 'سوربت هلو', primary: '#ffb997', bg: '#fff8f5', text: '#6e4f3f', isDark: false },
    { id: 'theme-wildflower', name: 'گل وحشی', primary: '#dea5a4', bg: '#fcf6f6', text: '#644949', isDark: false },
    { id: 'theme-buttercream', name: 'کرم کره‌ای', primary: '#f6e5b3', bg: '#fefbf0', text: '#69624d', isDark: false },
    { id: 'theme-mint-green', name: 'سبز نعنایی', primary: '#98ff98', bg: '#f7fff7', text: '#447344', isDark: false },
    // END of 50 new Modern Light themes
        // START of 25 new Modern Light themes
    { id: 'theme-diamond-dust', name: 'گرد الماس', primary: '#a4c6d5', bg: '#f8fafc', text: '#4a5a62', isDark: false },
    { id: 'theme-crystal-clear', name: 'کریستال شفاف', primary: '#80bdde', bg: '#f3f9fc', text: '#3d5966', isDark: false },
    { id: 'theme-luxury-boutique', name: 'بوتیک لوکس', primary: '#c0a0c0', bg: '#f9f5f9', text: '#5a4a5a', isDark: false },
    { id: 'theme-white-gold', name: 'طلای سفید', primary: '#d4c8b8', bg: '#fcfaf8', text: '#605a52', isDark: false },

    { id: 'theme-peony-blush', name: 'سرخی پیونی', primary: '#e89ab8', bg: '#fdf5f8', text: '#654452', isDark: false },
    { id: 'theme-silk-kimono', name: 'کیمونوی ابریشمی', primary: '#d4a8b4', bg: '#fdf6f8', text: '#614b51', isDark: false },
    { id: 'theme-glass-palace', name: 'کاخ شیشه‌ای', primary: '#a9d6e5', bg: '#f7fbfe', text: '#4c626a', isDark: false },
    { id: 'theme-champagne-toast', name: 'نوش شامپاین', primary: '#f6e5b3', bg: '#fefbf0', text: '#69624d', isDark: false },
    { id: 'theme-opalescent', name: 'اوپال', primary: '#b8d8d2', bg: '#f8fbfb', text: '#53635f', isDark: false },
    { id: 'theme-white-orchid', name: 'ارکیده سفید', primary: '#b0b0b0', bg: '#fcfcfc', text: '#505050', isDark: false },
    { id: 'theme-rose-quartz-gold', name: 'رز کوارتز و طلا', primary: '#e6b3b8', bg: '#fdf8f8', text: '#685053', isDark: false },
    { id: 'theme-modern-princess', name: 'پرنسس مدرن', primary: '#f4c2c2', bg: '#fef9f9', text: '#685656', isDark: false },
    { id: 'theme-high-jewelry', name: 'جواهرات فاخر', primary: '#87cefa', bg: '#f5faff', text: '#3e5e72', isDark: false },
    { id: 'theme-satin-sheets', name: 'ملحفه ساتن', primary: '#d8c0c8', bg: '#fcf9fa', text: '#63565a', isDark: false },
    { id: 'theme-lily-of-the-valley', name: 'گل برف', primary: '#a8d8a8', bg: '#f7fcf7', text: '#4b634b', isDark: false },
    { id: 'theme-crystal-chandelier', name: 'لوستر کریستال', primary: '#c0c0c0', bg: '#f9f9f9', text: '#585858', isDark: false },
    { id: 'theme-golden-petal', name: 'گلبرگ طلایی', primary: '#ffd700', bg: '#fffdf0', text: '#665700', isDark: false },
    { id: 'theme-blush-silk', name: 'ابریشم رژگونه‌ای', primary: '#e6b8c2', bg: '#fdf8f9', text: '#685358', isDark: false },
    { id: 'theme-beverly-hills', name: 'بورلی هیلز', primary: '#ffb6c1', bg: '#fff8f9', text: '#6e5155', isDark: false },
    { id: 'theme-platinum', name: 'پلاتین', primary: '#cdd4da', bg: '#fafbfc', text: '#5d6165', isDark: false },
    { id: 'theme-magnolia', name: 'ماگنولیا', primary: '#d4bca2', bg: '#fdfaf5', text: '#605548', isDark: false },
    { id: 'theme-luxe-life', name: 'زندگی لوکس', primary: '#d4af37', bg: '#fdfcf7', text: '#5e4e24', isDark: false },
    { id: 'theme-frosted-rose', name: 'رز مات', primary: '#e0b0c0', bg: '#fdf7f9', text: '#654f57', isDark: false },
    { id: 'theme-aquamarine', name: 'آکوامارین', primary: '#7fffd4', bg: '#f4fffa', text: '#387363', isDark: false },
    { id: 'theme-white-diamond', name: 'الماس سفید', primary: '#b9f2ff', bg: '#f8fcfe', text: '#536d75', isDark: false },
    // END of 25 new Modern Light themes
  ],
  classicLight: [
    { id: 'theme-solarized-light', name: 'سولارایزد', primary: '#d33682', bg: '#fdf6e3', text: '#586e75', isDark: false },
    { id: 'theme-gruvbox-light', name: 'گراوباکس', primary: '#d65d0e', bg: '#fbf1c7', text: '#3c3836', isDark: false },
    { id: 'theme-daylight', name: 'روز روشن', primary: '#007bff', bg: '#f0f8ff', text: '#212529', isDark: false },
    { id: 'theme-paper', name: 'کاغذی', primary: '#d94d41', bg: '#f7f6f1', text: '#3a3a3a', isDark: false },
    { id: 'theme-classic-mac', name: 'مک کلاسیک', primary: '#000000', bg: '#e0e0e0', text: '#000000', isDark: false },
    { id: 'theme-blueprint', name: 'بلوپرینت', primary: '#295ddc', bg: '#eff3f9', text: '#333a56', isDark: false },
    { id: 'theme-sepia', name: 'سپیا', primary: '#704214', bg: '#fbf0d9', text: '#4a2d0b', isDark: false },
    { id: 'theme-mint-choco', name: 'نعنا شکلاتی', primary: '#3d2b24', bg: '#f0fff0', text: '#513e36', isDark: false },
    { id: 'theme-desert-oasis', name: 'واحه', primary: '#00bcd4', bg: '#faf3e0', text: '#7a6a53', isDark: false },
    { id: 'theme-botanical', name: 'گیاه‌شناسی', primary: '#4caf50', bg: '#f5fcf5', text: '#3e503f', isDark: false },
    { id: 'theme-e-ink', name: 'جوهر الکترونیک', primary: '#000000', bg: '#f5f5f5', text: '#333333', isDark: false },
    { id: 'theme-minimal-white', name: 'مینیمال', primary: '#888888', bg: '#ffffff', text: '#222222', isDark: false },
    { id: 'theme-newspaper', name: 'روزنامه', primary: '#d11c11', bg: '#f8f8f2', text: '#1c1c1a', isDark: false },
    { id: 'theme-gameboy-light', name: 'گیم‌بوی روشن', primary: '#0f380f', bg: '#9bbc0f', text: '#0f380f', isDark: false },
    { id: 'theme-dune-light', name: 'تل‌ماسه روشن', primary: '#a0522d', bg: '#f4e8d8', text: '#5d4037', isDark: false },
    { id: 'theme-vanilla', name: 'وانیلی', primary: '#8d6e63', bg: '#fdfcf7', text: '#4e342e', isDark: false },
    { id: 'theme-pistachio', name: 'پسته‌ای', primary: '#7cb342', bg: '#f7fff2', text: '#33491c', isDark: false },
    { id: 'theme-sand', name: 'شنی', primary: '#c2b280', bg: '#fbf9f4', text: '#5a523c', isDark: false },
    { id: 'theme-rose-quartz', name: 'رز کوارتز', primary: '#f0a1b8', bg: '#fdf6f8', text: '#6b404c', isDark: false },
    { id: 'theme-serenity', name: 'آرامش', primary: '#92a8d1', bg: '#f6f8fd', text: '#444e60', isDark: false },
    // START of 50 new Classic Light themes
    { id: 'theme-monet', name: 'کلود مونه', primary: '#6f9eaf', bg: '#f2f5f6', text: '#405861', isDark: false },
    { id: 'theme-parchment-light', name: 'پوست روشن', primary: '#a88d5e', bg: '#fbf8f0', text: '#4c3f29', isDark: false },
    { id: 'theme-vintage-dress', name: 'لباس وینتج', primary: '#c9898b', bg: '#fdfaed', text: '#6b5a5a', isDark: false },
    { id: 'theme-terracotta', name: 'تراکوتا', primary: '#e2725b', bg: '#fdf3f1', text: '#643229', isDark: false },
    { id: 'theme-linen', name: 'کتان', primary: '#b8a99a', bg: '#fbf9f7', text: '#544d46', isDark: false },
    { id: 'theme-old-hollywood', name: 'هالیوود قدیم', primary: '#daa520', bg: '#fdf9e8', text: '#61490d', isDark: false },
    { id: 'theme-french-riviera', name: 'ریویرای فرانسه', primary: '#0077b6', bg: '#eef8fc', text: '#003652', isDark: false },
    { id: 'theme-tuscany', name: 'توسکانی', primary: '#c89f64', bg: '#fcf7ed', text: '#5a472c', isDark: false },
    { id: 'theme-provence', name: 'پروانس', primary: '#9e8fb9', bg: '#f8f6fb', text: '#484254', isDark: false },
    { id: 'theme-heirloom', name: 'موروثی', primary: '#b48e8e', bg: '#fbf6f6', text: '#514141', isDark: false },
    { id: 'theme-pressed-flowers', name: 'گل‌های خشک', primary: '#a87ca8', bg: '#f9f5f9', text: '#4c394c', isDark: false },
    { id: 'theme-porcelain', name: 'پرسلان', primary: '#8db7d1', bg: '#f5f8fa', text: '#405360', isDark: false },
    { id: 'theme-calligraphy', name: 'خوشنویسی', primary: '#6e6e6e', bg: '#f9f9f9', text: '#333333', isDark: false },
    { id: 'theme-tea-stain', name: 'لکه چای', primary: '#c6a88b', bg: '#fbf8f4', text: '#594a3b', isDark: false },
    { id: 'theme-antique-brass', name: 'برنج عتیقه', primary: '#c9a96e', bg: '#fcf8f0', text: '#5a4a30', isDark: false },
    { id: 'theme-cameo', name: 'کامئو', primary: '#d4b4a4', bg: '#fdf8f6', text: '#605149', isDark: false },
    { id: 'theme-sea-glass', name: 'شیشه دریایی', primary: '#86b4a7', bg: '#f5faf9', text: '#3d514b', isDark: false },
    { id: 'theme-ivory', name: 'عاجی', primary: '#a1887f', bg: '#fffdfa', text: '#493d39', isDark: false },
    { id: 'theme-khaki', name: 'خاکی', primary: '#c3b091', bg: '#faf8f4', text: '#585042', isDark: false },
    { id: 'theme-wedgwood', name: 'وج‌وود', primary: '#9ab3d3', bg: '#f6f8fb', text: '#465161', isDark: false },
    { id: 'theme-naturalist', name: 'طبیعت‌گرا', primary: '#8f9d78', bg: '#f7f8f4', text: '#414837', isDark: false },
    { id: 'theme-sage', name: 'مریم‌گلی', primary: '#a2b4a5', bg: '#f7f9f7', text: '#49524a', isDark: false },
    { id: 'theme-stone', name: 'سنگی', primary: '#b0ab9a', bg: '#f9f9f7', text: '#504d46', isDark: false },
    { id: 'theme-willow', name: 'بید', primary: '#a3b596', bg: '#f8faf6', text: '#495244', isDark: false },
    { id: 'theme-heather', name: 'خلنگ', primary: '#c4a6c4', bg: '#faf7fa', text: '#584a58', isDark: false },
    { id: 'theme-oxford', name: 'آکسفورد', primary: '#879bba', bg: '#f5f7f9', text: '#3e4855', isDark: false },
    { id: 'theme-cashmere', name: 'ترمه', primary: '#d1c4b4', bg: '#fcfaf8', text: '#5f5850', isDark: false },
    { id: 'theme-latte', name: 'لاته', primary: '#c3a995', bg: '#faf7f5', text: '#584c44', isDark: false },
    { id: 'theme-buttercup', name: 'آلاله', primary: '#f3da73', bg: '#fefbec', text: '#695f31', isDark: false },
    { id: 'theme-driftwood', name: 'چوب آب‌آورده', primary: '#b7a89b', bg: '#faf8f7', text: '#534c46', isDark: false },
    { id: 'theme-parisian-apartment', name: 'آپارتمان پاریسی', primary: '#d4af37', bg: '#f9f8f6', text: '#5e4e24', isDark: false },
    { id: 'theme-renaissance-fresco', name: 'فرسک رنسانس', primary: '#d7a98b', bg: '#fbf5f2', text: '#624b3c', isDark: false },
    { id: 'theme-claire-de-lune', name: 'مهتاب', primary: '#a1b6d1', bg: '#f7f9fc', text: '#495360', isDark: false },
    { id: 'theme-english-garden', name: 'باغ انگلیسی', primary: '#de7a95', bg: '#fcf3f6', text: '#643744', isDark: false },
    { id: 'theme-chinoiserie', name: 'چینی‌کاری', primary: '#6995b3', bg: '#f2f6f9', text: '#304451', isDark: false },
    { id: 'theme-greige', name: 'خاکستری‌بژ', primary: '#c0b6a8', bg: '#f9f8f7', text: '#57524c', isDark: false },
    { id: 'ivory-tower', name: 'برج عاج', primary: '#9e917d', bg: '#fcfaf6', text: '#484238', isDark: false },
    { id: 'theme-art-nouveau-light', name: 'آرت نوو روشن', primary: '#b8a383', bg: '#fbf8f4', text: '#54493a', isDark: false },
    { id: 'theme-taupe', name: 'قهوه‌ای دودی', primary: '#b3a595', bg: '#f9f8f6', text: '#514a44', isDark: false },
    { id: 'theme-alabaster', name: 'آلاباستر', primary: '#c2b8b0', bg: '#fcfbf9', text: '#58544f', isDark: false },
    { id: 'theme-venetian', name: 'ونیزی', primary: '#d28f8f', bg: '#fdf5f5', text: '#5f4141', isDark: false },
    { id: 'theme-wisteria', name: 'ویستریا', primary: '#b79fc9', bg: '#f9f6fc', text: '#53485b', isDark: false },
    { id: 'theme-oatmeal', name: 'بلغور جو دوسر', primary: '#d4c8be', bg: '#fcfaf8', text: '#605a55', isdark: false },
    { id: 'theme-pottery', name: 'سفالگری', primary: '#b97b62', bg: '#f9f4f2', text: '#54382c', isDark: false },
    { id: 'theme-bisque', name: 'بیسک', primary: '#d3b8ae', bg: '#fdf8f7', text: '#5f534e', isDark: false },
    { id: 'theme-ecru', name: 'اکرو', primary: '#d4c7a6', bg: '#fcfaf3', text: '#60594a', isDark: false },
    { id: 'theme-classic-linen', name: 'کتان کلاسیک', primary: '#c9c0b4', bg: '#faf9f8', text: '#5b5650', isDark: false },
    { id: 'theme-dove-grey', name: 'خاکستری کبوتری', primary: '#bdbdbd', bg: '#f9f9f9', text: '#555555', isDark: false },
    { id: 'theme-bone-white', name: 'سفید استخوانی', primary: '#c5bbae', bg: '#fbfaf8', text: '#59544e', isDark: false },
    { id: 'theme-putty', name: 'بتونه‌ای', primary: '#c8bdae', bg: '#faf9f7', text: '#5a544e', isDark: false },
    // END of 50 new Classic Light themes
        // START of 25 new Classic Light themes
    { id: 'theme-pearl-necklace', name: 'گردنبند مروارید', primary: '#c8b8a8', bg: '#fbf9f7', text: '#5a534c', isDark: false },
    { id: 'theme-versailles-day', name: 'روز ورسای', primary: '#d4b77a', bg: '#fdf9f1', text: '#5f5236', isDark: false },
    { id: 'theme-antique-lace', name: 'توری عتیقه', primary: '#dcd0c0', bg: '#fdfbf9', text: '#635d55', isDark: false },
    { id: 'theme-rose-garden', name: 'باغ رز', primary: '#d98c9c', bg: '#fdf4f6', text: '#623e46', isDark: false },
    { id: 'theme-heirloom-pearl', name: 'مروارید موروثی', primary: '#d1c4b8', bg: '#fbfaf8', text: '#5f5852', isDark: false },
    { id: 'theme-porcelain-doll', name: 'عروسک پرسلان', primary: '#d4b8b8', bg: '#fdf8f8', text: '#605353', isDark: false },
    { id: 'theme-tiffany-breakfast', name: 'صبحانه در تیفانی', primary: '#81d8d0', bg: '#f4fbfb', text: '#3a635f', isDark: false },
    { id: 'theme-silk-scarf', name: 'روسری ابریشمی', primary: '#c0a0a0', bg: '#f9f5f5', text: '#5a4a4a', isDark: false },
    { id: 'theme-cameo-pink', name: 'صورتی کامئو', primary: '#e6c4ba', bg: '#fdfaf8', text: '#685852', isDark: false },
    { id: 'theme-gold-leaf', name: 'ورق طلا', primary: '#e0c47f', bg: '#fdfaf2', text: '#645839', isDark: false },
    { id: 'theme-vintage-rose', name: 'رز وینتج', primary: '#d4a3a3', bg: '#fcf6f6', text: '#604949', isDark: false },
    { id: 'theme-marble-palace', name: 'کاخ مرمر', primary: '#c0c0c0', bg: '#f9f9f9', text: '#585858', isDark: false },
    { id: 'theme-chantilly-lace', name: 'توری شانتیلی', primary: '#d8c8b8', bg: '#fdfaf8', text: '#625a52', isDark: false },
    { id: 'theme-hydrangea', name: 'گل ادریسی', primary: '#a8b8d8', bg: '#f7f8fc', text: '#4c5363', isDark: false },
    { id: 'theme-gold-filigree', name: 'ملیله‌کاری طلا', primary: '#d4b370', bg: '#fdf8f0', text: '#5f5031', isDark: false },
    { id: 'theme-rococo', name: 'روکوکو', primary: '#f0c0a0', bg: '#fdf8f5', text: '#6b5547', isDark: false },
    { id: 'theme-english-rose', name: 'رز انگلیسی', primary: '#e0a8b8', bg: '#fdf6f8', text: '#654b53', isDark: false },
    { id: 'theme-angel-skin-coral', name: 'مرجان پوست‌فرشته‌ای', primary: '#f4b8a8', bg: '#fef8f6', text: '#68534b', isDark: false },

    { id: 'theme-summer-palace', name: 'کاخ تابستانی', primary: '#f2d8a8', bg: '#fefbf5', text: '#685f4b', isDark: false },
    { id: 'theme-satin-gown', name: 'لباس ساتن', primary: '#c8b0b8', bg: '#faf7f8', text: '#5a4f53', isDark: false },
    { id: 'theme-morganite', name: 'مورگانیت', primary: '#e6b4b4', bg: '#fdf8f8', text: '#685151', isDark: false },
    { id: 'theme-classic-pearl', name: 'مروارید کلاسیک', primary: '#d8d0c8', bg: '#fcfbf9', text: '#625d5a', isDark: false },
    { id: 'theme-gilded-rose', name: 'رز طلاکاری‌شده', primary: '#daa520', bg: '#fdf9e8', text: '#61490d', isDark: false },
    { id: 'theme-ivory-silk', name: 'ابریشم عاجی', primary: '#dcd0c0', bg: '#fdfbf9', text: '#635d55', isDark: false },
    { id: 'theme-celadon-glaze', name: 'لعاب سلادون', primary: '#b3d1b3', bg: '#f8fbf8', text: '#505f50', isDark: false } ],
  new: [

    // ===================================================================
  // ===== دسته ۱: سایبرپانک، نئون و آینده‌گرایی (۱-۴۰) =====
  // ===================================================================
  { id: 'theme-cyberpunk-classic', name: 'سایبرپانک کلاسیک', primary: '#ea00d9', bg: '#0d0221', text: '#00f0ff', isDark: true },
  { id: 'theme-neon-noir', name: 'نئو نوآر', primary: '#f222ff', bg: '#212130', text: '#8dffcd', isDark: true },
  { id: 'theme-megacity-rain', name: 'باران در مگاسیتی', primary: '#4cc9f0', bg: '#03045e', text: '#ffffff', isDark: true },
  { id: 'theme-glitch-effect', name: 'افکت گلیچ', primary: '#ff0054', bg: '#101010', text: '#00f6ff', isDark: true },
  { id: 'theme-tokyo-night', name: 'شب‌های توکیو', primary: '#ff3d8d', bg: '#1a183e', text: '#9effee', isDark: true },
  { id: 'theme-data-stream', name: 'جریان داده', primary: '#39ff14', bg: '#050203', text: '#ffffff', isDark: true },
  { id: 'theme-android-dream', name: 'رویای اندروید', primary: '#a6fffa', bg: '#0c0c27', text: '#f9f871', isDark: true },
  { id: 'theme-virtual-reality', name: 'واقعیت مجازی', primary: '#7209b7', bg: '#120421', text: '#f0f0f0', isDark: true },
  { id: 'theme-laser-grid', name: 'شبکه لیزری', primary: '#ff073a', bg: '#000000', text: '#00e5ff', isDark: true },
  { id: 'theme-hacker-terminal', name: 'ترمینال هکر', primary: '#32cd32', bg: '#0a0a0a', text: '#f0f0f0', isDark: true },
  { id: 'theme-cyber-magenta', name: 'سرخابی سایبری', primary: '#e0115f', bg: '#1e1b34', text: '#c1fff6', isDark: true },
  { id: 'theme-synthwave-sunset', name: 'غروب سینث‌ویو', primary: '#ff6c11', bg: '#2b0f42', text: '#ffc6d9', isDark: true },
  { id: 'theme-holo-ads', name: 'تبلیغات هولوگرافیک', primary: '#fef02d', bg: '#0a113a', text: '#ffffff', isDark: true },
  { id: 'theme-dark-street', name: 'خیابان تاریک', primary: '#d92121', bg: '#121212', text: '#b3b3b3', isDark: true },
  { id: 'theme-robot-eye', name: 'چشم ربات', primary: '#ff4b1f', bg: '#0d1317', text: '#a2b4bd', isDark: true },
  { id: 'theme-cyberpunk-2077-arasaka', name: 'برج آراساکا', primary: '#e5342a', bg: '#1c1c1c', text: '#f0f0f0', isDark: true },
  { id: 'theme-cyberpunk-2077-watson', name: 'نئون‌های واتسون', primary: '#ffd60a', bg: '#001219', text: '#f1faee', isDark: true },
  { id: 'theme-cyberpunk-2077-badlands', name: ' بدلندز', primary: '#fca311', bg: '#4d2c1d', text: '#faedcd', isDark: true },
  { id: 'theme-posthuman', name: 'پسا-انسان', primary: '#ced4da', bg: '#0b090a', text: '#80ed99', isDark: true },
  { id: 'theme-dystopian-future', name: 'آینده ویران‌شهری', primary: '#ffc107', bg: '#343a40', text: '#dee2e6', isDark: true },
  { id: 'theme-utopian-core', name: 'هسته آرمان‌شهر', primary: '#2ec4b6', bg: '#f0fcfb', text: '#011627', isDark: false },
  { id: 'theme-mech-battle', name: 'نبرد ربات‌ها', primary: '#e63946', bg: '#495057', text: '#f1faee', isDark: true },
  { id: 'theme-space-colony', name: 'مستعمره فضایی', primary: '#00b4d8', bg: '#e9ecef', text: '#03045e', isDark: false },
  { id: 'theme-bio-luminescence', name: 'زیست‌تابی', primary: '#40f99b', bg: '#023c40', text: '#e6fcf5', isDark: true },
  { id: 'theme-quantum-foam', name: 'کف کوانتومی', primary: '#9b5de5', bg: '#130b21', text: '#f0f0f0', isDark: true },
  { id: 'theme-singularity', name: 'تکینگی', primary: '#ffffff', bg: '#000000', text: '#cccccc', isDark: true },
  { id: 'theme-jet-engine', name: 'موتور جت', primary: '#f77f00', bg: '#3e4a61', text: '#eae2b7', isDark: true },
  { id: 'theme-cryo-sleep', name: 'خواب کرایو', primary: '#a2d2ff', bg: '#041533', text: '#e9f6ff', isDark: true },
  { id: 'theme-sentient-ai', name: 'هوش مصنوعی خودآگاه', primary: '#4361ee', bg: '#f8f9fa', text: '#343a40', isDark: false },
  { id: 'theme-hardwired', name: 'سیم‌کشی شده', primary: '#f94144', bg: '#2b2d42', text: '#edf2f4', isDark: true },
  { id: 'theme-night-city-chrome', name: 'کروم نایت‌سیتی', primary: '#c0c0c0', bg: '#101010', text: '#ff0054', isDark: true },
  { id: 'theme-arcology', name: 'آرکولوژی', primary: '#55a630', bg: '#0b090a', text: '#e0e1dd', isDark: true },
  { id: 'theme-fusion-core', name: 'هسته فیوژن', primary: '#ffc300', bg: '#003566', text: '#ffddd2', isDark: true },
  { id: 'theme-terraforming-mars', name: 'ترافرمینگ مریخ', primary: '#e76f51', bg: '#264653', text: '#f1faee', isDark: true },
  { id: 'theme-orbital-station', name: 'ایستگاه مداری', primary: '#dee2e6', bg: '#0d1b2a', text: '#e0e1dd', isDark: true },
  { id: 'theme-void-ship', name: 'کشتی خلأ', primary: '#9d4edd', bg: '#03071e', text: '#e5e5e5', isDark: true },
  { id: 'theme-digital-ghost', name: 'شبح دیجیتال', primary: '#caf0f8', bg: '#023e8a', text: '#ffffff', isDark: true },
  { id: 'theme-plasma-drive', name: 'پیشرانه پلاسما', primary: '#f72585', bg: '#1c0b2c', text: '#e9f6ff', isDark: true },
  { id: 'theme-exo-suit', name: 'لباس اگزو', primary: '#ff9e00', bg: '#495057', text: '#f8f9fa', isDark: true },
  { id: 'theme-nanotech', name: 'نانوتکنولوژی', primary: '#6c757d', bg: '#141414', text: '#e9ecef', isDark: true },

  // ===================================================================
  // ===== دسته ۲: بازی‌های ویدئویی (۴۱-۹۰) =====
  // ===================================================================
  // Ghost of Tsushima
  { id: 'theme-tsushima-autumn', name: 'پاییز تسوشیما', primary: '#e63946', bg: '#2c2a2e', text: '#f1faee', isDark: true },
  { id: 'theme-tsushima-golden', name: 'جنگل طلایی', primary: '#ffc300', bg: '#212529', text: '#ffffff', isDark: true },
  { id: 'theme-tsushima-spring', name: 'بهار ایزوهارا', primary: '#ffb3c1', bg: '#f8f9fa', text: '#343a40', isDark: false },
  { id: 'theme-tsushima-kurosawa', name: 'حالت کوروساوا', primary: '#ffffff', bg: '#000000', text: '#a0a0a0', isDark: true },
  { id: 'theme-tsushima-night', name: 'شب پرستاره', primary: '#90e0ef', bg: '#070a2b', text: '#ffffff', isDark: true },
  { id: 'theme-ghost-armor', name: 'زره شبح', primary: '#e5e5e5', bg: '#1b1b1b', text: '#da2c38', isDark: true },
  { id: 'theme-tsushima-snow', name: 'برف کامی‌اگاتا', primary: '#0077b6', bg: '#e0f2fe', text: '#023047', isDark: false },
  { id: 'theme-tsushima-pampas', name: 'علفزار پامپاس', primary: '#e6ccb2', bg: '#585123', text: '#fefae0', isDark: true },
  // Death Stranding
  { id: 'theme-death-stranding-main', name: 'دث استرندینگ', primary: '#ff9a00', bg: '#232f2a', text: '#c2d1c8', isDark: true },
  { id: 'theme-death-stranding-bt', name: 'منطقه بی‌تی', primary: '#a8dadc', bg: '#1d3557', text: '#ffffff', isDark: true },
  { id: 'theme-death-stranding-chiral', name: 'کریستال کایرال', primary: '#ffd60a', bg: '#000814', text: '#e5e5e5', isDark: true },
  { id: 'theme-death-stranding-rain', name: 'باران زمان', primary: '#6c757d', bg: '#212529', text: '#ced4da', isDark: true },
  { id: 'theme-death-stranding-ludens', name: 'لودنز', primary: '#fca311', bg: '#14213d', text: '#e5e5e5', isDark: true },
  // Rockstar Games
  { id: 'theme-rdr2-heartlands', name: 'چمنزار هارت‌لندز', primary: '#b5838d', bg: '#fefae0', text: '#6d6875', isDark: false },
  { id: 'theme-rdr2-sunset', name: 'غروب نیو هانوفر', primary: '#e76f51', bg: '#3a2e39', text: '#f4a261', isDark: true },
  { id: 'theme-rdr2-grizzlies', name: 'کوهستان گریزلیز', primary: '#6096ba', bg: '#e7ecef', text: '#274c77', isDark: false },
  { id: 'theme-gta-v-vespucci', name: 'ساحل وسپوچی', primary: '#ffddd2', bg: '#00a8e8', text: '#003459', isDark: true },
  { id: 'theme-gta-v-night', name: 'شب در لوس سانتوس', primary: '#ff00f4', bg: '#240046', text: '#e5e5e5', isDark: true },
  { id: 'theme-gta-vice-city', name: 'وایس سیتی', primary: '#ff3f8f', bg: '#04d9ff', text: '#212121', isDark: false },
  // Minecraft
  { id: 'theme-minecraft-overworld', name: 'دنیای ماینکرفت', primary: '#5a9632', bg: '#79c0ff', text: '#3b2a1a', isDark: false },
  { id: 'theme-minecraft-nether', name: 'دنیای ندر', primary: '#ff5a00', bg: '#6b0000', text: '#ffc896', isDark: true },
  { id: 'theme-minecraft-diamond', name: 'الماس', primary: '#00f2ea', bg: '#404040', text: '#ffffff', isDark: true },
  { id: 'theme-minecraft-creeper', name: 'کریپر', primary: '#2f943f', bg: '#0e0e0e', text: '#c3c3c3', isDark: true },
  { id: 'theme-minecraft-end', name: 'دنیای اِند', primary: '#e400ff', bg: '#1a102b', text: '#f0f0f0', isDark: true },
  // Elden Ring
  { id: 'theme-elden-ring-erdtree', name: 'اِردتری', primary: '#ffc300', bg: '#1f2a37', text: '#fde4cf', isDark: true },
  { id: 'theme-elden-ring-caelid', name: 'کِی‌لید', primary: '#c9184a', bg: '#4a2530', text: '#ffb3c1', isDark: true },
  { id: 'theme-elden-ring-liurnia', name: 'لیورنیا', primary: '#90e0ef', bg: '#1c3e4e', text: '#caf0f8', isDark: true },
  { id: 'theme-elden-ring-malenia', name: 'مِلینیا', primary: '#e09f3e', bg: '#333d29', text: '#fff3b0', isDark: true },
  // The Last of Us
  { id: 'theme-last-of-us-overgrowth', name: 'طبیعت پساآخرالزمانی', primary: '#73a942', bg: '#3a3d2b', text: '#e8f0e2', isDark: true },
  { id: 'theme-last-of-us-spores', name: 'هاگ‌های عفونی', primary: '#ff9e00', bg: '#2c2c27', text: '#fff3b0', isDark: true },
  { id: 'theme-last-of-us-fedra', name: 'فدرا', primary: '#adb5bd', bg: '#212529', text: '#dee2e6', isDark: true },
  // Hades
  { id: 'theme-hades-tartarus', name: 'تارتاروس', primary: '#9d4edd', bg: '#14101b', text: '#e0cffc', isDark: true },
  { id: 'theme-hades-asphodel', name: 'آسفودل', primary: '#e63946', bg: '#4d191d', text: '#ffb3c1', isDark: true },
  { id: 'theme-hades-elysium', name: 'الیسیوم', primary: '#fca311', bg: '#eef8f1', text: '#003566', isDark: false },
  // Stardew Valley
  { id: 'theme-stardew-spring', name: 'بهار استاردو', primary: '#f15bb5', bg: '#d8f3dc', text: '#2d6a4f', isDark: false },
  { id: 'theme-stardew-fall', name: 'پاییز استاردو', primary: '#e76f51', bg: '#fefae0', text: '#606c38', isDark: false },
  { id: 'theme-stardew-community-center', name: 'مرکز اجتماعات', primary: '#ffd60a', bg: '#e6ccb2', text: '#582f0e', isDark: false },
  // More Games
  { id: 'theme-witcher-3-velen', name: 'ولن (ویچر)', primary: '#7f7f7f', bg: '#3d402d', text: '#c8c6a7', isDark: true },
  { id: 'theme-witcher-3-toussaint', name: 'توسان (ویچر)', primary: '#7209b7', bg: '#f2eafc', text: '#441669', isDark: false },
  { id: 'theme-skyrim-whiterun', name: 'وایتران (اسکایریم)', primary: '#dda15e', bg: '#e8e1d5', text: '#39322a', isDark: false },
  { id: 'theme-bioshock-rapture', name: 'رپچر (بایوشاک)', primary: '#cda434', bg: '#0a2239', text: '#e0e1dd', isDark: true },
  { id: 'theme-portal-2', name: 'پورتال ۲', primary: '#ff6b00', bg: '#e8e8e8', text: '#005f73', isDark: false },
  { id: 'theme-journey', name: 'جورنی', primary: '#d72323', bg: '#f4a261', text: '#212121', isDark: false },
  { id: 'theme-gris', name: 'گریس', primary: '#ef476f', bg: '#f7f7f7', text: '#073b4c', isDark: false },
  { id: 'theme-outer-wilds', name: 'آوتر وایلدز', primary: '#4361ee', bg: '#001219', text: '#90e0ef', isDark: true },
  { id: 'theme-control', name: 'کنترل', primary: '#e5342a', bg: '#1d1d1d', text: '#ffffff', isDark: true },
  { id: 'theme-red-dead-online', name: 'رد دد آنلاین', primary: '#b8860b', bg: '#2d2d2d', text: '#e5e5e5', isDark: true },

  // ===================================================================
  // ===== دسته ۳: انیمه و استودیو جیبلی (۹۱-۱۳۰) =====
  // ===================================================================
  { id: 'theme-spirited-away-main', name: 'شهر اشباح', primary: '#c92a2a', bg: '#e6fcf5', text: '#2b624f', isDark: false },
  { id: 'theme-spirited-away-bathhouse', name: 'حمامخانه ابورایا', primary: '#e03131', bg: '#5f3dc4', text: '#fcc419', isDark: true },
  { id: 'theme-spirited-away-noh-face', name: 'بی‌چهره (کائوناشی)', primary: '#e9ecef', bg: '#0b090a', text: '#a9a9a9', isDark: true },
  { id: 'theme-spirited-away-spirit-world', name: 'دنیای ارواح', primary: '#4cc9f0', bg: '#1d2d50', text: '#f0f0f0', isDark: true },
  { id: 'theme-miyazaki-forest', name: 'جنگل میازاکی', primary: '#40916c', bg: '#f2fcf7', text: '#1b4332', isDark: false },
  { id: 'theme-my-neighbor-totoro', name: 'همسایه‌ام توتورو', primary: '#52b788', bg: '#d8f3dc', text: '#2d6a4f', isDark: false },
  { id: 'theme-totoro-bus-stop', name: 'ایستگاه اتوبوس توتورو', primary: '#fca311', bg: '#293a46', text: '#e9ecef', isDark: true },
  { id: 'theme-princess-mononoke', name: 'شاهزاده مونونوکه', primary: '#c9184a', bg: '#2d3a3a', text: '#d8e2dc', isDark: true },
  { id: 'theme-mononoke-forest-spirit', name: 'روح جنگل', primary: '#00b4d8', bg: '#002538', text: '#e9f6ff', isDark: true },
  { id: 'theme-howls-moving-castle', name: 'قلعه متحرک هاول', primary: '#fca311', bg: '#f1faee', text: '#14213d', isDark: false },
  { id: 'theme-howl-calcifer', name: 'کالسیفر', primary: '#e76f51', bg: '#212529', text: '#ffd60a', isDark: true },
  { id: 'theme-ponyo-sea', name: 'پونیو روی صخره', primary: '#4895ef', bg: '#fde4cf', text: '#f15bb5', isDark: false },
  { id: 'theme-laputa-sky', name: 'لاپوتا: قلعه‌ای در آسمان', primary: '#00b4d8', bg: '#caf0f8', text: '#03045e', isDark: false },
  { id: 'theme-kikis-delivery', name: 'سرویس تحویل کی‌کی', primary: '#c9184a', bg: '#191834', text: '#ffffff', isDark: true },
  { id: 'theme-kiki-bakery', name: 'نانوایی کی‌کی', primary: '#dda15e', bg: '#fefae0', text: '#606c38', isDark: false },
  { id: 'theme-akira-red', name: 'قرمز آکیرا', primary: '#d72323', bg: '#171717', text: '#f5f5f5', isDark: true },
  { id: 'theme-ghost-in-the-shell', name: 'شبح در پوسته', primary: '#02c39a', bg: '#023e8a', text: '#edf6f9', isDark: true },
  { id: 'theme-evangelion-unit01', name: 'اوا واحد ۰۱', primary: '#7209b7', bg: '#10221a', text: '#55a630', isDark: true },
  { id: 'theme-evangelion-asuka', name: 'آسکا (اوانگلیون)', primary: '#e63946', bg: '#f1faee', text: '#1d3557', isDark: false },
  { id: 'theme-sailor-moon', name: 'سیلور مون', primary: '#f72585', bg: '#fcf3f6', text: '#7209b7', isDark: false },
  { id: 'theme-attack-on-titan', name: 'حمله به تایتان', primary: '#a4161a', bg: '#e2dccd', text: '#3c322f', isDark: false },
  { id: 'theme-cowboy-bebop', name: 'کابوی بیباپ', primary: '#e5c100', bg: '#003566', text: '#f0f0f0', isDark: true },
  { id: 'theme-jujutsu-kaisen', name: 'جوجوتسو کایسن', primary: '#e63946', bg: '#0d1b2a', text: '#e0e1dd', isDark: true },
  { id: 'theme-demon-slayer-tanjiro', name: 'تانجیرو (شیطان‌کش)', primary: '#2d6a4f', bg: '#1b1b1b', text: '#f1faee', isDark: true },
  { id: 'theme-demon-slayer-nezuko', name: 'نزوکو (شیطان‌کش)', primary: '#ffb3c1', bg: '#212529', text: '#f8f9fa', isDark: true },
  { id: 'theme-one-punch-man', name: 'مرد تک‌مشتی', primary: '#ffd60a', bg: '#e63946', text: '#ffffff', isDark: true },
  { id: 'theme-my-hero-academia', name: 'مدرسه قهرمانانه من', primary: '#0077b6', bg: '#f1faee', text: '#e63946', isDark: false },
  { id: 'theme-naruto-konoha', name: 'کونوها (ناروتو)', primary: '#ff9e00', bg: '#40916c', text: '#081c15', isDark: true },
  { id: 'theme-naruto-akatsuki', name: 'آکاتسوکی (ناروتو)', primary: '#d90429', bg: '#141414', text: '#e5e5e5', isDark: true },
  { id: 'theme-death-note', name: 'دفترچه مرگ', primary: '#a4161a', bg: '#0b090a', text: '#adb5bd', isDark: true },
  { id: 'theme-tokyo-ghoul', name: 'توکیو غول', primary: '#c9184a', bg: '#1b1b1b', text: '#dee2e6', isDark: true },
  { id: 'theme-studio-trigger', name: 'استودیو تریگر', primary: '#f94144', bg: '#f3722c', text: '#ffffff', isDark: true },
  { id: 'theme-makoto-shinkai', name: 'ماکوتو شینکای', primary: '#4895ef', bg: '#d0eaff', text: '#012a4a', isDark: false },
  { id: 'theme-your-name', name: 'نام تو', primary: '#f77f00', bg: '#0096c7', text: '#fcfcfc', isDark: true },
  { id: 'theme-weathering-with-you', name: 'فرزند آب و هوا', primary: '#90e0ef', bg: '#6c757d', text: '#f8f9fa', isDark: true },
  { id: 'theme-satoshi-kon', name: 'ساتوشی کن', primary: '#e1166b', bg: '#fdf0d5', text: '#003049', isDark: false },
  { id: 'theme-perfect-blue', name: 'آبی تمام‌عیار', primary: '#ef476f', bg: '#0077b6', text: '#ffd166', isDark: true },
  { id: 'theme-paprika', name: 'پاپریکا', primary: '#d90429', bg: '#ffc300', text: '#000814', isDark: true },
  { id: 'theme-cat-returns', name: 'بازگشت گربه', primary: '#e29578', bg: '#fefae0', text: '#6d6875', isDark: false },
  { id: 'theme-porco-rosso', name: 'پورکو روسو', primary: '#d72323', bg: '#a2d2ff', text: '#023e8a', isDark: false },

  // ===================================================================
  // ===== دسته ۴: طبیعت و محیط اطراف (۱۳۱-۱۹۰) =====
  // ===================================================================
  { id: 'theme-deep-forest', name: 'جنگل عمیق', primary: '#2d6a4f', bg: '#e9f5ee', text: '#081c15', isDark: false },
  { id: 'theme-autumn-leaves', name: 'برگ‌های پاییزی', primary: '#e76f51', bg: '#4d2c1d', text: '#f4a261', isDark: true },
  { id: 'theme-sahara-desert', name: 'صحرای آفریقا', primary: '#f4a261', bg: '#faedcd', text: '#a05e2c', isDark: false },
  { id: 'theme-arctic-ice', name: 'یخ‌های قطبی', primary: '#00a6fb', bg: '#ffffff', text: '#003459', isDark: false },
  { id: 'theme-tropical-beach', name: 'ساحل استوایی', primary: '#00f5d4', bg: '#00bbf9', text: '#001a40', isDark: true },
  { id: 'theme-coral-reef', name: 'صخره مرجانی', primary: '#ff595e', bg: '#e2fdff', text: '#457b9d', isDark: false },
  { id: 'theme-volcanic-ash', name: 'خاکستر آتشفشانی', primary: '#ff6700', bg: '#333333', text: '#f0f0f0', isDark: true },
  { id: 'theme-mountain-peak', name: 'قله کوه', primary: '#6c757d', bg: '#f8f9fa', text: '#212529', isDark: false },
  { id: 'theme-lavender-field', name: 'دشت اسطوخودوس', primary: '#7b2cbf', bg: '#f2eafc', text: '#441669', isDark: false },
  { id: 'theme-cherry-blossom', name: 'شکوفه گیلاس', primary: '#ffb3c1', bg: '#ffffff', text: '#e75480', isDark: false },
  { id: 'theme-river-stone', name: 'سنگ رودخانه', primary: '#adb5bd', bg: '#e9ecef', text: '#343a40', isDark: false },
  { id: 'theme-bamboo-forest', name: 'جنگل بامبو', primary: '#80b918', bg: '#f1f8e9', text: '#335005', isDark: false },
  { id: 'theme-sunset-glow', name: 'درخشش غروب', primary: '#ff9e00', bg: '#4d194d', text: '#ffc8dd', isDark: true },
  { id: 'theme-misty-morning', name: 'صبح مه‌آلود', primary: '#a2d2ff', bg: '#f0f8ff', text: '#3a5a78', isDark: false },
  { id: 'theme-deep-ocean', name: 'اعماق اقیانوس', primary: '#0096c7', bg: '#001219', text: '#90e0ef', isDark: true },
  { id: 'theme-sunflower-field', name: 'مزرعه آفتابگردان', primary: '#ffbe0b', bg: '#fcf8e8', text: '#3a2e00', isDark: false },
  { id: 'theme-redwood-forest', name: 'جنگل ردوود', primary: '#800f2f', bg: '#f4eade', text: '#390715', isDark: false },
  { id: 'theme-desert-night', name: 'شب کویر', primary: '#f6bd60', bg: '#02021a', text: '#f2f2f2', isDark: true },
  { id: 'theme-jungle-canopy', name: 'سایبان جنگل', primary: '#55a630', bg: '#004b23', text: '#f0f0f0', isDark: true },
  { id: 'theme-canyon-walls', name: 'دیواره‌های دره', primary: '#e29578', bg: '#f9f3f0', text: '#7f5539', isDark: false },
  { id: 'theme-flower-garden', name: 'باغ گل', primary: '#f15bb5', bg: '#ffffff', text: '#9b5de5', isDark: false },
  { id: 'theme-mossy-rock', name: 'سنگ خزه‌ای', primary: '#73a942', bg: '#4f5d50', text: '#e8f0e2', isDark: true },
  { id: 'theme-wheat-field', name: 'گندم‌زار', primary: '#dda15e', bg: '#fefae0', text: '#606c38', isDark: false },
  { id: 'theme-iris-garden', name: 'باغ زنبق', primary: '#6a0dad', bg: '#f4f0f8', text: '#3d0764', isDark: false },
  { id: 'theme-poppy-field', name: 'دشت شقایق', primary: '#d90429', bg: '#edf2f4', text: '#2b2d42', isDark: false },
  { id: 'theme-thunderstorm', name: 'آسمان طوفانی', primary: '#fca311', bg: '#1d3557', text: '#f1faee', isDark: true },
  { id: 'theme-geode-crystal', name: 'بلور ژئود', primary: '#9d4edd', bg: '#3c3c3c', text: '#f4f0f8', isDark: true },
  { id: 'theme-parrot-feathers', name: 'پرهای طوطی', primary: '#2a9d8f', bg: '#e9c46a', text: '#264653', isDark: false },
  { id: 'theme-butterfly-wing', name: 'بال پروانه', primary: '#4361ee', bg: '#f7f7f7', text: '#f72585', isDark: false },
  { id: 'theme-peacock', name: 'طاووس', primary: '#0077b6', bg: '#03001C', text: '#55a630', isDark: true },
  { id: 'theme-savanna', name: 'ساوانا', primary: '#e76f51', bg: '#fdf4f0', text: '#2a9d8f', isDark: false },
  { id: 'theme-taiga', name: 'تایگا', primary: '#274c77', bg: '#e7ecef', text: '#6096ba', isDark: false },
  { id: 'theme-mangrove', name: 'مانگرو', primary: '#40916c', bg: '#1b4332', text: '#d8f3dc', isDark: true },
  { id: 'theme-swamp', name: 'مرداب', primary: '#606c38', bg: '#283618', text: '#fefae0', isDark: true },
  { id: 'theme-golden-hour', name: 'ساعت طلایی', primary: '#ff9e00', bg: '#fff0d8', text: '#783d00', isDark: false },
  { id: 'theme-blue-hour', name: 'ساعت آبی', primary: '#a2d2ff', bg: '#03045e', text: '#e9f6ff', isDark: true },
  { id: 'theme-high-noon', name: 'اوج ظهر', primary: '#ffbe0b', bg: '#ffffff', text: '#005f73', isDark: false },
  { id: 'theme-sandstone', name: 'سنگ ماسه‌ای', primary: '#e09f3e', bg: '#fff3b0', text: '#333d29', isDark: false },
  { id: 'theme-rose-garden', name: 'باغ رز', primary: '#c9184a', bg: '#fff0f3', text: '#800f2f', isDark: false },
  { id: 'theme-tulip-festival', name: 'جشنواره لاله', primary: '#e63946', bg: '#f1faee', text: '#1d3557', isDark: false },
  { id: 'theme-orchid', name: 'ارکیده', primary: '#9b5de5', bg: '#f7f7f7', text: '#5e368c', isDark: false },
  { id: 'theme-lily-pad', name: 'برگ نیلوفر آبی', primary: '#80b918', bg: '#e0f2fe', text: '#2d6a4f', isDark: false },
  { id: 'theme-firefly-night', name: 'شب کرم‌های شب‌تاب', primary: '#f9f871', bg: '#023047', text: '#f1f1f1', isDark: true },
  { id: 'theme-grand-canyon', name: 'گرند کنیون', primary: '#d5bdaf', bg: '#4f3f35', text: '#fff6ea', isDark: true },
  { id: 'theme-niagara-falls', name: 'آبشار نیاگارا', primary: '#00b4d8', bg: '#e7f9fc', text: '#003459', isDark: false },
  { id: 'theme-iceland-lagoon', name: 'مرداب ایسلند', primary: '#a2d2ff', bg: '#1d3557', text: '#f1faee', isDark: true },
  { id: 'theme-amazon-rainforest', name: 'جنگل آمازون', primary: '#55a630', bg: '#1b4332', text: '#d8f3dc', isDark: true },
  { id: 'theme-serengeti-migration', name: 'مهاجرت در سرنگتی', primary: '#bc6c25', bg: '#faedcd', text: '#283618', isDark: false },
  { id: 'theme-fox', name: 'روباه', primary: '#e76f51', bg: '#f8f9fa', text: '#343a40', isDark: false },
  { id: 'theme-wolf', name: 'گرگ', primary: '#adb5bd', bg: '#212529', text: '#f8f9fa', isDark: true },
  { id: 'theme-tiger', name: 'ببر', primary: '#fca311', bg: '#0b090a', text: '#ffffff', isDark: true },
  { id: 'theme-snow-leopard', name: 'پلنگ برفی', primary: '#dee2e6', bg: '#f8f9fa', text: '#495057', isDark: false },
  { id: 'theme-red-panda', name: 'پاندای قرمز', primary: '#c44536', bg: '#4a2e1d', text: '#fefae0', isDark: true },
  { id: 'theme-jellyfish', name: 'عروس دریایی', primary: '#f72585', bg: '#001845', text: '#90e0ef', isDark: true },
  { id: 'theme-clownfish', name: 'دلقک‌ماهی', primary: '#ff6700', bg: '#e2fdff', text: '#003459', isDark: false },
  { id: 'theme-toucan', name: 'توکان', primary: '#f9f871', bg: '#101010', text: '#f94144', isDark: true },
  { id: 'theme-hummingbird', name: 'مرغ مگس‌خوار', primary: '#9b5de5', bg: '#f0fcfb', text: '#011627', isDark: false },
  { id: 'theme-chameleon', name: 'آفتاب‌پرست', primary: '#80b918', bg: '#333d29', text: '#e9c46a', isDark: true },
  
  // ===================================================================
  // ===== دسته ۵: فضا و پدیده‌های آسمانی (۱۹۱-۲۳۰) =====
  // ===================================================================
  { id: 'theme-nebula', name: 'سحابی', primary: '#f72585', bg: '#1a0d3a', text: '#4cc9f0', isDark: true },
  { id: 'theme-galaxy', name: 'کهکشان', primary: '#9d4edd', bg: '#03071e', text: '#e85d04', isDark: true },
  { id: 'theme-aurora-borealis', name: 'شفق قطبی', primary: '#5aff15', bg: '#031d33', text: '#f0f0f0', isDark: true },
  { id: 'theme-starry-night', name: 'شب پر ستاره', primary: '#fefae0', bg: '#001845', text: '#979dac', isDark: true },
  { id: 'theme-solar-flare', name: 'شراره خورشیدی', primary: '#ff6700', bg: '#000000', text: '#ffca3a', isDark: true },
  { id: 'theme-planet-mars', name: 'سیاره مریخ', primary: '#c44536', bg: '#fff0e6', text: '#772e25', isDark: false },
  { id: 'theme-planet-jupiter', name: 'سیاره مشتری', primary: '#e29578', bg: '#543b35', text: '#f7eedc', isDark: true },
  { id: 'theme-planet-neptune', name: 'سیاره نپتون', primary: '#4ea8de', bg: '#00254d', text: '#e8f7ff', isDark: true },
  { id: 'theme-lunar-surface', name: 'سطح ماه', primary: '#adb5bd', bg: '#212529', text: '#f8f9fa', isDark: true },
  { id: 'theme-black-hole', name: 'سیاه‌چاله', primary: '#ff9100', bg: '#000000', text: '#ffffff', isDark: true },
  { id: 'theme-milky-way', name: 'راه شیری', primary: '#f6b95c', bg: '#18122B', text: '#e3d8f1', isDark: true },
  { id: 'theme-supernova', name: 'ابرنواختر', primary: '#fef02d', bg: '#540d6e', text: '#ffffff', isDark: true },
  { id: 'theme-earth-from-space', name: 'زمین از فضا', primary: '#4361ee', bg: '#020d1e', text: '#ffffff', isDark: true },
  { id: 'theme-comet-tail', name: 'دنباله ستاره دنباله‌دار', primary: '#a2d2ff', bg: '#0c1445', text: '#e0e0e0', isDark: true },
  { id: 'theme-saturn-rings', name: 'حلقه‌های زحل', primary: '#e6ccb2', bg: '#42372f', text: '#ffffff', isDark: true },
  { id: 'theme-pillars-of-creation', name: 'ستون‌های آفرینش', primary: '#e76f51', bg: '#14213d', text: '#e9c46a', isDark: true },
  { id: 'theme-crab-nebula', name: 'سحابی خرچنگ', primary: '#ef476f', bg: '#073b4c', text: '#ffd166', isDark: true },
  { id: 'theme-orion-nebula', name: 'سحابی شکارچی', primary: '#e63946', bg: '#1d3557', text: '#f1faee', isDark: true },
  { id: 'theme-rosette-nebula', name: 'سحابی رزت', primary: '#c9184a', bg: '#03071e', text: '#ffb3c1', isDark: true },
  { id: 'theme-horsehead-nebula', name: 'سحابی سر اسب', primary: '#ffddd2', bg: '#800f2f', text: '#fcfcfc', isDark: true },
  { id: 'theme-andromeda-galaxy', name: 'کهکشان آندرومدا', primary: '#caf0f8', bg: '#023e8a', text: '#ffffff', isDark: true },
  { id: 'theme-triangulum-galaxy', name: 'کهکشان مثلث', primary: '#ffc8dd', bg: '#7209b7', text: '#f0f0f0', isDark: true },
  { id: 'theme-cosmic-latte', name: 'لاته کیهانی', primary: '#6d6875', bg: '#fffce8', text: '#3c322f', isDark: false },
  { id: 'theme-solar-eclipse', name: 'خورشیدگرفتگی', primary: '#fca311', bg: '#0b090a', text: '#e9ecef', isDark: true },
  { id: 'theme-lunar-eclipse', name: 'ماه‌گرفتگی', primary: '#e63946', bg: '#1d1d1d', text: '#ffb3c1', isDark: true },
  { id: 'theme-meteor-shower', name: 'بارش شهابی', primary: '#ffbe0b', bg: '#001219', text: '#f0f0f0', isDark: true },
  { id: 'theme-gas-giant', name: 'غول گازی', primary: '#f4a261', bg: '#264653', text: '#faedcd', isDark: true },
  { id: 'theme-ice-giant', name: 'غول یخی', primary: '#90e0ef', bg: '#1c3e4e', text: '#e9f6ff', isDark: true },
  { id: 'theme-red-dwarf-star', name: 'ستاره کوتوله قرمز', primary: '#d90429', bg: '#3a0ca3', text: '#ffb3c1', isDark: true },
  { id: 'theme-white-dwarf-star', name: 'ستاره کوتوله سفید', primary: '#a2d2ff', bg: '#000814', text: '#e9ecef', isDark: true },
  { id: 'theme-neutron-star', name: 'ستاره نوترونی', primary: '#9d4edd', bg: '#000000', text: '#f4f0f8', isDark: true },
  { id: 'theme-interstellar-cloud', name: 'ابر میان‌ستاره‌ای', primary: '#ffc8dd', bg: '#580b1d', text: '#fcfcfc', isDark: true },
  { id: 'theme-exoplanet', name: 'سیاره فراخورشیدی', primary: '#02c39a', bg: '#023e8a', text: '#edf6f9', isDark: true },
  { id: 'theme-quasar', name: 'کوازار', primary: '#4361ee', bg: '#0b090a', text: '#ffffff', isDark: true },
  { id: 'theme-deep-space', name: 'اعماق فضا', primary: '#f8f9fa', bg: '#000000', text: '#6c757d', isDark: true },
  { id: 'theme-event-horizon', name: 'افق رویداد', primary: '#ffd60a', bg: '#101010', text: '#f0f0f0', isDark: true },
  { id: 'theme-cosmic-microwave-background', name: 'تابش زمینه کیهانی', primary: '#f77f00', bg: '#003049', text: '#fdf0d5', isDark: true },
  { id: 'theme-planet-earth', name: 'سیاره زمین', primary: '#2a9d8f', bg: '#f1faee', text: '#1d3557', isDark: false },
  { id: 'theme-aurora-australis', name: 'شفق جنوبی', primary: '#ef476f', bg: '#073b4c', text: '#f0f0f0', isDark: true },
  { id: 'theme-zodiacal-light', name: 'نور منطقةالبروجی', primary: '#e6ccb2', bg: '#02021a', text: '#f5f5f5', isDark: true },

  // ===================================================================
  // ===== دسته ۶: هنر، طراحی و معماری (۲۳۱-۲۷۰) =====
  // ===================================================================
  { id: 'theme-van-gogh-starry-night', name: 'شب پرستاره ونگوگ', primary: '#fca311', bg: '#003566', text: '#e9f6ff', isDark: true },
  { id: 'theme-van-gogh-sunflowers', name: 'آفتابگردان‌های ونگوگ', primary: '#ffbe0b', bg: '#fcf8e8', text: '#3a2e00', isDark: false },
  { id: 'theme-monet-water-lilies', name: 'نیلوفرهای آبی مونه', primary: '#a2d2ff', bg: '#f2eafc', text: '#6a0dad', isDark: false },
  { id: 'theme-klimt-the-kiss', name: 'بوسه کلیمت', primary: '#ffd60a', bg: '#3a2e00', text: '#fffce8', isDark: true },
  { id: 'theme-mondrian-composition', name: 'ترکیب‌بندی موندریان', primary: '#d90429', bg: '#ffffff', text: '#001d3d', isDark: false },
  { id: 'theme-dali-surrealism', name: 'سورئالیسم دالی', primary: '#0077b6', bg: '#fde4cf', text: '#023047', isDark: false },
  { id: 'theme-bauhaus', name: 'باهاوس', primary: '#ffd60a', bg: '#f8f9fa', text: '#003566', isDark: false },
  { id: 'theme-impressionism', name: 'امپرسیونیسم', primary: '#a2d2ff', bg: '#fffce8', text: '#577590', isDark: false },
  { id: 'theme-baroque', name: 'باروک', primary: '#ffd60a', bg: '#580b1d', text: '#fae3c6', isDark: true },
  { id: 'theme-pop-art', name: 'پاپ آرت', primary: '#ff0054', bg: '#f9f871', text: '#000000', isDark: false },
  { id: 'theme-art-deco', name: 'آرت دکو', primary: '#cda434', bg: '#0d1b2a', text: '#e0e1dd', isDark: true },
  { id: 'theme-minimalist', name: 'مینیمالیست', primary: '#343a40', bg: '#f8f9fa', text: '#6c757d', isDark: false },
  { id: 'theme-brutalism', name: 'بروتالیسم', primary: '#495057', bg: '#dee2e6', text: '#212529', isDark: false },
  { id: 'theme-vintage-poster', name: 'پوستر وینتیج', primary: '#d5bdaf', bg: '#4f3f35', text: '#fff6ea', isDark: true },
  { id: 'theme-steampunk', name: 'استیم‌پانک', primary: '#c08552', bg: '#582f0e', text: '#f9f1e7', isDark: true },
  { id: 'theme-gothic-architecture', name: 'معماری گوتیک', primary: '#8d0801', bg: '#2b2b2b', text: '#d7d7d7', isDark: true },
  { id: 'theme-victorian-era', name: 'دوران ویکتوریا', primary: '#585481', bg: '#eef0f2', text: '#373261', isDark: false },
  { id: 'theme-abstract-art', name: 'هنر انتزاعی', primary: '#e63946', bg: '#f1faee', text: '#1d3557', isDark: false },
  { id: 'theme-renaissance', name: 'رنسانس', primary: '#a4161a', bg: '#f2e8dc', text: '#4d3020', isDark: false },
  { id: 'theme-fauvism', name: 'فوویسم', primary: '#e1166b', bg: '#ffd243', text: '#006e90', isDark: false },
  { id: 'theme-art-nouveau', name: 'آرت نوو', primary: '#436436', bg: '#f2ebd8', text: '#774936', isDark: false },
  { id: 'theme-cubism', name: 'کوبیسم', primary: '#8f7b66', bg: '#e8e1d5', text: '#39322a', isDark: false },
  { id: 'theme-rococo', name: 'روکوکو', primary: '#ffb3c1', bg: '#f8f4f9', text: '#6d6875', isDark: false },
  { id: 'theme-modern-interior', name: 'طراحی داخلی مدرن', primary: '#0096c7', bg: '#ffffff', text: '#495057', isDark: false },
  { id: 'theme-scandinavian', name: 'اسکاندیناوی', primary: '#3d405b', bg: '#f4f1de', text: '#81b29a', isDark: false },
  { id: 'theme-vermeer-girl-pearl', name: 'دختری با گوشواره مروارید', primary: '#f6bd60', bg: '#02021a', text: '#e9ecef', isDark: true },
  { id: 'theme-edward-hopper-nighthawks', name: 'شب‌زنده‌داران هاپر', primary: '#f9c74f', bg: '#004b23', text: '#f0f0f0', isDark: true },
  { id: 'theme-hieronymus-bosch', name: 'باغ لذت‌های دنیوی', primary: '#e29578', bg: '#fde4cf', text: '#2a9d8f', isDark: false },
  { id: 'theme-fridakahlo', name: 'فریدا کالو', primary: '#c9184a', bg: '#ffd166', text: '#1d3557', isDark: false },
  { id: 'theme-banksy', name: 'بنکسی', primary: '#d90429', bg: '#e9ecef', text: '#141414', isDark: false },
  { id: 'theme-islamic-architecture', name: 'معماری اسلامی', primary: '#00a896', bg: '#f0fcfb', text: '#023e8a', isDark: false },
  { id: 'theme-japanese-woodblock', name: 'چاپ چوبی ژاپنی', primary: '#d72323', bg: '#f2e8dc', text: '#03045e', isDark: false },
  { id: 'theme-sepia-photo', name: 'عکس سپیا', primary: '#8f7b66', bg: '#fbf8f2', text: '#39322a', isDark: false },
  { id: 'theme-film-noir', name: 'فیلم نوآر', primary: '#ffbe0b', bg: '#101010', text: '#dee2e6', isDark: true },
  { id: 'theme-technicolor', name: 'تکنی‌کالر', primary: '#e63946', bg: '#a8dadc', text: '#1d3557', isDark: false },
  { id: 'theme-wes-anderson', name: 'وس اندرسون', primary: '#e76f51', bg: '#f4a261', text: '#264653', isDark: false },
  { id: 'theme-tim-burton', name: 'تیم برتون', primary: '#9d4edd', bg: '#212529', text: '#e9ecef', isDark: true },
  { id: 'theme-studio-ghibli-food', name: 'غذای جیبلی', primary: '#e29578', bg: '#fefae0', text: '#bc6c25', isDark: false },
  { id: 'theme-zaha-hadid', name: 'زاها حدید', primary: '#6c757d', bg: '#ffffff', text: '#212529', isDark: false },
  { id: 'theme-antoni-gaudi', name: 'آنتونی گائودی', primary: '#e9c46a', bg: '#0096c7', text: '#023047', isDark: true },

  // ===================================================================
  // ===== دسته ۷: سنگ‌های زینتی و مواد (۲۷۱-۳۰۰) =====
  // ===================================================================
  { id: 'theme-gem-sapphire', name: 'یاقوت کبود', primary: '#0f4c75', bg: '#e2f0fc', text: '#1b262c', isDark: false },
  { id: 'theme-gem-ruby', name: 'یاقوت سرخ', primary: '#9e2a2b', bg: '#f9f5f5', text: '#330404', isDark: false },
  { id: 'theme-gem-emerald', name: 'زمرد', primary: '#008037', bg: '#e8f6ef', text: '#002b13', isDark: false },
  { id: 'theme-gem-amethyst', name: 'آمیتیست', primary: '#9966cc', bg: '#f6f2fa', text: '#3c2850', isDark: false },
  { id: 'theme-gem-topaz', name: 'توپاز', primary: '#00a6fb', bg: '#ffffff', text: '#005a8b', isDark: false },
  { id: 'theme-gem-citrine', name: 'سیترین', primary: '#e4d00a', bg: '#fdfce6', text: '#544d04', isDark: false },
  { id: 'theme-gem-opal', name: 'اوپال', primary: '#a2d2ff', bg: '#f7f7f7', text: '#ffc8dd', isDark: false },
  { id: 'theme-gem-onyx', name: 'اونیکس (عقیق سیاه)', primary: '#e5e5e5', bg: '#141414', text: '#b3b3b3', isDark: true },
  { id: 'theme-gold', name: 'طلا', primary: '#ffd700', bg: '#1a1100', text: '#fff8e1', isDark: true },
  { id: 'theme-silver', name: 'نقره', primary: '#757575', bg: '#e8e8e8', text: '#424242', isDark: false },
  { id: 'theme-copper', name: 'مس', primary: '#b87333', bg: '#402a1d', text: '#f9e9de', isDark: true },
  { id: 'theme-bronze', name: 'برنز', primary: '#cd7f32', bg: '#5c3817', text: '#f5e8da', isDark: true },
  { id: 'theme-marble', name: 'سنگ مرمر', primary: '#6c757d', bg: '#f8f9fa', text: '#343a40', isDark: false },
  { id: 'theme-wood', name: 'چوب', primary: '#9e6240', bg: '#fef7f1', text: '#4a2e1d', isDark: false },
  { id: 'theme-concrete', name: 'بتن', primary: '#838383', bg: '#e0e0e0', text: '#2e2e2e', isDark: false },
  { id: 'theme-gem-garnet', name: 'گارنت', primary: '#a4161a', bg: '#f9f5f5', text: '#3c0606', isDark: false },
  { id: 'theme-gem-aquamarine', name: 'آکوامارین', primary: '#90e0ef', bg: '#e9f6ff', text: '#012a4a', isDark: false },
  { id: 'theme-gem-peridot', name: 'پریدوت', primary: '#80b918', bg: '#f1f8e9', text: '#335005', isDark: false },
  { id: 'theme-gem-tourmaline', name: 'تورمالین', primary: '#f72585', bg: '#fefae0', text: '#9b5de5', isDark: false },
  { id: 'theme-gem-lapis-lazuli', name: 'لاجورد', primary: '#4361ee', bg: '#eef0f2', text: '#03045e', isDark: false },
  { id: 'theme-gem-turquoise', name: 'فیروزه', primary: '#40e0d0', bg: '#f0fcfb', text: '#011627', isDark: false },
  { id: 'theme-gem-moonstone', name: 'سنگ ماه', primary: '#a2d2ff', bg: '#e9ecef', text: '#1d3557', isDark: false },
  { id: 'theme-gem-sunstone', name: 'سنگ خورشید', primary: '#f4a261', bg: '#fefae0', text: '#bc6c25', isDark: false },
  { id: 'theme-gem-bloodstone', name: 'سنگ خون', primary: '#d90429', bg: '#1b4332', text: '#d8f3dc', isDark: true },
  { id: 'theme-gem-jade', name: 'یشم', primary: '#55a630', bg: '#e8f6ef', text: '#1b4332', isDark: false },
  { id: 'theme-rose-gold', name: 'رز گلد', primary: '#e6ccb2', bg: '#6c3b2a', text: '#fdf4f0', isDark: true },
  { id: 'theme-steel', name: 'فولاد', primary: '#adb5bd', bg: '#212529', text: '#f8f9fa', isDark: true },
  { id: 'theme-terracotta', name: 'سفال', primary: '#e29578', bg: '#f9f3f0', text: '#7f5539', isDark: false },
  { id: 'theme-glass', name: 'شیشه', primary: '#caf0f8', bg: '#ffffff', text: '#0077b6', isDark: false },
  { id: 'theme-leather', name: 'چرم', primary: '#8f7b66', bg: '#39322a', text: '#e8e1d5', isDark: true },
  
  // ===================================================================
  // ===== دسته ۸: فرهنگ و محیط‌های انسانی (۳۰۱-۳۴۰) =====
  // ===================================================================
  { id: 'theme-spice-market', name: 'بازار ادویه', primary: '#c97c5d', bg: '#fdf4f0', text: '#6c3b2a', isDark: false },
  { id: 'theme-moroccan-bazaar', name: 'بازار مراکشی', primary: '#f15bb5', bg: '#00f5d4', text: '#212121', isDark: false },
  { id: 'theme-street-graffiti', name: 'هنر خیابانی (گرافیتی)', primary: '#f94144', bg: '#4d4d4d', text: '#f8f9fa', isDark: true },
  { id: 'theme-amusement-park', name: 'شهربازی', primary: '#f9c74f', bg: '#ffffff', text: '#f94144', isDark: false },
  { id: 'theme-library', name: 'کتابخانه', primary: '#a05e2c', bg: '#f5efe6', text: '#4e2a0f', isDark: false },
  { id: 'theme-coffee-shop', name: 'کافی شاپ', primary: '#6f4e37', bg: '#e8e0d9', text: '#2b1d12', isDark: false },
  { id: 'theme-bakery', name: 'نانوایی', primary: '#dda15e', bg: '#fefae0', text: '#bc6c25', isDark: false },
  { id: 'theme-candy-store', name: 'شیرینی فروشی', primary: '#ffc4d6', bg: '#ffffff', text: '#f72585', isDark: false },
  { id: 'theme-theater-stage', name: 'صحنه تئاتر', primary: '#e5c100', bg: '#67080f', text: '#f2f2f2', isDark: true },
  { id: 'theme-farmhouse', name: 'خانه روستایی', primary: '#606c38', bg: '#fefae0', text: '#283618', isDark: false },
  { id: 'theme-industrial-loft', name: 'انبار صنعتی', primary: '#fca311', bg: '#343a40', text: '#e9ecef', isDark: true },
  { id: 'theme-beach-hut', name: 'کلبه ساحلی', primary: '#56cfe1', bg: '#fef9ef', text: '#489fb5', isDark: false },
  { id: 'theme-subway-station', name: 'ایستگاه مترو', primary: '#ffc600', bg: '#4a4a4a', text: '#ffffff', isDark: true },
  { id: 'theme-summer-festival', name: 'فستیوال تابستانی', primary: '#ef476f', bg: '#ffd166', text: '#073b4c', isDark: false },
  { id: 'theme-old-map', name: 'نقشه قدیمی', primary: '#8f7b66', bg: '#fbf8f2', text: '#544639', isDark: false },
  { id: 'theme-venetian-carnival', name: 'کارناوال ونیز', primary: '#cda434', bg: '#580b1d', text: '#f2e8dc', isDark: true },
  { id: 'theme-indian-holi-festival', name: 'جشن هولی هند', primary: '#f72585', bg: '#f1faee', text: '#7209b7', isDark: false },
  { id: 'theme-mexican-fiesta', name: 'فیستا مکزیکی', primary: '#f94144', bg: '#f9c74f', text: '#43aa8b', isDark: false },
  { id: 'theme-ski-resort', name: 'پیست اسکی', primary: '#0077b6', bg: '#f8f9fa', text: '#ef476f', isDark: false },
  { id: 'theme-jazz-club', name: 'کلوپ جاز', primary: '#e5c100', bg: '#1d1d1d', text: '#e9ecef', isDark: true },
  { id: 'theme-science-lab', name: 'آزمایشگاه علمی', primary: '#2ec4b6', bg: '#e9ecef', text: '#011627', isDark: false },
  { id: 'theme-artist-studio', name: 'آتلیه هنرمند', primary: '#e76f51', bg: '#f8f9fa', text: '#2a9d8f', isDark: false },
  { id: 'theme-greenhouse', name: 'گلخانه', primary: '#55a630', bg: '#f1f8e9', text: '#2d6a4f', isDark: false },
  { id: 'theme-observatory', name: 'رصدخانه', primary: '#caf0f8', bg: '#03045e', text: '#f0f0f0', isDark: true },
  { id: 'theme-museum', name: 'موزه', primary: '#6c757d', bg: '#ffffff', text: '#212529', isDark: false },
  { id: 'theme-circus', name: 'سیرک', primary: '#d90429', bg: '#fefae0', text: '#003566', isDark: false },
  { id: 'theme-winery', name: 'کارخانه شراب‌سازی', primary: '#800f2f', bg: '#f4eade', text: '#390715', isDark: false },
  { id: 'theme-bookstore', name: 'کتابفروشی', primary: '#bc6c25', bg: '#f5efe6', text: '#283618', isDark: false },
  { id: 'theme-record-store', name: 'فروشگاه صفحه گرامافون', primary: '#f94144', bg: '#43aa8b', text: '#212121', isDark: true },
  { id: 'theme-aquarium', name: 'آکواریوم', primary: '#4895ef', bg: '#00254d', text: '#e8f7ff', isDark: true },
  { id: 'theme-tailor-shop', name: 'خیاط‌خانه', primary: '#585481', bg: '#eef0f2', text: '#373261', isDark: false },
  { id: 'theme-botanical-garden', name: 'باغ گیاه‌شناسی', primary: '#40916c', bg: '#f1faee', text: '#1b4332', isDark: false },
  { id: 'theme-flea-market', name: 'بازار دست‌دوم فروشی', primary: '#e76f51', bg: '#f4f1de', text: '#264653', isDark: false },
  { id: 'theme-diner', name: 'رستوران دینر', primary: '#d90429', bg: '#a8dadc', text: '#212121', isDark: false },
  { id: 'theme-irish-pub', name: 'پاب ایرلندی', primary: '#2d6a4f', bg: '#582f0e', text: '#fefae0', isDark: true },
  { id: 'theme-tropical-resort', name: 'تفرجگاه استوایی', primary: '#00b4d8', bg: '#ffffff', text: '#0077b6', isDark: false },
  { id: 'theme-skatepark', name: 'اسکیت پارک', primary: '#f9c74f', bg: '#495057', text: '#f8f9fa', isDark: true },
  { id: 'theme-arcade', name: 'آرکید (کلوپ بازی)', primary: '#f72585', bg: '#141414', text: '#90e0ef', isDark: true },
  { id: 'theme-planetarium', name: 'افلاک‌نما', primary: '#4361ee', bg: '#000814', text: '#e9ecef', isDark: true },
  { id: 'theme-sushi-bar', name: 'سوشی بار', primary: '#ef476f', bg: '#edf2f4', text: '#2b2d42', isDark: false },

  // ===================================================================
  // ===== دسته ۹: دوران‌ها و اعصار تاریخی (۳۴۱-۳۷۰) =====
  // ===================================================================
  { id: 'theme-era-prehistoric', name: 'ماقبل تاریخ', primary: '#e76f51', bg: '#4a2e1d', text: '#faedcd', isDark: true },
  { id: 'theme-era-ancient-egypt', name: 'مصر باستان', primary: '#ffd60a', bg: '#fde4cf', text: '#03045e', isDark: false },
  { id: 'theme-era-greco-roman', name: 'یونان و روم', primary: '#d5bdaf', bg: '#f8f9fa', text: '#800f2f', isDark: false },
  { id: 'theme-era-viking', name: 'عصر وایکینگ‌ها', primary: '#6096ba', bg: '#274c77', text: '#e7ecef', isDark: true },
  { id: 'theme-era-feudal-japan', name: 'ژاپن فئودال', primary: '#a4161a', bg: '#e2dccd', text: '#1b1b1b', isDark: false },
  { id: 'theme-era-medieval-europe', name: 'قرون وسطی', primary: '#8f7b66', bg: '#e8e1d5', text: '#39322a', isDark: false },
  { id: 'theme-era-renaissance-europe', name: 'رنسانس اروپا', primary: '#8d0801', bg: '#f2e8dc', text: '#3c322f', isDark: false },
  { id: 'theme-era-age-of-piracy', name: 'عصر دزدان دریایی', primary: '#bc6c25', bg: '#001219', text: '#fefae0', isDark: true },
  { id: 'theme-era-wild-west', name: 'غرب وحشی', primary: '#b5838d', bg: '#f4eade', text: '#582f0e', isDark: false },
  { id: 'theme-era-industrial-revolution', name: 'انقلاب صنعتی', primary: '#6c757d', bg: '#343a40', text: '#dee2e6', isDark: true },
  { id: 'theme-era-roaring-twenties', name: 'دهه بیست خروشان', primary: '#cda434', bg: '#101010', text: '#f0f0f0', isDark: true },
  { id: 'theme-era-dirty-thirties', name: 'رکود بزرگ (دهه ۳۰)', primary: '#8f7b66', bg: '#e8e1d5', text: '#39322a', isDark: false },
  { id: 'theme-era-world-war-ii', name: 'جنگ جهانی دوم', primary: '#606c38', bg: '#dee2e6', text: '#283618', isDark: false },
  { id: 'theme-era-atomic-age-50s', name: 'عصر اتم (دهه ۵۰)', primary: '#2ec4b6', bg: '#f1faee', text: '#011627', isDark: false },
  { id: 'theme-era-swinging-sixties', name: 'دهه ۶۰ میلادی', primary: '#f9c74f', bg: '#a4161a', text: '#fefae0', isDark: true },
  { id: 'theme-era-disco-70s', name: 'دیسکو (دهه ۷۰)', primary: '#f77f00', bg: '#582f0e', text: '#fefae0', isDark: true },
  { id: 'theme-era-retro-80s', name: 'رترو (دهه ۸۰)', primary: '#f72585', bg: '#e9f6ff', text: '#7209b7', isDark: false },
  { id: 'theme-era-grunge-90s', name: 'گرانج (دهه ۹۰)', primary: '#6c757d', bg: '#212529', text: '#adb5bd', isDark: true },
  { id: 'theme-era-y2k', name: 'Y2K (اواخر دهه ۹۰)', primary: '#4361ee', bg: '#c0c0c0', text: '#141414', isDark: false },
  { id: 'theme-era-persian-empire', name: 'شاهنشاهی هخامنشی', primary: '#9e2a2b', bg: '#003566', text: '#ffd60a', isDark: true },
  { id: 'theme-era-roman-empire', name: 'امپراطوری روم', primary: '#a4161a', bg: '#fefae0', text: '#3c322f', isDark: false },
  { id: 'theme-era-byzantine-empire', name: 'امپراطوری بیزانس', primary: '#6a0dad', bg: '#ffd60a', text: '#141414', isDark: false },
  { id: 'theme-era-ottoman-empire', name: 'امپراطوری عثمانی', primary: '#008037', bg: '#a4161a', text: '#f1faee', isDark: true },
  { id: 'theme-era-mughal-empire', name: 'امپراطوری گورکانی', primary: '#00a896', bg: '#fde4cf', text: '#800f2f', isDark: false },
  { id: 'theme-era-mayan-civilization', name: 'تمدن مایا', primary: '#2a9d8f', bg: '#e9c46a', text: '#264653', isDark: false },
  { id: 'theme-era-incan-empire', name: 'امپراطوری اینکا', primary: '#bc6c25', bg: '#0077b6', text: '#f1faee', isDark: true },
  { id: 'theme-era-age-of-enlightenment', name: 'عصر روشنگری', primary: '#8f7b66', bg: '#f5efe6', text: '#39322a', isDark: false },
  { id: 'theme-era-cold-war', name: 'جنگ سرد', primary: '#d90429', bg: '#dee2e6', text: '#003566', isDark: false },
  { id: 'theme-era-space-race', name: 'رقابت فضایی', primary: '#4361ee', bg: '#212529', text: '#f8f9fa', isDark: true },
  { id: 'theme-era-digital-age', name: 'عصر دیجیتال', primary: '#0077b6', bg: '#f8f9fa', text: '#343a40', isDark: false },

  // ===================================================================
  // ===== دسته ۱۰: خوراکی‌ها و نوشیدنی‌ها (۳۷۱-۴۰۰) =====
  // ===================================================================
  { id: 'theme-food-chocolate-cake', name: 'کیک شکلاتی', primary: '#8d0801', bg: '#4a2e1d', text: '#f5efe6', isDark: true },
  { id: 'theme-food-strawberry-tart', name: 'تارت توت‌فرنگی', primary: '#e63946', bg: '#fefae0', text: '#bc6c25', isDark: false },
  { id: 'theme-food-macarons', name: 'ماکارون', primary: '#ffb3c1', bg: '#f8f9fa', text: '#80b918', isDark: false },
  { id: 'theme-food-ice-cream', name: 'بستنی', primary: '#a2d2ff', bg: '#fff0f3', text: '#e75480', isDark: false },
  { id: 'theme-food-coffee', name: 'قهوه', primary: '#6f4e37', bg: '#f5efe6', text: '#2b1d12', isDark: false },
  { id: 'theme-food-matcha-latte', name: 'ماچا لاته', primary: '#55a630', bg: '#f1f8e9', text: '#2d6a4f', isDark: false },
  { id: 'theme-food-red-wine', name: 'شراب قرمز', primary: '#800f2f', bg: '#f4eade', text: '#390715', isDark: false },
  { id: 'theme-food-cocktail-mojito', name: 'موهیتو', primary: '#80b918', bg: '#e9f6ff', text: '#004b23', isDark: false },
  { id: 'theme-food-sushi', name: 'سوشی', primary: '#ef476f', bg: '#f8f9fa', text: '#2a9d8f', isDark: false },
  { id: 'theme-food-pizza', name: 'پیتزا', primary: '#d90429', bg: '#ffbe0b', text: '#283618', isDark: false },
  { id: 'theme-food-watermelon', name: 'هندوانه', primary: '#d90429', bg: '#d8f3dc', text: '#2d6a4f', isDark: false },
  { id: 'theme-food-lemonade', name: 'لیموناد', primary: '#f9f871', bg: '#e9f6ff', text: '#2d6a4f', isDark: false },
  { id: 'theme-food-blueberry-pancakes', name: 'پنکیک بلوبری', primary: '#4361ee', bg: '#fde4cf', text: '#582f0e', isDark: false },
  { id: 'theme-food-avocado-toast', name: 'تست آووکادو', primary: '#73a942', bg: '#fefae0', text: '#606c38', isDark: false },
  { id: 'theme-food-cinnamon-roll', name: 'رول دارچینی', primary: '#c97c5d', bg: '#fdf4f0', text: '#6c3b2a', isDark: false },
  { id: 'theme-food-pumpkin-spice', name: 'ادویه کدو حلوایی', primary: '#e76f51', bg: '#f5efe6', text: '#bc6c25', isDark: false },
  { id: 'theme-food-saffron', name: 'زعفران', primary: '#fca311', bg: '#fffce8', text: '#a4161a', isDark: false },
  { id: 'theme-food-olives', name: 'زیتون', primary: '#606c38', bg: '#f4f1de', text: '#283618', isDark: false },
  { id: 'theme-food-honey', name: 'عسل', primary: '#ffbe0b', bg: '#fdfce6', text: '#3a2e00', isDark: false },
  { id: 'theme-food-cheese-board', name: 'تخته پنیر', primary: '#e6ccb2', bg: '#800f2f', text: '#f2e8dc', isDark: true },
  { id: 'theme-food-ramen', name: 'رامن', primary: '#e29578', bg: '#582f0e', text: '#fefae0', isDark: true },
  { id: 'theme-food-tacos', name: 'تاکو', primary: '#f9c74f', bg: '#d90429', text: '#43aa8b', isDark: true },
  { id: 'theme-food-curry', name: 'کاری', primary: '#e76f51', bg: '#f4a261', text: '#264653', isDark: false },
  { id: 'theme-food-bubble-tea', name: 'چای بابل', primary: '#8d0801', bg: '#fde4cf', text: '#3c322f', isDark: false },
  { id: 'theme-food-salad', name: 'سالاد', primary: '#55a630', bg: '#ffffff', text: '#d90429', isDark: false },
  { id: 'theme-food-dark-chocolate', name: 'شکلات تلخ', primary: '#f5efe6', bg: '#3c2a21', text: '#d5bdaf', isDark: true },
  { id: 'theme-food-baguette', name: 'باگت', primary: '#dda15e', bg: '#fbf8f2', text: '#8f7b66', isDark: false },
  { id: 'theme-food-espresso', name: 'اسپرسو', primary: '#f5efe6', bg: '#2b1d12', text: '#d5bdaf', isDark: true },
  { id: 'theme-food-smoothie', name: 'اسموتی', primary: '#f15bb5', bg: '#f2eafc', text: '#7209b7', isDark: false },
  { id: 'theme-food-jam', name: 'مربا', primary: '#9e2a2b', bg: '#fff0f3', text: '#4a0808', isDark: false },

]
};