// words.js
const appWords = [

  { "word": "the", "translation": "used to refer to a specific thing", "persian": "این، آن (حرف تعریف)" },
  { "word": "be", "translation": "to exist", "persian": "بودن" },
  { "word": "and", "translation": "used to connect words or phrases", "persian": "و" },
  { "word": "of", "translation": "belonging to", "persian": "از" },
  { "word": "to", "translation": "shows direction, place, or position", "persian": "به" },
  { "word": "a", "translation": "used before nouns", "persian": "یک (حرف تعریف)" },
  { "word": "in", "translation": "inside", "persian": "در" },
  { "word": "that", "translation": "used to introduce a clause", "persian": "که، آن" },
  { "word": "have", "translation": "to own or possess", "persian": "داشتن" },
  { "word": "I", "translation": "refers to yourself", "persian": "من" },
  { "word": "it", "translation": "refers to a thing or animal", "persian": "آن" },
  { "word": "for", "translation": "with the object or purpose of", "persian": "برای" },
  { "word": "not", "translation": "used to make a verb negative", "persian": "نه" },
  { "word": "on", "translation": "position above or touching", "persian": "روی" },
  { "word": "with", "translation": "accompanied by", "persian": "با" },
  { "word": "he", "translation": "male person", "persian": "او (مذکر)" },
  { "word": "as", "translation": "in the same way", "persian": "مانند، به عنوان" },
  { "word": "you", "translation": "refers to the listener", "persian": "تو، شما" },
  { "word": "do", "translation": "to perform", "persian": "انجام دادن" },
  { "word": "at", "translation": "shows place or time", "persian": "در" },
  { "word": "this", "translation": "refers to something near", "persian": "این" },
  { "word": "but", "translation": "except", "persian": "اما" },
  { "word": "his", "translation": "belonging to him", "persian": "او (مذکر، ملکی)" },
  { "word": "by", "translation": "near; using", "persian": "توسط، به وسیله" },
  { "word": "from", "translation": "starting point", "persian": "از" },
  { "word": "they", "translation": "refers to more than one", "persian": "آنها" },
  { "word": "we", "translation": "refers to yourself and others", "persian": "ما" },
  { "word": "say", "translation": "to speak", "persian": "گفتن" },
  { "word": "her", "translation": "belonging to her", "persian": "او (مونث، ملکی)" },
  { "word": "she", "translation": "female person", "persian": "او (مونث)" },
  { "word": "or", "translation": "used to show choice", "persian": "یا" },
  { "word": "an", "translation": "used before vowel sounds", "persian": "یک (قبل از مصوت)" },
  { "word": "will", "translation": "future tense marker", "persian": "خواهد" },
  { "word": "my", "translation": "belonging to me", "persian": "من (ملکی)" },
  { "word": "one", "translation": "the number 1", "persian": "یک" },
  { "word": "all", "translation": "every", "persian": "همه" },
  { "word": "would", "translation": "past/future conditional", "persian": "می‌خواست، خواهد" },
  { "word": "there", "translation": "in that place", "persian": "آنجا" },
  { "word": "their", "translation": "belonging to them", "persian": "آنها (ملکی)" },
  { "word": "what", "translation": "asking about things", "persian": "چه" },
  { "word": "so", "translation": "as a result", "persian": "پس، بنابراین" },
  { "word": "up", "translation": "toward higher place", "persian": "بالا" },
  { "word": "out", "translation": "away from inside", "persian": "بیرون" },
  { "word": "if", "translation": "in case", "persian": "اگر" },
  { "word": "about", "translation": "on the subject of", "persian": "درباره" },
  { "word": "who", "translation": "asking about person", "persian": "چه کسی" },
  { "word": "get", "translation": "to obtain", "persian": "گرفتن" },
  { "word": "which", "translation": "asking about choice", "persian": "کدام" },
  { "word": "go", "translation": "to move", "persian": "رفتن" },
  { "word": "me", "translation": "refers to yourself", "persian": "من (مفعولی)" },
  { "word": "when", "translation": "asking about time", "persian": "چه وقت" },
  { "word": "make", "translation": "to create", "persian": "ساختن" },
  { "word": "can", "translation": "be able to", "persian": "توانستن" },
  { "word": "like", "translation": "enjoy, similar to", "persian": "دوست داشتن، مانند" },
  { "word": "time", "translation": "measured in minutes, hours", "persian": "زمان" },
  { "word": "no", "translation": "not any", "persian": "نه" },
  { "word": "just", "translation": "only; fair", "persian": "فقط، عادلانه" },
  { "word": "him", "translation": "refers to a male", "persian": "او (مذکر، مفعولی)" },
  { "word": "know", "translation": "to be aware", "persian": "دانستن" },
  { "word": "take", "translation": "to get, grab", "persian": "گرفتن" },
  { "word": "people", "translation": "humans", "persian": "مردم" },
  { "word": "into", "translation": "to inside", "persian": "به داخل" },
  { "word": "year", "translation": "12 months", "persian": "سال" },
  { "word": "your", "translation": "belonging to you", "persian": "شما (ملکی)" },
  { "word": "good", "translation": "nice, of quality", "persian": "خوب" },
  { "word": "some", "translation": "an amount", "persian": "برخی" },
  { "word": "could", "translation": "past tense of can", "persian": "می‌توانست" },
  { "word": "them", "translation": "those people", "persian": "آنها (مفعولی)" },
  { "word": "see", "translation": "to look", "persian": "دیدن" },
  { "word": "other", "translation": "different one", "persian": "دیگر" },
  { "word": "than", "translation": "used in comparisons", "persian": "از" },
  { "word": "then", "translation": "at that time", "persian": "سپس" },
  { "word": "now", "translation": "at the present time", "persian": "اکنون" },
  { "word": "look", "translation": "to see", "persian": "نگاه کردن" },
  { "word": "only", "translation": "nothing more", "persian": "فقط" },
  { "word": "come", "translation": "to arrive", "persian": "آمدن" },
  { "word": "its", "translation": "belonging to it", "persian": "آن (ملکی)" },
  { "word": "over", "translation": "above", "persian": "روی، بالای" },
  { "word": "think", "translation": "to have ideas", "persian": "فکر کردن" },
  { "word": "also", "translation": "in addition", "persian": "همچنین" },
  { "word": "back", "translation": "reverse direction", "persian": "عقب، بازگشت" },
  { "word": "after", "translation": "following in time", "persian": "بعد از" },
  { "word": "use", "translation": "to employ for a purpose", "persian": "استفاده کردن" },
  { "word": "two", "translation": "the number 2", "persian": "دو" },
  { "word": "how", "translation": "asking in what way", "persian": "چگونه" },
  { "word": "our", "translation": "belonging to us", "persian": "ما (ملکی)" },
  { "word": "work", "translation": "to do a job", "persian": "کار کردن" },
  { "word": "first", "translation": "number one in order", "persian": "اول" },
  { "word": "well", "translation": "in a good way", "persian": "خوب" },
  { "word": "way", "translation": "method or road", "persian": "راه" },
  { "word": "even", "translation": "used to emphasize", "persian": "حتی" },
  { "word": "new", "translation": "recent, not old", "persian": "جدید" },
  { "word": "want", "translation": "to wish for", "persian": "خواستن" },
  { "word": "because", "translation": "for the reason that", "persian": "زیرا" },
  { "word": "any", "translation": "one, some, or all", "persian": "هر، هیچ" },
  { "word": "these", "translation": "plural of this", "persian": "اینها" },
  { "word": "give", "translation": "to hand to someone", "persian": "دادن" },
  { "word": "day", "translation": "24 hours", "persian": "روز" },
  { "word": "most", "translation": "greatest amount", "persian": "بیشتر" },
  { "word": "us", "translation": "refers to we", "persian": "ما (مفعولی)" },
  { "word": "is", "translation": "present of be", "persian": "است" },
  { "word": "was", "translation": "past of be", "persian": "بود" },
  { "word": "are", "translation": "present plural of be", "persian": "هستند" },
  { "word": "were", "translation": "past plural of be", "persian": "بودند" },
  { "word": "been", "translation": "past participle of be", "persian": "بوده است" },
  { "word": "has", "translation": "present of have (he/she/it)", "persian": "دارد" },
  { "word": "had", "translation": "past of have", "persian": "داشت" },
  { "word": "does", "translation": "present of do (he/she/it)", "persian": "می‌کند" },
  { "word": "did", "translation": "past of do", "persian": "کرد" },
  { "word": "done", "translation": "past participle of do", "persian": "انجام شده" },
  { "word": "more", "translation": "greater amount", "persian": "بیشتر" },
  { "word": "many", "translation": "a large number", "persian": "زیاد" },
  { "word": "much", "translation": "a lot", "persian": "خیلی" },
  { "word": "those", "translation": "plural of that", "persian": "آنها" },
  { "word": "every", "translation": "each one", "persian": "هر" },
  { "word": "might", "translation": "may, possibility", "persian": "ممکن است" },
  { "word": "must", "translation": "have to", "persian": "باید" },
  { "word": "shall", "translation": "will (formal)", "persian": "باید" },
  { "word": "should", "translation": "ought to", "persian": "باید" },
  { "word": "may", "translation": "can, possible", "persian": "ممکن است" },
  { "word": "yet", "translation": "until now", "persian": "هنوز" },
  { "word": "ever", "translation": "at any time", "persian": "تا کنون" },
  { "word": "since", "translation": "from a past time", "persian": "از زمانی که" },
  { "word": "always", "translation": "at all times", "persian": "همیشه" },
  { "word": "once", "translation": "one time", "persian": "یک بار" },
  { "word": "again", "translation": "another time", "persian": "دوباره" },
  { "word": "never", "translation": "not ever", "persian": "هرگز" },
  { "word": "whose", "translation": "belonging to whom", "persian": "مال چه کسی" },
  { "word": "where", "translation": "in what place", "persian": "کجا" },
  { "word": "while", "translation": "during", "persian": "در حالی که" },
  { "word": "before", "translation": "earlier than", "persian": "قبل از" },
  { "word": "after", "translation": "later than", "persian": "بعد از" },
  { "word": "though", "translation": "although", "persian": "اگرچه" },
  { "word": "although", "translation": "despite the fact that", "persian": "اگرچه" },
  { "word": "however", "translation": "but", "persian": "اما" },
  { "word": "because", "translation": "for the reason that", "persian": "زیرا" },
  { "word": "during", "translation": "throughout a period", "persian": "در طول" },
  { "word": "within", "translation": "inside a limit", "persian": "در داخل" },
  { "word": "without", "translation": "not having", "persian": "بدون" },
  { "word": "between", "translation": "in the space separating", "persian": "بین" },
  { "word": "against", "translation": "in opposition to", "persian": "علیه" },
  { "word": "toward", "translation": "in the direction of", "persian": "به سمت" },
  { "word": "among", "translation": "in the middle of", "persian": "در میان" },
  { "word": "upon", "translation": "on", "persian": "بر روی" },
  { "word": "beside", "translation": "next to", "persian": "کنار" },
  { "word": "beyond", "translation": "further than", "persian": "فراتر از" },
  { "word": "beneath", "translation": "under", "persian": "زیر" },
  { "word": "unless", "translation": "except if", "persian": "مگر اینکه" },
  { "word": "whether", "translation": "if, expressing a doubt", "persian": "آیا" },
  { "word": "upon", "translation": "on", "persian": "بر روی" },
  { "word": "thus", "translation": "as a result", "persian": "بنابراین" },
  { "word": "further", "translation": "more distant", "persian": "دورتر، بیشتر" },
  { "word": "least", "translation": "smallest in amount", "persian": "کمترین" },
  { "word": "own", "translation": "belonging to oneself", "persian": "خود، مالک" },
  { "word": "such", "translation": "of the type already mentioned", "persian": "چنین" },
  { "word": "rather", "translation": "preferably", "persian": "ترجیحاً" },
  { "word": "quite", "translation": "completely or to a large degree", "persian": "کاملاً" },
  { "word": "instead", "translation": "in place of", "persian": "به جای" },
  { "word": "otherwise", "translation": "in another way", "persian": "در غیر این صورت" },
  { "word": "indeed", "translation": "in fact, really", "persian": "واقعاً" },
  { "word": "besides", "translation": "in addition to", "persian": "علاوه بر" },
  { "word": "regard", "translation": "to consider", "persian": "در نظر گرفتن" },
  { "word": "concern", "translation": "worry, matter", "persian": "نگرانی، موضوع" },
  { "word": "seem", "translation": "appear to be", "persian": "به نظر رسیدن" },
  { "word": "allow", "translation": "to let happen", "persian": "اجازه دادن" },
  { "word": "expect", "translation": "to think something will happen", "persian": "انتظار داشتن" },
  { "word": "require", "translation": "to need", "persian": "نیاز داشتن" },
  { "word": "appear", "translation": "to come into sight", "persian": "ظاهر شدن" },
  { "word": "develop", "translation": "to grow, make better", "persian": "توسعه دادن" },
  { "word": "support", "translation": "to help", "persian": "حمایت کردن" },
  { "word": "provide", "translation": "to supply", "persian": "ارائه دادن" },
  { "word": "continue", "translation": "to keep going", "persian": "ادامه دادن" },
  { "word": "increase", "translation": "to make more", "persian": "افزایش دادن" },
  { "word": "include", "translation": "to have as part", "persian": "شامل بودن" },
  { "word": "lead", "translation": "to go first", "persian": "رهبری کردن" },
  { "word": "result", "translation": "the outcome", "persian": "نتیجه" },
  { "word": "change", "translation": "to make different", "persian": "تغییر دادن" },
  { "word": "form", "translation": "shape, to shape", "persian": "فرم، شکل دادن" },
  { "word": "produce", "translation": "to make", "persian": "تولید کردن" },
  { "word": "explain", "translation": "to make clear", "persian": "توضیح دادن" },
  { "word": "recognize", "translation": "to know again", "persian": "تشخیص دادن" },
  { "word": "suggest", "translation": "to propose", "persian": "پیشنهاد دادن" },
  { "word": "raise", "translation": "to lift up", "persian": "بالا بردن" },
  { "word": "refer", "translation": "to direct attention", "persian": "ارجاع دادن" },
  { "word": "compare", "translation": "to see similarities", "persian": "مقایسه کردن" },
  { "word": "manage", "translation": "to control, handle", "persian": "مدیریت کردن" },
  { "word": "treat", "translation": "to act toward, to cure", "persian": "رفتار کردن، درمان کردن" },
  { "word": "choose", "translation": "to select", "persian": "انتخاب کردن" },
  { "word": "avoid", "translation": "to stay away from", "persian": "اجتناب کردن" },
  { "word": "prevent", "translation": "to stop from happening", "persian": "جلوگیری کردن" },
  { "word": "realize", "translation": "to understand fully", "persian": "متوجه شدن" },
  
  
  { "word": "replace", "translation": "to take the place of", "persian": "جایگزین کردن" },
  { "word": "claim", "translation": "to say something is true", "persian": "ادعا کردن" },
  { "word": "contain", "translation": "to have inside", "persian": "حاوی بودن" },
  { "word": "apply", "translation": "to put to use, to request", "persian": "درخواست دادن، به کار بردن" },
  { "word": "examine", "translation": "to look at closely", "persian": "بررسی کردن" },
  { "word": "discover", "translation": "to find for the first time", "persian": "کشف کردن" },
  { "word": "indicate", "translation": "to point out, to show", "persian": "نشان دادن" },
  { "word": "establish", "translation": "to set up, create", "persian": "تاسیس کردن" },
  { "word": "mention", "translation": "to refer to briefly", "persian": "ذکر کردن" },
  { "word": "assume", "translation": "to take as true", "persian": "فرض کردن" },
  { "word": "prepare", "translation": "to make ready", "persian": "آماده کردن" },
  { "word": "respond", "translation": "to answer", "persian": "پاسخ دادن" },
  { "word": "protect", "translation": "to keep safe", "persian": "محافظت کردن" },
  { "word": "reduce", "translation": "to make less", "persian": "کاهش دادن" },
  { "word": "avoid", "translation": "to keep away from", "persian": "اجتناب کردن" },
  { "word": "determine", "translation": "to find out", "persian": "تعیین کردن" },
  { "word": "achieve", "translation": "to succeed in", "persian": "دستیابی یافتن" },
  { "word": "improve", "translation": "to make better", "persian": "بهبود بخشیدن" },
  { "word": "reflect", "translation": "to bounce back, to show", "persian": "منعکس کردن، نشان دادن" },
  { "word": "operate", "translation": "to work, function", "persian": "عمل کردن، کار کردن" },
  { "word": "accept", "translation": "to agree to take", "persian": "پذیرفتن" },
  { "word": "attempt", "translation": "to try", "persian": "تلاش کردن" },
  { "word": "prove", "translation": "to show as true", "persian": "ثابت کردن" },
  { "word": "relate", "translation": "to be connected", "persian": "ارتباط داشتن" },
  { "word": "depend", "translation": "to rely on", "persian": "وابسته بودن" },
  { "word": "enable", "translation": "to make possible", "persian": "امکان‌پذیر کردن" },
  { "word": "focus", "translation": "to pay special attention", "persian": "تمرکز کردن" },
  { "word": "suggest", "translation": "to offer an idea", "persian": "پیشنهاد دادن" },
  { "word": "respond", "translation": "to answer", "persian": "پاسخ دادن" },
  { "word": "compare", "translation": "to look for similarities", "persian": "مقایسه کردن" },
  { "word": "identify", "translation": "to recognize", "persian": "تشخیص دادن" },
  { "word": "involve", "translation": "to include", "persian": "درگیر کردن" },
  { "word": "contribute", "translation": "to give to a common purpose", "persian": "مشارکت کردن" },
  { "word": "assess", "translation": "to evaluate", "persian": "ارزیابی کردن" },
  { "word": "select", "translation": "to choose", "persian": "انتخاب کردن" },
  { "word": "invest", "translation": "to put in money or time", "persian": "سرمایه‌گذاری کردن" },
  { "word": "encourage", "translation": "to give support", "persian": "تشویق کردن" },
  { "word": "affect", "translation": "to influence", "persian": "تاثیر گذاشتن" },
  { "word": "participate", "translation": "to take part", "persian": "شرکت کردن" },
  { "word": "promote", "translation": "to support growth", "persian": "ارتقاء دادن" },
  { "word": "appreciate", "translation": "to be thankful", "persian": "قدردانی کردن" },
  { "word": "grant", "translation": "to give officially", "persian": "اعطا کردن" },
  { "word": "expand", "translation": "to make bigger", "persian": "گسترش دادن" },
  { "word": "decline", "translation": "to go down, refuse", "persian": "کاهش یافتن، رد کردن" },
  { "word": "address", "translation": "to speak to; location", "persian": "نشانی، خطاب قرار دادن" },
  { "word": "adopt", "translation": "to take as one's own", "persian": "پذیرفتن، به فرزندی گرفتن" },
  { "word": "implement", "translation": "to put into effect", "persian": "اجرا کردن" },
  { "word": "monitor", "translation": "to watch closely", "persian": "نظارت کردن" },
  { "word": "emphasize", "translation": "to stress importance", "persian": "تاکید کردن" },
  { "word": "clarify", "translation": "to make clear", "persian": "شفاف‌سازی کردن" },
  { "word": "facilitate", "translation": "to make easier", "persian": "تسهیل کردن" },
  { "word": "acquire", "translation": "to get, obtain", "persian": "به دست آوردن" },
  { "word": "allocate", "translation": "to distribute", "persian": "اختصاص دادن" },
  { "word": "anticipate", "translation": "to expect", "persian": "انتظار داشتن، پیش‌بینی کردن" },
  { "word": "analyze", "translation": "to study closely", "persian": "تحلیل کردن" },
  { "word": "appeal", "translation": "to request; attraction", "persian": "درخواست کردن، جذابیت" },
  { "word": "assure", "translation": "to make certain", "persian": "اطمینان دادن" },
  { "word": "balance", "translation": "a state of equality", "persian": "تعادل" },
  { "word": "barrier", "translation": "something that blocks", "persian": "مانع" },
  { "word": "capable", "translation": "able to do", "persian": "توانمند" },
  { "word": "collapse", "translation": "to fall down", "persian": "فروپاشی کردن" },
  { "word": "commission", "translation": "an official group; payment", "persian": "کمیسیون" },
  { "word": "comply", "translation": "to follow rules", "persian": "پیروی کردن" },
  { "word": "conceal", "translation": "to hide", "persian": "پنهان کردن" },
  { "word": "conclude", "translation": "to finish, decide", "persian": "نتیجه‌گیری کردن" },
  { "word": "confirm", "translation": "to make sure", "persian": "تایید کردن" },
  { "word": "confront", "translation": "to face boldly", "persian": "روبرو شدن" },
  { "word": "conserve", "translation": "to save or protect", "persian": "محافظت کردن، صرفه‌جویی کردن" },
  { "word": "contribute", "translation": "to give (help)", "persian": "مشارکت کردن" },
  { "word": "convert", "translation": "to change form", "persian": "تبدیل کردن" },
  { "word": "convince", "translation": "to persuade", "persian": "قانع کردن" },
  { "word": "correspond", "translation": "to match or communicate", "persian": "مطابقت داشتن، مکاتبه کردن" },
  { "word": "counter", "translation": "opposite, to respond", "persian": "مقابل، پیشخوان" },
  { "word": "debate", "translation": "formal discussion", "persian": "مناظره" },
  { "word": "dedicate", "translation": "to give time or effort", "persian": "اختصاص دادن" },
  { "word": "defend", "translation": "to protect", "persian": "دفاع کردن" },
  { "word": "demonstrate", "translation": "to show, protest", "persian": "نشان دادن، تظاهرات کردن" },
  { "word": "deny", "translation": "to refuse to accept", "persian": "انکار کردن" },
  { "word": "depend", "translation": "to rely", "persian": "وابسته بودن" },
  { "word": "depress", "translation": "to make sad", "persian": "افسرده کردن" },
  { "word": "derive", "translation": "to get from", "persian": "گرفتن از، مشتق شدن" },
  { "word": "detect", "translation": "to discover", "persian": "تشخیص دادن" },
  { "word": "disclose", "translation": "to reveal", "persian": "افشا کردن" },
  { "word": "dispose", "translation": "to throw away", "persian": "دور انداختن" },
  { "word": "distract", "translation": "to draw attention away", "persian": "حواس پرت کردن" },
  { "word": "eliminate", "translation": "to remove", "persian": "حذف کردن" },
  { "word": "emerge", "translation": "to come out", "persian": "پدیدار شدن" },
  { "word": "enforce", "translation": "to make obey", "persian": "اجرا کردن" },
  { "word": "enhance", "translation": "to improve", "persian": "افزایش دادن" },
  { "word": "ensure", "translation": "to make sure", "persian": "اطمینان حاصل کردن" },
  { "word": "establish", "translation": "to set up", "persian": "تاسیس کردن" },
  { "word": "evaluate", "translation": "to judge", "persian": "ارزیابی کردن" },
  { "word": "exclude", "translation": "to leave out", "persian": "حذف کردن" },
  { "word": "expand", "translation": "to become bigger", "persian": "گسترش دادن" },
  { "word": "explore", "translation": "to travel, search", "persian": "کاوش کردن" },
  { "word": "expose", "translation": "to uncover", "persian": "آشکار کردن" },
  { "word": "facilitate", "translation": "to help make easier", "persian": "تسهیل کردن" },
  { "word": "forecast", "translation": "to predict", "persian": "پیش‌بینی کردن" },
  { "word": "forgive", "translation": "to stop blaming", "persian": "بخشیدن" },
  { "word": "fulfill", "translation": "to satisfy or complete", "persian": "برآورده کردن" },
  { "word": "guarantee", "translation": "to promise", "persian": "تضمین کردن" },
  { "word": "ignore", "translation": "to not pay attention", "persian": "نادیده گرفتن" },
  { "word": "impose", "translation": "to force on others", "persian": "تحمیل کردن" },
  { "word": "incorporate", "translation": "to include", "persian": "ادغام کردن" },
  { "word": "indicate", "translation": "to point out", "persian": "نشان دادن" },
  { "word": "influence", "translation": "to affect", "persian": "تاثیر گذاشتن" },
  { "word": "initiate", "translation": "to start", "persian": "آغاز کردن" },
  { "word": "inspire", "translation": "to motivate", "persian": "الهام بخشیدن" },
  { "word": "integrate", "translation": "to combine", "persian": "ادغام کردن" },
  { "word": "interact", "translation": "to communicate", "persian": "تعامل داشتن" },
  { "word": "interpret", "translation": "to explain meaning", "persian": "تفسیر کردن" },
  { "word": "interrupt", "translation": "to break the flow", "persian": "قطع کردن" },
  { "word": "intervene", "translation": "to get involved", "persian": "مداخله کردن" },
  { "word": "investigate", "translation": "to examine", "persian": "بررسی کردن" },
  { "word": "justify", "translation": "to prove right", "persian": "توجیه کردن" },
  { "word": "limit", "translation": "to set a boundary", "persian": "محدود کردن" },
  { "word": "maintain", "translation": "to keep up", "persian": "حفظ کردن" },
  { "word": "maximize", "translation": "to increase to the most", "persian": "بیشینه کردن" },
  { "word": "minimize", "translation": "to reduce to the least", "persian": "کمینه کردن" },
  { "word": "modify", "translation": "to change", "persian": "تغییر دادن" },
  { "word": "motivate", "translation": "to give reason", "persian": "انگیزه دادن" },
  { "word": "negotiate", "translation": "to discuss for agreement", "persian": "مذاکره کردن" },
  { "word": "observe", "translation": "to watch carefully", "persian": "مشاهده کردن" },
  { "word": "overcome", "translation": "to defeat", "persian": "غلبه کردن" },
  { "word": "participate", "translation": "to join in", "persian": "شرکت کردن" },
  { "word": "perceive", "translation": "to understand, sense", "persian": "درک کردن" },
  { "word": "permit", "translation": "to allow", "persian": "اجازه دادن" },
  { "word": "persist", "translation": "to continue firmly", "persian": "پافشاری کردن" },
  { "word": "predict", "translation": "to forecast", "persian": "پیش‌بینی کردن" },
  { "word": "presume", "translation": "to suppose", "persian": "فرض کردن" },
  { "word": "prioritize", "translation": "to put in order of importance", "persian": "اولویت‌بندی کردن" },
  { "word": "proceed", "translation": "to move forward", "persian": "ادامه دادن" },
  { "word": "prohibit", "translation": "to not allow", "persian": "ممنوع کردن" },
  { "word": "promote", "translation": "to help grow", "persian": "ارتقاء دادن" },
  { "word": "pursue", "translation": "to follow", "persian": "دنبال کردن" },
  { "word": "question", "translation": "to ask", "persian": "سوال کردن" },
  { "word": "quote", "translation": "to repeat exactly", "persian": "نقل قول کردن" },
  { "word": "react", "translation": "to respond", "persian": "واکنش نشان دادن" },
  { "word": "recommend", "translation": "to suggest as good", "persian": "توصیه کردن" },
  { "word": "recover", "translation": "to get better", "persian": "بهبودی یافتن" },
  { "word": "reduce", "translation": "to make smaller", "persian": "کاهش دادن" },
  { "word": "refer", "translation": "to mention, direct to", "persian": "ارجاع دادن" },
  { "word": "reflect", "translation": "to show image or idea", "persian": "منعکس کردن، نشان دادن" },
  { "word": "refuse", "translation": "to say no", "persian": "رد کردن" },
  { "word": "regret", "translation": "to feel sorry", "persian": "پشیمان شدن" },
  { "word": "relate", "translation": "to connect", "persian": "ارتباط داشتن" },
  { "word": "rely", "translation": "to depend", "persian": "اعتماد کردن" },
  { "word": "remove", "translation": "to take away", "persian": "حذف کردن" },
  { "word": "replace", "translation": "to take the place of", "persian": "جایگزین کردن" },
  { "word": "request", "translation": "to ask for", "persian": "درخواست کردن" },
  { "word": "require", "translation": "to need", "persian": "نیاز داشتن" },
  { "word": "resolve", "translation": "to solve", "persian": "حل کردن" },
  { "word": "restrict", "translation": "to limit", "persian": "محدود کردن" },
  { "word": "retain", "translation": "to keep", "persian": "نگه داشتن" },
  { "word": "reveal", "translation": "to show, uncover", "persian": "آشکار کردن" },
  { "word": "reverse", "translation": "to go backwards", "persian": "معکوس کردن" },
  { "word": "review", "translation": "to look at again", "persian": "بررسی کردن" },
  { "word": "revise", "translation": "to edit, change", "persian": "اصلاح کردن" },
  { "word": "satisfy", "translation": "to please", "persian": "راضی کردن" },
  { "word": "seek", "translation": "to look for", "persian": "جستجو کردن" },
  { "word": "select", "translation": "to choose", "persian": "انتخاب کردن" },
  { "word": "separate", "translation": "to divide", "persian": "جدا کردن" },
  { "word": "settle", "translation": "to resolve, live in", "persian": "حل و فصل کردن، سکونت کردن" },
  { "word": "shift", "translation": "to move or change", "persian": "تغییر دادن" },
  { "word": "solve", "translation": "to find an answer", "persian": "حل کردن" },
  { "word": "specify", "translation": "to state clearly", "persian": "مشخص کردن" },
  { "word": "struggle", "translation": "to try hard", "persian": "تقلا کردن" },
  { "word": "submit", "translation": "to hand in", "persian": "ارائه دادن" },
  { "word": "succeed", "translation": "to do well", "persian": "موفق شدن" },
  { "word": "suggest", "translation": "to propose", "persian": "پیشنهاد دادن" },
  { "word": "support", "translation": "to back up", "persian": "حمایت کردن" },
  { "word": "supply", "translation": "to provide", "persian": "تامین کردن" },
  { "word": "suspend", "translation": "to stop for a time", "persian": "تعلیق کردن" },
  { "word": "sustain", "translation": "to keep up", "persian": "حفظ کردن" },
  { "word": "target", "translation": "to aim at", "persian": "هدف قرار دادن" },
  { "word": "terminate", "translation": "to end", "persian": "خاتمه دادن" },
  { "word": "tolerate", "translation": "to accept", "persian": "تحمل کردن" },
  { "word": "transform", "translation": "to change greatly", "persian": "تغییر دادن" },
  { "word": "transmit", "translation": "to send", "persian": "انتقال دادن" },
  { "word": "undergo", "translation": "to go through", "persian": "متحمل شدن" },
  { "word": "undertake", "translation": "to agree to do", "persian": "برعهده گرفتن" },
  { "word": "update", "translation": "to bring up to date", "persian": "به‌روزرسانی کردن" },
  { "word": "urge", "translation": "to strongly recommend", "persian": "تشویق کردن" },
  { "word": "utilize", "translation": "to use", "persian": "استفاده کردن" },
  { "word": "vary", "translation": "to change", "persian": "تغییر دادن" },
  { "word": "view", "translation": "to look at", "persian": "دیدن، نگاه کردن" },
  { "word": "violate", "translation": "to break a rule", "persian": "نقض کردن" },
  { "word": "witness", "translation": "to see an event", "persian": "شاهد بودن" }
,

  { "word": "abandon", "translation": "to leave completely", "persian": "رها کردن، ترک کردن" },
  { "word": "ability", "translation": "power or skill to do something", "persian": "توانایی" },
  { "word": "abolish", "translation": "to officially end", "persian": "لغو کردن" },
  { "word": "abuse", "translation": "cruel or violent treatment", "persian": "سوء استفاده" },
  { "word": "access", "translation": "the right to use or reach", "persian": "دسترسی" },
  { "word": "accomplish", "translation": "to achieve or finish", "persian": "انجام دادن" },
  { "word": "according", "translation": "as stated by", "persian": "طبق، بر اساس" },
  { "word": "accuse", "translation": "to blame someone", "persian": "متهم کردن" },
  { "word": "acknowledge", "translation": "to admit or accept", "persian": "پذیرفتن، تصدیق کردن" },
  { "word": "adapt", "translation": "to change for a new situation", "persian": "سازگار شدن" },
  { "word": "adjust", "translation": "to change slightly", "persian": "تنظیم کردن" },
  { "word": "affect", "translation": "to influence", "persian": "تاثیر گذاشتن" },
  { "word": "afford", "translation": "to have enough for", "persian": "توانایی مالی داشتن" },
  { "word": "agenda", "translation": "list of items for discussion", "persian": "دستور جلسه" },
  { "word": "aid", "translation": "help or support", "persian": "کمک" },
  { "word": "allocate", "translation": "to assign or distribute", "persian": "اختصاص دادن" },
  { "word": "alter", "translation": "to change or modify", "persian": "تغییر دادن" },
  { "word": "amend", "translation": "to change, especially a law", "persian": "اصلاح کردن" },
  { "word": "announce", "translation": "to make public", "persian": "اعلام کردن" },
  { "word": "annual", "translation": "happening once a year", "persian": "سالانه" },
  { "word": "anticipate", "translation": "to expect, predict", "persian": "انتظار داشتن" },
  { "word": "anxiety", "translation": "nervous worry", "persian": "اضطراب" },
  { "word": "apparent", "translation": "obvious, clear", "persian": "آشکار، واضح" },
  { "word": "appeal", "translation": "a serious request", "persian": "درخواست، تجدیدنظر" },
  { "word": "appoint", "translation": "to assign a role", "persian": "منصوب کردن" },
  { "word": "approach", "translation": "a way to do something", "persian": "رویکرد" },
  { "word": "appropriate", "translation": "suitable", "persian": "مناسب" },
  { "word": "approve", "translation": "to agree with", "persian": "تایید کردن" },
  { "word": "approximate", "translation": "almost correct", "persian": "تقریبی" },
  { "word": "arise", "translation": "to happen", "persian": "رخ دادن" },
  { "word": "arrange", "translation": "to organize", "persian": "ترتیب دادن" },
  { "word": "arrest", "translation": "to take into custody", "persian": "دستگیر کردن" },
  { "word": "article", "translation": "a piece of writing", "persian": "مقاله" },
  { "word": "artificial", "translation": "not natural", "persian": "مصنوعی" },
  { "word": "aspect", "translation": "part or feature", "persian": "جنبه" },
  { "word": "assess", "translation": "to evaluate", "persian": "ارزیابی کردن" },
  { "word": "assign", "translation": "to give a task", "persian": "واگذار کردن" },
  { "word": "assist", "translation": "to help", "persian": "کمک کردن" },
  { "word": "associate", "translation": "to connect in your mind", "persian": "ارتباط دادن" },
  { "word": "assume", "translation": "to suppose", "persian": "فرض کردن" },
  { "word": "assure", "translation": "to make certain", "persian": "اطمینان دادن" },
  { "word": "atmosphere", "translation": "the mood or air", "persian": "جو، فضای محیط" },
  { "word": "attempt", "translation": "to try", "persian": "تلاش کردن" },
  { "word": "attitude", "translation": "way of thinking", "persian": "نگرش" },
  { "word": "authority", "translation": "power or right to control", "persian": "اقتدار" },
  { "word": "aware", "translation": "knowing about", "persian": "آگاه" },
  { "word": "background", "translation": "experience, education, or scenery", "persian": "سابقه، پیش‌زمینه" },
  { "word": "balance", "translation": "state of equality", "persian": "تعادل" },
  { "word": "barrier", "translation": "something that blocks", "persian": "مانع" },
  { "word": "benefit", "translation": "advantage", "persian": "منفعت" },
  { "word": "bias", "translation": "prejudice", "persian": "تعصب" },
  { "word": "blame", "translation": "to say someone is responsible", "persian": "سرزنش کردن" },
  { "word": "boost", "translation": "to increase or improve", "persian": "تقویت کردن" },
  { "word": "brilliant", "translation": "very smart or bright", "persian": "درخشان، باهوش" },
  { "word": "burden", "translation": "a heavy load", "persian": "بار، فشار" },
  { "word": "campaign", "translation": "planned actions for a goal", "persian": "کمپین، مبارزه" },
  { "word": "capacity", "translation": "ability or amount", "persian": "ظرفیت" },
  { "word": "category", "translation": "group, class", "persian": "دسته، گروه" },
  { "word": "cease", "translation": "to stop", "persian": "متوقف کردن" },
  { "word": "challenge", "translation": "something difficult", "persian": "چالش" },
  { "word": "channel", "translation": "TV station or a path", "persian": "کانال" },
  { "word": "charge", "translation": "to ask for payment or to accuse", "persian": "هزینه، متهم کردن" },
  { "word": "cite", "translation": "to quote or refer to", "persian": "استناد کردن" },
  { "word": "collapse", "translation": "to fall down", "persian": "فروپاشی کردن" },
  { "word": "colleague", "translation": "a co-worker", "persian": "همکار" },
  { "word": "comment", "translation": "an opinion or statement", "persian": "نظر" },
  { "word": "commit", "translation": "to do, carry out", "persian": "مرتکب شدن" },
  { "word": "commodity", "translation": "product for sale", "persian": "کالا" },
  { "word": "compete", "translation": "to try to win", "persian": "رقابت کردن" },
  { "word": "compile", "translation": "to put together", "persian": "گردآوری کردن" },
  { "word": "complaint", "translation": "expression of dissatisfaction", "persian": "شکایت" },
  { "word": "complement", "translation": "something that completes", "persian": "مکمل" },
  { "word": "complex", "translation": "not simple", "persian": "پیچیده" },
  { "word": "comply", "translation": "to obey rules", "persian": "پیروی کردن" },
  { "word": "component", "translation": "part of something", "persian": "جزء، مولفه" },
  { "word": "comprehensive", "translation": "complete", "persian": "جامع" },
  { "word": "compromise", "translation": "agreement by both sides", "persian": "سازش" },
  { "word": "conceal", "translation": "to hide", "persian": "پنهان کردن" },
  { "word": "conclude", "translation": "to finish, decide", "persian": "نتیجه گرفتن" },
  { "word": "concrete", "translation": "real, not abstract", "persian": "ملموس، واقعی" },
  { "word": "conduct", "translation": "to organize or do", "persian": "انجام دادن" },
  { "word": "confident", "translation": "sure, certain", "persian": "مطمئن" },
  { "word": "conflict", "translation": "serious disagreement", "persian": "درگیری، اختلاف" },
  { "word": "confuse", "translation": "to make unclear", "persian": "گیج کردن" },
  { "word": "congress", "translation": "law-making body", "persian": "کنگره" },
  { "word": "conscious", "translation": "aware", "persian": "آگاه" },
  { "word": "consequence", "translation": "result", "persian": "نتیجه" },
  { "word": "conservative", "translation": "favoring tradition", "persian": "محافظه‌کار" },
  { "word": "considerable", "translation": "notable, significant", "persian": "قابل توجه" },
  { "word": "consistent", "translation": "unchanging, regular", "persian": "ثابت، سازگار" },
  { "word": "conspiracy", "translation": "secret plan", "persian": "توطئه" },
  { "word": "constant", "translation": "not changing", "persian": "ثابت" },
  { "word": "constitute", "translation": "to form, make up", "persian": "تشکیل دادن" },
  { "word": "constraint", "translation": "limitation", "persian": "محدودیت" },
  { "word": "consult", "translation": "to seek advice", "persian": "مشاوره گرفتن" },
  { "word": "consume", "translation": "to use up", "persian": "مصرف کردن" },
  { "word": "contact", "translation": "touch or communication", "persian": "ارتباط" },
  { "word": "contemplate", "translation": "to think deeply", "persian": "تعمق کردن" },
  { "word": "contemporary", "translation": "modern, same time", "persian": "معاصر" },
  { "word": "contend", "translation": "to argue or compete", "persian": "رقابت کردن، مبارزه کردن" },
  { "word": "content", "translation": "the things inside", "persian": "محتوا" },
  { "word": "contest", "translation": "competition", "persian": "مسابقه" },
  { "word": "context", "translation": "surrounding situation", "persian": "زمینه" },
  { "word": "continual", "translation": "happening repeatedly", "persian": "پیوسته" },
  { "word": "contradict", "translation": "to say the opposite", "persian": "تناقض داشتن" },
  { "word": "contrary", "translation": "opposite", "persian": "برعکس، مخالف" },
  { "word": "contribute", "translation": "to help or give", "persian": "مشارکت کردن" },
  { "word": "controversy", "translation": "public disagreement", "persian": "جدال، بحث" },
  { "word": "convenient", "translation": "easy, suitable", "persian": "راحت، مناسب" },
  { "word": "conventional", "translation": "usual, normal", "persian": "مرسوم" },
  { "word": "convert", "translation": "to change form", "persian": "تبدیل کردن" },
  { "word": "convey", "translation": "to communicate", "persian": "انتقال دادن" },
  { "word": "convince", "translation": "to persuade", "persian": "قانع کردن" },
  { "word": "cooperate", "translation": "to work together", "persian": "همکاری کردن" },
  { "word": "coordinate", "translation": "to organize together", "persian": "هماهنگ کردن" },
  { "word": "core", "translation": "central part", "persian": "هسته" },
  { "word": "corporate", "translation": "related to business", "persian": "شرکتی" },
  { "word": "correlate", "translation": "to have a relationship", "persian": "ارتباط داشتن" },
  { "word": "correspond", "translation": "to match or write to", "persian": "مطابقت داشتن، مکاتبه کردن" },
  { "word": "corrupt", "translation": "dishonest for money", "persian": "فاسد" },
  { "word": "counter", "translation": "opposite, reply", "persian": "مقابل، پیشخوان" },
  { "word": "coverage", "translation": "news reporting", "persian": "پوشش خبری" },
  { "word": "crucial", "translation": "very important", "persian": "حیاتی" },
  { "word": "currency", "translation": "money used", "persian": "واحد پول" },
  { "word": "cycle", "translation": "series that repeats", "persian": "چرخه" },
  { "word": "data", "translation": "information", "persian": "داده" },
  { "word": "database", "translation": "organized information", "persian": "پایگاه داده" },
  { "word": "debate", "translation": "formal discussion", "persian": "مناظره" },
  { "word": "debt", "translation": "money owed", "persian": "بدهی" },
  { "word": "decade", "translation": "ten years", "persian": "دهه" },
  { "word": "decide", "translation": "to choose", "persian": "تصمیم گرفتن" },
  { "word": "decision", "translation": "choice made", "persian": "تصمیم" },
  { "word": "declare", "translation": "to announce officially", "persian": "اعلام کردن" },
  { "word": "decline", "translation": "to go down", "persian": "کاهش یافتن" },
  { "word": "decrease", "translation": "to make less", "persian": "کاهش دادن" },
  { "word": "dedicate", "translation": "to give time or effort", "persian": "اختصاص دادن" },
  { "word": "deem", "translation": "to consider", "persian": "در نظر گرفتن" },
  { "word": "defeat", "translation": "to win against", "persian": "شکست دادن" },
  { "word": "defend", "translation": "to protect", "persian": "دفاع کردن" },
  { "word": "deficit", "translation": "shortage", "persian": "کسری" },
  { "word": "define", "translation": "to explain meaning", "persian": "تعریف کردن" },
  { "word": "defy", "translation": "to refuse to obey", "persian": "مقاومت کردن" },
  { "word": "delegate", "translation": "a representative", "persian": "نماینده" },
  { "word": "delete", "translation": "to remove", "persian": "حذف کردن" },
  { "word": "deliberate", "translation": "intentional or to discuss", "persian": "عمدی، تعمق کردن" },
  { "word": "deliver", "translation": "to bring or send", "persian": "تحویل دادن" },
  { "word": "demand", "translation": "to ask strongly", "persian": "درخواست کردن" },
  { "word": "democracy", "translation": "government by the people", "persian": "دموکراسی" },
  { "word": "demonstrate", "translation": "to show or protest", "persian": "نشان دادن، تظاهرات کردن" },
  { "word": "deny", "translation": "to say not true", "persian": "انکار کردن" },
  { "word": "depart", "translation": "to leave", "persian": "ترک کردن" },
  { "word": "depend", "translation": "to rely on", "persian": "وابسته بودن" },
  { "word": "depict", "translation": "to show in a picture", "persian": "تصویر کردن" },
  { "word": "deploy", "translation": "to use or position", "persian": "استقرار دادن" },
  { "word": "deposit", "translation": "to put money in", "persian": "سپرده گذاری کردن" },
  { "word": "depress", "translation": "to make sad", "persian": "افسرده کردن" },
  { "word": "derive", "translation": "to get from", "persian": "گرفتن از" },
  { "word": "descend", "translation": "to go down", "persian": "پایین آمدن" },
  { "word": "describe", "translation": "to say what something is like", "persian": "توصیف کردن" },
  { "word": "designate", "translation": "to choose for a job", "persian": "منصوب کردن" },
  { "word": "desire", "translation": "strong wish", "persian": "میل، خواسته" },
  { "word": "despite", "translation": "even with", "persian": "با وجود" },
  { "word": "destroy", "translation": "to ruin", "persian": "نابود کردن" },
  { "word": "detect", "translation": "to find out", "persian": "تشخیص دادن" },
  { "word": "deter", "translation": "to discourage", "persian": "بازداشتن" },
  { "word": "detract", "translation": "to take away from", "persian": "کاستن از" },
  { "word": "devote", "translation": "to give time or effort", "persian": "اختصاص دادن" },
  { "word": "dictate", "translation": "to give orders", "persian": "دستور دادن" },
  { "word": "differ", "translation": "to be not the same", "persian": "متفاوت بودن" },
  { "word": "dignity", "translation": "sense of self-respect", "persian": "کرامت، وقار" },
  { "word": "diminish", "translation": "to decrease", "persian": "کاهش دادن" },
  { "word": "disclose", "translation": "to make known", "persian": "افشا کردن" },
  { "word": "discriminate", "translation": "to treat unfairly", "persian": "تبعیض قائل شدن" },
  { "word": "disguise", "translation": "to hide appearance", "persian": "تغییر چهره دادن" },
  { "word": "dismiss", "translation": "to send away, reject", "persian": "رد کردن، اخراج کردن" },
  { "word": "disorder", "translation": "a mess, not organized", "persian": "بی نظمی" },
  { "word": "display", "translation": "to show", "persian": "نمایش دادن" },
  { "word": "dispose", "translation": "to throw away", "persian": "دور انداختن" },
  { "word": "dispute", "translation": "an argument", "persian": "اختلاف" },
  { "word": "disrupt", "translation": "to interrupt", "persian": "مختل کردن" },
  { "word": "dissent", "translation": "disagreement", "persian": "مخالفت" },
  { "word": "distinct", "translation": "clearly different", "persian": "متمایز" },
  { "word": "distinguish", "translation": "to recognize differences", "persian": "تشخیص دادن" },
  { "word": "distort", "translation": "to change the shape", "persian": "تحریف کردن" },
  { "word": "distract", "translation": "to draw attention away", "persian": "حواس پرت کردن" },
  { "word": "distress", "translation": "extreme worry", "persian": "ناراحتی شدید" },
  { "word": "distribute", "translation": "to give out", "persian": "توزیع کردن" },
  { "word": "diverse", "translation": "varied", "persian": "متنوع" },
  { "word": "divert", "translation": "to change direction", "persian": "منحرف کردن" },
  { "word": "divorce", "translation": "legal end of marriage", "persian": "طلاق" },
  { "word": "donate", "translation": "to give for free", "persian": "اهداء کردن" },
  { "word": "double", "translation": "twice as much", "persian": "دو برابر" },
  { "word": "draft", "translation": "first version or military selection", "persian": "پیش‌نویس، سربازگیری" },
  { "word": "drain", "translation": "to remove liquid", "persian": "تخلیه کردن" },
  { "word": "drastic", "translation": "severe, extreme", "persian": "شدید" },
  { "word": "duration", "translation": "length of time", "persian": "مدت زمان" },
  { "word": "dynamic", "translation": "full of energy", "persian": "پویا" },
  { "word": "earn", "translation": "to get for work done", "persian": "درآمد داشتن" },
  { "word": "edit", "translation": "to make changes to text or code", "persian": "ویرایش کردن" },
  { "word": "efficient", "translation": "doing well with little waste", "persian": "کارآمد" },
  { "word": "elaborate", "translation": "detailed, complex", "persian": "مفصل، پیچیده" },
  { "word": "eliminate", "translation": "to remove", "persian": "حذف کردن" }
,

  { "word": "embrace", "translation": "to hug; to accept willingly", "persian": "در آغوش گرفتن، پذیرفتن" },
  { "word": "emerge", "translation": "to come out, appear", "persian": "پدیدار شدن" },
  { "word": "emission", "translation": "release of gas or radiation", "persian": "انتشار (گاز یا اشعه)" },
  { "word": "emphasize", "translation": "to give special importance", "persian": "تاکید کردن" },
  { "word": "empire", "translation": "a group of countries ruled by one", "persian": "امپراتوری" },
  { "word": "empirical", "translation": "based on observation or experience", "persian": "تجربی" },
  { "word": "enable", "translation": "to make possible", "persian": "امکان‌پذیر کردن" },
  { "word": "encounter", "translation": "to meet unexpectedly", "persian": "مواجه شدن" },
  { "word": "endeavor", "translation": "serious effort or attempt", "persian": "تلاش، کوشش" },
  { "word": "endorse", "translation": "to publicly approve or support", "persian": "تایید کردن" },
  { "word": "endure", "translation": "to suffer patiently", "persian": "تحمل کردن" },
  { "word": "enforce", "translation": "to make people obey", "persian": "اجرا کردن" },
  { "word": "engage", "translation": "to participate or attract", "persian": "درگیر شدن، جذب کردن" },
  { "word": "enhance", "translation": "to improve", "persian": "تقویت کردن، بهبود بخشیدن" },
  { "word": "enormous", "translation": "very large", "persian": "عظیم" },
  { "word": "enroll", "translation": "to sign up for", "persian": "ثبت‌نام کردن" },
  { "word": "ensure", "translation": "to make sure", "persian": "اطمینان حاصل کردن" },
  { "word": "enterprise", "translation": "business or company", "persian": "شرکت، بنگاه" },
  { "word": "entire", "translation": "whole, complete", "persian": "تمام، کامل" },
  { "word": "entity", "translation": "something that exists", "persian": "موجودیت، نهاد" },
  { "word": "envision", "translation": "to imagine", "persian": "در ذهن مجسم کردن" },
  { "word": "equivalent", "translation": "equal in value", "persian": "معادل" },
  { "word": "eradicate", "translation": "to destroy completely", "persian": "ریشه‌کن کردن" },
  { "word": "erosion", "translation": "wearing away", "persian": "فرسایش" },
  { "word": "erroneous", "translation": "wrong, incorrect", "persian": "نادرست" },
  { "word": "escalate", "translation": "to increase rapidly", "persian": "تشدید شدن" },
  { "word": "essence", "translation": "the main part", "persian": "ذات، ماهیت" },
  { "word": "establish", "translation": "to set up", "persian": "تاسیس کردن" },
  { "word": "estimate", "translation": "to guess the value", "persian": "تخمین زدن" },
  { "word": "ethics", "translation": "moral principles", "persian": "اخلاقیات" },
  { "word": "evaluate", "translation": "to judge or assess", "persian": "ارزیابی کردن" },
  { "word": "eventually", "translation": "in the end", "persian": "در نهایت" },
  { "word": "evidence", "translation": "proof", "persian": "شواهد" },
  { "word": "evolve", "translation": "to develop gradually", "persian": "تکامل یافتن" },
  { "word": "exceed", "translation": "to be more than", "persian": "فراتر رفتن" },
  { "word": "exception", "translation": "something not included", "persian": "استثنا" },
  { "word": "excess", "translation": "extra amount", "persian": "اضافه، مازاد" },
  { "word": "exclude", "translation": "to leave out", "persian": "حذف کردن" },
  { "word": "exclusive", "translation": "not shared with others", "persian": "انحصاری" },
  { "word": "execute", "translation": "to carry out, put into effect", "persian": "اجرا کردن" },
  { "word": "exempt", "translation": "free from duty", "persian": "معاف" },
  { "word": "exhibit", "translation": "to show publicly", "persian": "نمایش دادن" },
  { "word": "expand", "translation": "to make larger", "persian": "گسترش دادن" },
  { "word": "expel", "translation": "to force out", "persian": "اخراج کردن" },
  { "word": "expertise", "translation": "special skill or knowledge", "persian": "تخصص" },
  { "word": "explicit", "translation": "clear and detailed", "persian": "صریح، واضح" },
  { "word": "exploit", "translation": "to take advantage of", "persian": "بهره‌برداری کردن" },
  { "word": "expose", "translation": "to uncover", "persian": "آشکار کردن" },
  { "word": "express", "translation": "to show thoughts or feelings", "persian": "ابراز کردن" },
  { "word": "extend", "translation": "to make longer", "persian": "گسترش دادن" },
  { "word": "extent", "translation": "degree or amount", "persian": "میزان، گستره" },
  { "word": "extract", "translation": "to remove or take out", "persian": "استخراج کردن" },
  { "word": "fabricate", "translation": "to invent or make up", "persian": "ساختن، جعل کردن" },
  { "word": "facilitate", "translation": "to make easier", "persian": "تسهیل کردن" },
  { "word": "factor", "translation": "something that influences", "persian": "عامل" },
  { "word": "faculty", "translation": "teaching staff or ability", "persian": "هیئت علمی، توانایی" },
  { "word": "federal", "translation": "national (government)", "persian": "فدرال" },
  { "word": "feasible", "translation": "possible to do", "persian": "امکان‌پذیر" },
  { "word": "feature", "translation": "an important part", "persian": "ویژگی" },
  { "word": "federal", "translation": "relating to the central government", "persian": "فدرال" },
  { "word": "feminist", "translation": "supporter of women's rights", "persian": "فمینیست" },
  { "word": "fertile", "translation": "able to produce", "persian": "حاصلخیز" },
  { "word": "finite", "translation": "having limits", "persian": "محدود" },
  { "word": "fluctuate", "translation": "to change often", "persian": "نوسان داشتن" },
  { "word": "focus", "translation": "to concentrate", "persian": "تمرکز کردن" },
  { "word": "forecast", "translation": "to predict", "persian": "پیش‌بینی کردن" },
  { "word": "forge", "translation": "to form or create", "persian": "ایجاد کردن" },
  { "word": "former", "translation": "previous", "persian": "سابق" },
  { "word": "formulate", "translation": "to develop or create", "persian": "فرمول‌بندی کردن" },
  { "word": "forthcoming", "translation": "about to happen", "persian": "در پیش رو" },
  { "word": "fragment", "translation": "a small part", "persian": "قطعه، تکه" },
  { "word": "framework", "translation": "structure for something", "persian": "چارچوب" },
  { "word": "franchise", "translation": "the right to vote or sell a brand", "persian": "حق رای، فرانچایز" },
  { "word": "fund", "translation": "money for a purpose", "persian": "صندوق، سرمایه" },
  { "word": "fundamental", "translation": "basic, essential", "persian": "اساسی" },
  { "word": "fuse", "translation": "to combine, merge", "persian": "ادغام کردن، فیوز" },
  { "word": "gauge", "translation": "to measure or estimate", "persian": "سنجیدن، معیار" },
  { "word": "generate", "translation": "to produce", "persian": "تولید کردن" },
  { "word": "genuine", "translation": "real, authentic", "persian": "اصیل، واقعی" },
  { "word": "govern", "translation": "to rule or control", "persian": "حکومت کردن" },
  { "word": "grant", "translation": "to give officially", "persian": "اعطا کردن" },
  { "word": "guarantee", "translation": "promise to do something", "persian": "تضمین کردن" },
  { "word": "guideline", "translation": "general rule", "persian": "دستورالعمل" },
  { "word": "hence", "translation": "for this reason", "persian": "از این رو" },
  { "word": "hierarchy", "translation": "system of ranking", "persian": "سلسله مراتب" },
  { "word": "highlight", "translation": "to emphasize", "persian": "برجسته کردن" },
  { "word": "hypothesis", "translation": "theory needing proof", "persian": "فرضیه" },
  { "word": "identical", "translation": "exactly the same", "persian": "یکسان" },
  { "word": "ideology", "translation": "system of ideas", "persian": "ایدئولوژی" },
  { "word": "ignite", "translation": "to set on fire", "persian": "آتش زدن" },
  { "word": "illicit", "translation": "illegal", "persian": "غیرقانونی" },
  { "word": "illuminate", "translation": "to light up", "persian": "روشن کردن" },
  { "word": "illustrate", "translation": "to explain with examples", "persian": "شرح دادن با مثال" },
  { "word": "imitate", "translation": "to copy", "persian": "تقلید کردن" },
  { "word": "immerse", "translation": "to cover completely", "persian": "غوطه‌ور شدن" },
  { "word": "impact", "translation": "the effect or influence", "persian": "تاثیر" },
  { "word": "impair", "translation": "to make worse", "persian": "آسیب رساندن" },
  { "word": "implement", "translation": "to carry out", "persian": "اجرا کردن" },
  { "word": "implicate", "translation": "to show involvement", "persian": "دخیل دانستن" },
  { "word": "implicit", "translation": "implied, not stated", "persian": "ضمنی" },
  { "word": "imply", "translation": "to suggest indirectly", "persian": "اشاره داشتن" },
  { "word": "impose", "translation": "to force upon", "persian": "تحمیل کردن" },
  { "word": "incentive", "translation": "reason to do something", "persian": "انگیزه" },
  { "word": "incident", "translation": "event, usually bad", "persian": "حادثه" },
  { "word": "incline", "translation": "to lean or tend toward", "persian": "تمایل داشتن" },
  { "word": "incorporate", "translation": "to include", "persian": "ادغام کردن" },
  { "word": "indicate", "translation": "to show, point out", "persian": "نشان دادن" },
  { "word": "indigenous", "translation": "native to a place", "persian": "بومی" },
  { "word": "induce", "translation": "to cause, bring about", "persian": "وادار کردن" },
  { "word": "inevitable", "translation": "unavoidable", "persian": "اجتناب‌ناپذیر" },
  { "word": "infer", "translation": "to guess based on facts", "persian": "استنباط کردن" },
  { "word": "infinite", "translation": "without end", "persian": "بی‌نهایت" },
  { "word": "inhibit", "translation": "to hold back", "persian": "بازداشتن" },
  { "word": "initiate", "translation": "to start", "persian": "آغاز کردن" },
  { "word": "inject", "translation": "to force into", "persian": "تزریق کردن" },
  { "word": "innovate", "translation": "to create something new", "persian": "نوآوری کردن" },
  { "word": "insight", "translation": "deep understanding", "persian": "بینش" },
  { "word": "inspect", "translation": "to look at carefully", "persian": "بازرسی کردن" },
  { "word": "inspire", "translation": "to motivate", "persian": "الهام بخشیدن" },
  { "word": "install", "translation": "to set up", "persian": "نصب کردن" },
  { "word": "integrate", "translation": "to combine", "persian": "ادغام کردن" },
  { "word": "integrity", "translation": "honesty, moral uprightness", "persian": "درستی، صداقت" },
  { "word": "intense", "translation": "very strong", "persian": "شدید" },
  { "word": "interact", "translation": "to communicate", "persian": "تعامل داشتن" },
  { "word": "interfere", "translation": "to get in the way", "persian": "مداخله کردن" },
  { "word": "interim", "translation": "temporary", "persian": "موقت" },
  { "word": "intervene", "translation": "to get involved", "persian": "مداخله کردن" },
  { "word": "intuitive", "translation": "easy to understand, instinctive", "persian": "شهودی" },
  { "word": "invoke", "translation": "to call upon", "persian": "فراخواندن" },
  { "word": "involve", "translation": "to include, engage", "persian": "درگیر کردن" },
  { "word": "irrelevant", "translation": "not related", "persian": "نامرتبط" },
  { "word": "isolate", "translation": "to set apart", "persian": "جدا کردن" },
  { "word": "issue", "translation": "an important topic or problem", "persian": "مسئله، موضوع" },
  { "word": "jeopardize", "translation": "to put in danger", "persian": "به خطر انداختن" },
  { "word": "legislate", "translation": "to make laws", "persian": "قانون وضع کردن" },
  { "word": "leverage", "translation": "to use something for advantage", "persian": "استفاده بهینه، اهرم" },
  { "word": "likewise", "translation": "in the same way", "persian": "به همین ترتیب" },
  { "word": "locate", "translation": "to find the position", "persian": "مکان‌یابی کردن" },
  { "word": "lucrative", "translation": "profitable", "persian": "سودآور" },
  { "word": "magnitude", "translation": "greatness of size", "persian": "بزرگی، اندازه" },
  { "word": "mainstream", "translation": "accepted by most people", "persian": "جریان اصلی" },
  { "word": "malfunction", "translation": "to fail to work properly", "persian": "خراب شدن" },
  { "word": "manifest", "translation": "to show clearly", "persian": "آشکار کردن" },
  { "word": "manipulate", "translation": "to handle or control", "persian": "دستکاری کردن" },
  { "word": "margin", "translation": "edge or difference", "persian": "حاشیه، تفاوت" },
  { "word": "mediate", "translation": "to help settle differences", "persian": "میانجی‌گری کردن" },
  { "word": "milestone", "translation": "important event", "persian": "نقطه عطف" },
  { "word": "minimal", "translation": "very small in amount", "persian": "حداقلی" },
  { "word": "mobilize", "translation": "to prepare for action", "persian": "بسیج کردن" },
  { "word": "modify", "translation": "to change", "persian": "تغییر دادن" },
  { "word": "monitor", "translation": "to watch, check", "persian": "نظارت کردن" },
  { "word": "mutual", "translation": "shared by both sides", "persian": "متقابل" },
  { "word": "navigate", "translation": "to find the way", "persian": "جهت‌یابی کردن" },
  { "word": "negotiate", "translation": "to discuss for agreement", "persian": "مذاکره کردن" },
  { "word": "notion", "translation": "idea or belief", "persian": "تصور، عقیده" },
  { "word": "notify", "translation": "to inform", "persian": "اطلاع دادن" },
  { "word": "notorious", "translation": "famous for something bad", "persian": "بدنام" },
  { "word": "objective", "translation": "goal or purpose", "persian": "هدف" },
  { "word": "oblige", "translation": "to require", "persian": "ملزم کردن" },
  { "word": "obscure", "translation": "not clear", "persian": "مبهم" },
  { "word": "omit", "translation": "to leave out", "persian": "حذف کردن" },
  { "word": "ongoing", "translation": "continuing", "persian": "در حال انجام" },
  { "word": "optimum", "translation": "best possible", "persian": "بهینه" },
  { "word": "orient", "translation": "to direct toward", "persian": "جهت دادن" },
  { "word": "output", "translation": "amount produced", "persian": "خروجی" },
  { "word": "overlap", "translation": "to cover partly", "persian": "همپوشانی داشتن" },
  { "word": "paradigm", "translation": "model or example", "persian": "الگو" },
  { "word": "parameter", "translation": "limit, boundary", "persian": "پارامتر، محدودیت" },
  { "word": "partake", "translation": "to join in, share", "persian": "شرکت کردن" },
  { "word": "perceive", "translation": "to understand, notice", "persian": "درک کردن" },
  { "word": "periodic", "translation": "happening regularly", "persian": "دوره‌ای" },
  { "word": "persist", "translation": "to continue firmly", "persian": "پافشاری کردن" },
  { "word": "plausible", "translation": "believable", "persian": "محتمل" },
  { "word": "portion", "translation": "part, section", "persian": "بخش، قسمت" },
  { "word": "precede", "translation": "to go before", "persian": "مقدم بودن" },
  { "word": "precise", "translation": "exact, accurate", "persian": "دقیق" },
  { "word": "predominant", "translation": "main, strongest", "persian": "غالب" },
  { "word": "presume", "translation": "to assume", "persian": "فرض کردن" },
  { "word": "prevail", "translation": "to win, overcome", "persian": "غالب شدن" },
  { "word": "primary", "translation": "main, first", "persian": "اصلی" },
  { "word": "principal", "translation": "main, most important", "persian": "اصلی" },
  { "word": "prior", "translation": "before, earlier", "persian": "قبل از" },
  { "word": "proceed", "translation": "to continue", "persian": "ادامه دادن" },
  { "word": "profound", "translation": "deep, great", "persian": "عمیق" },
  { "word": "prohibit", "translation": "to forbid", "persian": "ممنوع کردن" },
  { "word": "project", "translation": "a planned work; to estimate", "persian": "پروژه؛ تخمین زدن" },
  { "word": "prolong", "translation": "to make longer", "persian": "طولانی کردن" },
  { "word": "prominent", "translation": "important, well-known", "persian": "برجسته" },
  { "word": "prompt", "translation": "to encourage or cause", "persian": "تشویق کردن، باعث شدن" },
  { "word": "prone", "translation": "likely to do something", "persian": "مستعد" },
  { "word": "proponent", "translation": "supporter", "persian": "طرفدار" },
  { "word": "prospect", "translation": "chance or possibility", "persian": "چشم‌انداز" },
  { "word": "protocol", "translation": "rules, official procedure", "persian": "پروتکل" },
  { "word": "provoke", "translation": "to anger or stir up", "persian": "تحریک کردن" },
  { "word": "qualitative", "translation": "relating to quality", "persian": "کیفی" },
  { "word": "quantitative", "translation": "relating to quantity", "persian": "کمی" },
  { "word": "quarantine", "translation": "isolation to prevent disease", "persian": "قرنطینه" },
  { "word": "quote", "translation": "to repeat exactly", "persian": "نقل قول کردن" },
  { "word": "rational", "translation": "logical, reasonable", "persian": "منطقی" },
  { "word": "realm", "translation": "area, domain", "persian": "قلمرو" },
  { "word": "refine", "translation": "to make better", "persian": "تصفیه کردن، اصلاح کردن" },
  { "word": "reflect", "translation": "to show, to mirror", "persian": "منعکس کردن" },
  { "word": "regime", "translation": "system of government", "persian": "رژیم" },
  { "word": "reinforce", "translation": "to make stronger", "persian": "تقویت کردن" },
  { "word": "reject", "translation": "to refuse", "persian": "رد کردن" },
  { "word": "reluctant", "translation": "unwilling", "persian": "بی میل" },
  { "word": "remedy", "translation": "solution or cure", "persian": "درمان، چاره" },
  { "word": "render", "translation": "to cause to become", "persian": "موجب شدن" },
  { "word": "reproach", "translation": "to criticize", "persian": "سرزنش کردن" },
  { "word": "resemble", "translation": "to look like", "persian": "شبیه بودن" },
  { "word": "reside", "translation": "to live somewhere", "persian": "سکونت داشتن" },
  { "word": "resilient", "translation": "able to recover quickly", "persian": "تاب‌آور" },
  { "word": "restrict", "translation": "to limit", "persian": "محدود کردن" },
  { "word": "retrieve", "translation": "to get back", "persian": "بازیابی کردن" },
  { "word": "revenue", "translation": "income, especially for government", "persian": "درآمد" },
  { "word": "revise", "translation": "to change or edit", "persian": "اصلاح کردن" },
  { "word": "rigid", "translation": "not flexible", "persian": "سخت، انعطاف‌ناپذیر" },
  { "word": "scenario", "translation": "possible situation", "persian": "سناریو" },
  { "word": "scrutinize", "translation": "to examine closely", "persian": "بررسی دقیق کردن" },
  { "word": "sector", "translation": "a part of an area or economy", "persian": "بخش، قسمت" },
  { "word": "segment", "translation": "part or section", "persian": "بخش، قطعه" },
  { "word": "simulate", "translation": "to imitate", "persian": "شبیه‌سازی کردن" },
  { "word": "sovereign", "translation": "having independent authority", "persian": "مستقل، حاکم" },
  { "word": "specify", "translation": "to state clearly", "persian": "مشخص کردن" },
  { "word": "spontaneous", "translation": "unplanned, natural", "persian": "خودجوش" },
  { "word": "squeeze", "translation": "to press together", "persian": "فشردن" },
  { "word": "stakeholder", "translation": "interested party", "persian": "ذی‌نفع" },
  { "word": "strategy", "translation": "plan of action", "persian": "استراتژی" },
  { "word": "subsequent", "translation": "following, next", "persian": "متوالی" },
  { "word": "subsidy", "translation": "money given to support", "persian": "یارانه" },
  { "word": "substantial", "translation": "large, important", "persian": "قابل توجه" },
  { "word": "substitute", "translation": "to replace", "persian": "جایگزین کردن" },
  { "word": "suppress", "translation": "to stop by force", "persian": "سرکوب کردن" },
  { "word": "sustain", "translation": "to support or keep up", "persian": "حفظ کردن" },
  { "word": "terminate", "translation": "to bring to an end", "persian": "خاتمه دادن" },
  { "word": "threshold", "translation": "starting point", "persian": "آستانه" },
  { "word": "trace", "translation": "to follow or find", "persian": "ردیابی کردن" },
  { "word": "transient", "translation": "temporary, short-lived", "persian": "گذرا" },
  { "word": "transmit", "translation": "to send", "persian": "انتقال دادن" },
  { "word": "trigger", "translation": "to cause to happen", "persian": "باعث شدن" },
  { "word": "ultimate", "translation": "final, best", "persian": "نهایی" },
  { "word": "undermine", "translation": "to weaken", "persian": "تضعیف کردن" },
  { "word": "unify", "translation": "to bring together", "persian": "یکپارچه کردن" },
  { "word": "utilize", "translation": "to use", "persian": "استفاده کردن" },
  { "word": "viable", "translation": "able to work or succeed", "persian": "قابل اجرا" },
  { "word": "virtue", "translation": "moral goodness", "persian": "فضیلت" },
  { "word": "volatile", "translation": "likely to change suddenly", "persian": "ناپایدار" },
  { "word": "widespread", "translation": "happening in many places", "persian": "گسترده" },
  { "word": "withdraw", "translation": "to take back, remove", "persian": "عقب‌نشینی کردن، برداشت کردن" },
  { "word": "withstand", "translation": "to resist, survive", "persian": "مقاومت کردن" },
  { "word": "yield", "translation": "to produce or give way", "persian": "بازده، تسلیم شدن" }


];