const frenchQuestions = [
   
     {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Comment ça va ?",
    "question_pronunciation_ipa": "[kɔmɑ̃ sa va]",
    "question_pronunciation_english": "koh-mahn sah vah",
    "question_pronunciation_persian": "کُمان سا وا؟",
    "question_translation_english": "How are you?",
    "question_translation_persian": "حالت چطوره؟",
    "french_answerformal": "Je vais bien, merci. Et vous ?",
    "answerformal_pronunciation_ipa": "[ʒə vɛ bjɛ̃ mɛʁsi e vu]",
    "answerformal_pronunciation_english": "zhuh veh byan, mehr-see, ay voo?",
    "answerformal_pronunciation_persian": "ژو وِ بیا، مِغسی، اِ وو؟",
    "answerformal_translation_english": "I'm fine, thank you. And you?",
    "answerformal_translation_persian": "خوبم، ممنون. شما چطور؟",
    "french_answerinformal": "Ça va bien, et toi ?",
    "answerinformal_pronunciation_ipa": "[sa va bjɛ̃ e twa]",
    "answerinformal_pronunciation_english": "sah vah byan, ay twa?",
    "answerinformal_pronunciation_persian": "سا وا بیا، اِ توا؟",
    "answerinformal_translation_english": "I'm good, and you?",
    "answerinformal_translation_persian": "خوبم، تو چطوری؟"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quelle heure est-il ?",
    "question_pronunciation_ipa": "[kɛl œʁ ɛ til]",
    "question_pronunciation_english": "kel ur eh teel",
    "question_pronunciation_persian": "کِل اُغ اِ تیل؟",
    "question_translation_english": "What time is it?",
    "question_translation_persian": "ساعت چنده؟",
    "french_answerformal": "Il est quinze heures.",
    "answerformal_pronunciation_ipa": "[il ɛ kɛ̃z œʁ]",
    "answerformal_pronunciation_english": "eel eh kanz ur",
    "answerformal_pronunciation_persian": "ایل اِ کنز اُغ",
    "answerformal_translation_english": "It is three o’clock.",
    "answerformal_translation_persian": "ساعت سه است.",
    "french_answerinformal": "Il est trois heures de l’après-midi.",
    "answerinformal_pronunciation_ipa": "[il ɛ tʁwɑ zœʁ də lapʁɛ midi]",
    "answerinformal_pronunciation_english": "eel eh trwa ur duh lah-preh mee-dee",
    "answerinformal_pronunciation_persian": "ایل اِ تغا اُغ دُ لَپغه میدی",
    "answerinformal_translation_english": "It's three in the afternoon.",
    "answerinformal_translation_persian": "ساعت سه بعدازظهره."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Où sont les toilettes ?",
    "question_pronunciation_ipa": "[u sɔ̃ le twalɛt]",
    "question_pronunciation_english": "oo sohn lay twa-let",
    "question_pronunciation_persian": "او سون له توالت؟",
    "question_translation_english": "Where are the restrooms?",
    "question_translation_persian": "دستشویی‌ها کجاست؟",
    "french_answerformal": "Les toilettes sont au fond à gauche.",
    "answerformal_pronunciation_ipa": "[le twalɛt sɔ̃ o fɔ̃ a ɡoʃ]",
    "answerformal_pronunciation_english": "lay twa-let sohn oh fon ah gosh",
    "answerformal_pronunciation_persian": "له توالت سون او فون آ گوش",
    "answerformal_translation_english": "The restrooms are at the back, on the left.",
    "answerformal_translation_persian": "دستشویی‌ها آخر سالن سمت چپ هستند.",
    "french_answerinformal": "Juste là-bas, à droite.",
    "answerinformal_pronunciation_ipa": "[ʒyst laba a dʁwat]",
    "answerinformal_pronunciation_english": "zhust la-bah, ah drwat",
    "answerinformal_pronunciation_persian": "ژوست لابا، آ دقوات",
    "answerinformal_translation_english": "Just over there, on the right.",
    "answerinformal_translation_persian": "همین‌جا، سمت راست."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Pouvez-vous m'aider ?",
    "question_pronunciation_ipa": "[puve vu mɛde]",
    "question_pronunciation_english": "poo-vay voo meh-day",
    "question_pronunciation_persian": "پووه وو مه‌ده؟",
    "question_translation_english": "Can you help me?",
    "question_translation_persian": "می‌تونید کمکم کنید؟",
    "french_answerformal": "Oui, bien sûr. Que puis-je faire pour vous ?",
    "answerformal_pronunciation_ipa": "[wi bjɛ̃ syʁ kə pɥi ʒə fɛʁ puʁ vu]",
    "answerformal_pronunciation_english": "wee byan sur, kuh pwee-zh fair poor voo?",
    "answerformal_pronunciation_persian": "وی بیا سور، کُ پیژ فغ پوق وو؟",
    "answerformal_translation_english": "Yes, of course. How can I help you?",
    "answerformal_translation_persian": "بله، حتما. چطور می‌تونم کمکتون کنم؟",
    "french_answerinformal": "Pas de problème, dis-moi !",
    "answerinformal_pronunciation_ipa": "[pa də pʁɔblɛm di mwa]",
    "answerinformal_pronunciation_english": "pah duh pro-blem, dee mwah",
    "answerinformal_pronunciation_persian": "پا دُ پقُبلم، دی موا",
    "answerinformal_translation_english": "No problem, tell me!",
    "answerinformal_translation_persian": "مشکلی نیست، بگو!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Combien ça coûte ?",
    "question_pronunciation_ipa": "[kɔ̃bjɛ̃ sa kut]",
    "question_pronunciation_english": "kohm-byen sah koot",
    "question_pronunciation_persian": "کُبیَن سا کوت؟",
    "question_translation_english": "How much does it cost?",
    "question_translation_persian": "قیمتش چنده؟",
    "french_answerformal": "Cela coûte vingt euros.",
    "answerformal_pronunciation_ipa": "[səla kut vɛ̃t øʁo]",
    "answerformal_pronunciation_english": "suh-lah koot vahnt uh-ro",
    "answerformal_pronunciation_persian": "سُلا کوت وَنت اورو",
    "answerformal_translation_english": "It costs twenty euros.",
    "answerformal_translation_persian": "قیمتش بیست یورو است.",
    "french_answerinformal": "C’est pas cher, dix euros.",
    "answerinformal_pronunciation_ipa": "[se pa ʃɛʁ dis øʁo]",
    "answerinformal_pronunciation_english": "seh pah sher, dees uh-ro",
    "answerinformal_pronunciation_persian": "سِه پا شغ، دیس اورو",
    "answerinformal_translation_english": "It's not expensive, ten euros.",
    "answerinformal_translation_persian": "گرون نیست، ده یورو."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Parlez-vous anglais ?",
    "question_pronunciation_ipa": "[paʁle vu ɑ̃ɡlɛ]",
    "question_pronunciation_english": "par-lay voo ong-lay?",
    "question_pronunciation_persian": "پاغله وو آنگله؟",
    "question_translation_english": "Do you speak English?",
    "question_translation_persian": "انگلیسی صحبت می‌کنید؟",
    "french_answerformal": "Oui, je parle un peu anglais.",
    "answerformal_pronunciation_ipa": "[wi ʒə paʁl ɛ̃ pø ɑ̃ɡlɛ]",
    "answerformal_pronunciation_english": "wee zhuh parl uh puh ong-lay",
    "answerformal_pronunciation_persian": "وی ژو پاغل او پو آنگله",
    "answerformal_translation_english": "Yes, I speak a little English.",
    "answerformal_translation_persian": "بله، کمی انگلیسی صحبت می‌کنم.",
    "french_answerinformal": "Non, pas vraiment.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ pa vʁɛmɑ̃]",
    "answerinformal_pronunciation_english": "noh, pah vray-mahn",
    "answerinformal_pronunciation_persian": "نُون، پا وغما",
    "answerinformal_translation_english": "No, not really.",
    "answerinformal_translation_persian": "نه، واقعا نه."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Où est la station de métro la plus proche ?",
    "question_pronunciation_ipa": "[u ɛ la stasjɔ̃ də metro la ply pʁɔʃ]",
    "question_pronunciation_english": "oo eh lah stah-syon duh meh-tro lah ploo prosh",
    "question_pronunciation_persian": "او اِ لا ستاسیون دُ متقو لا پلوی پروش؟",
    "question_translation_english": "Where is the nearest metro station?",
    "question_translation_persian": "نزدیک‌ترین ایستگاه مترو کجاست؟",
    "french_answerformal": "La station est à deux rues d’ici.",
    "answerformal_pronunciation_ipa": "[la stasjɔ̃ ɛ a dø ʁy disi]",
    "answerformal_pronunciation_english": "lah stah-syon eh ah duh rue dee-see",
    "answerformal_pronunciation_persian": "لا ستاسیون اِ آ دو غو دیسی",
    "answerformal_translation_english": "The station is two streets away from here.",
    "answerformal_translation_persian": "ایستگاه دو خیابان با اینجا فاصله دارد.",
    "french_answerinformal": "C’est juste là-bas au coin.",
    "answerinformal_pronunciation_ipa": "[se ʒyst laba o kwɛ̃]",
    "answerinformal_pronunciation_english": "seh zhust la-bah oh kwen",
    "answerinformal_pronunciation_persian": "سه ژوست لابا او کوئن",
    "answerinformal_translation_english": "It's just over there, on the corner.",
    "answerinformal_translation_persian": "همون‌جا، سر کوچه."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Puis-je avoir l’addition, s’il vous plaît ?",
    "question_pronunciation_ipa": "[pɥi ʒə avwaʁ ladisjɔ̃ sil vu plɛ]",
    "question_pronunciation_english": "pwee zhuh ah-vwar lah-dee-syon, seel voo pleh",
    "question_pronunciation_persian": "پوی ژُ آوواغ لادیسیون، سیل وو پله؟",
    "question_translation_english": "May I have the bill, please?",
    "question_translation_persian": "می‌تونم صورت‌حساب رو داشته باشم؟",
    "french_answerformal": "Bien sûr, je vous l’apporte tout de suite.",
    "answerformal_pronunciation_ipa": "[bjɛ̃ syʁ ʒə vu lapɔʁt tu də sɥit]",
    "answerformal_pronunciation_english": "byan sur, zhuh voo lah-port too duh sweet",
    "answerformal_pronunciation_persian": "بیا سور، ژو وو لاپوق تو دُ سویت",
    "answerformal_translation_english": "Of course, I’ll bring it to you right away.",
    "answerformal_translation_persian": "حتما، الان براتون میارم.",
    "french_answerinformal": "Pas de souci, j’arrive !",
    "answerinformal_pronunciation_ipa": "[pa də susi ʒaʁiv]",
    "answerinformal_pronunciation_english": "pah duh soo-see, zha-reev",
    "answerinformal_pronunciation_persian": "پا دُ سوسی، ژغیو!",
    "answerinformal_translation_english": "No worries, I’m coming!",
    "answerinformal_translation_persian": "الان میارم برات."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Vous acceptez la carte bancaire ?",
    "question_pronunciation_ipa": "[vu aksɛpte la kaʁt bɑ̃kɛʁ]",
    "question_pronunciation_english": "voo ak-sep-tay lah kart bon-kehr?",
    "question_pronunciation_persian": "وو اکسپته لا کارت بانکغ؟",
    "question_translation_english": "Do you accept bank cards?",
    "question_translation_persian": "کارت بانکی قبول می‌کنید؟",
    "french_answerformal": "Oui, toutes les cartes sont acceptées.",
    "answerformal_pronunciation_ipa": "[wi tut le kaʁt sɔ̃t aksɛpte]",
    "answerformal_pronunciation_english": "wee toot lay kart sont ak-sep-tay",
    "answerformal_pronunciation_persian": "وی توت له کارت سون اکسپته",
    "answerformal_translation_english": "Yes, all cards are accepted.",
    "answerformal_translation_persian": "بله، همه کارت‌ها قبول می‌شوند.",
    "french_answerinformal": "Non, désolé, seulement en espèces.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ dezole sœlmɑ̃ ɑ̃ ɛspɛs]",
    "answerinformal_pronunciation_english": "noh, day-zoh-lay, seul-mahn on es-pess",
    "answerinformal_pronunciation_persian": "نون دِزوله، سُلمان اِن اِسپِس",
    "answerinformal_translation_english": "No, sorry, only cash.",
    "answerinformal_translation_persian": "نه، متاسفم، فقط نقدی."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Avez-vous un menu en anglais ?",
    "question_pronunciation_ipa": "[ave vu ɛ̃ mənɥ ɑ̃ ɑ̃ɡlɛ]",
    "question_pronunciation_english": "ah-vay voo uh muh-new on ong-lay?",
    "question_pronunciation_persian": "اوِ وو اَن منو آن آنگله؟",
    "question_translation_english": "Do you have a menu in English?",
    "question_translation_persian": "منوی انگلیسی دارید؟",
    "french_answerformal": "Oui, voici le menu en anglais.",
    "answerformal_pronunciation_ipa": "[wi vwazi lə mənɥ ɑ̃ ɑ̃ɡlɛ]",
    "answerformal_pronunciation_english": "wee vwazee luh muh-new on ong-lay",
    "answerformal_pronunciation_persian": "وی ووازی لُ منو آن آنگله",
    "answerformal_translation_english": "Yes, here is the menu in English.",
    "answerformal_translation_persian": "بله، این هم منوی انگلیسی.",
    "french_answerinformal": "Désolé, seulement en français.",
    "answerinformal_pronunciation_ipa": "[dezole sœlmɑ̃ ɑ̃ fʁɑ̃sɛ]",
    "answerinformal_pronunciation_english": "day-zoh-lay, seul-mahn on fran-say",
    "answerinformal_pronunciation_persian": "دِزوله، سُلمان اَن فرانسِ",
    "answerinformal_translation_english": "Sorry, only in French.",
    "answerinformal_translation_persian": "متاسفم، فقط به فرانسوی داریم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Où puis-je trouver un taxi ?",
    "question_pronunciation_ipa": "[u pɥi ʒə tʁuve ɛ̃ taksi]",
    "question_pronunciation_english": "oo pwee zhuh troo-vay uh taxi?",
    "question_pronunciation_persian": "او پوی ژ ترووه اَن تاکسی؟",
    "question_translation_english": "Where can I find a taxi?",
    "question_translation_persian": "کجا می‌تونم تاکسی پیدا کنم؟",
    "french_answerformal": "Il y a une station de taxis devant la gare.",
    "answerformal_pronunciation_ipa": "[il j‿a yn stasjɔ̃ də taksi dəvɑ̃ la ɡaʁ]",
    "answerformal_pronunciation_english": "eel ya uhn stah-syon duh taxi duh-vahn lah gar",
    "answerformal_pronunciation_persian": "ایل یا اون ستاسیون دُ تاکسی دُوان لا گغ",
    "answerformal_translation_english": "There’s a taxi stand in front of the station.",
    "answerformal_translation_persian": "یک ایستگاه تاکسی جلوی ایستگاه قطار هست.",
    "french_answerinformal": "Vous pouvez appeler un taxi avec votre téléphone.",
    "answerinformal_pronunciation_ipa": "[vu puve aplɛ ɛ̃ taksi avɛk votʁ tɛlɛfɔn]",
    "answerinformal_pronunciation_english": "voo poo-vay ah-play uh taxi avek votr telephone",
    "answerinformal_pronunciation_persian": "وو پُوه اوپله اَن تاکسی اوِک وُتغ تلفون",
    "answerinformal_translation_english": "You can call a taxi with your phone.",
    "answerinformal_translation_persian": "می‌تونید با گوشیتون تاکسی خبر کنید."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Comment tu t’appelles ?",
    "question_pronunciation_ipa": "[kɔmɑ̃ ty tapɛl]",
    "question_pronunciation_english": "koh-mahn tew tah-pell?",
    "question_pronunciation_persian": "کُمان تو تَپل؟",
    "question_translation_english": "What’s your name?",
    "question_translation_persian": "اسمت چیه؟",
    "french_answerformal": "Je m’appelle Pierre.",
    "answerformal_pronunciation_ipa": "[ʒə mapɛl pjɛʁ]",
    "answerformal_pronunciation_english": "zhuh mah-pell pyair",
    "answerformal_pronunciation_persian": "ژو مَپل پیغ",
    "answerformal_translation_english": "My name is Pierre.",
    "answerformal_translation_persian": "اسم من پی‌یر است.",
    "french_answerinformal": "Moi, c’est Marie.",
    "answerinformal_pronunciation_ipa": "[mwa sɛ maʁi]",
    "answerinformal_pronunciation_english": "mwah seh mah-ree",
    "answerinformal_pronunciation_persian": "موا، سه ماری",
    "answerinformal_translation_english": "Me, I’m Marie.",
    "answerinformal_translation_persian": "من، ماری هستم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel âge as-tu ?",
    "question_pronunciation_ipa": "[kɛl aʒ a ty]",
    "question_pronunciation_english": "kel ahzh ah tew?",
    "question_pronunciation_persian": "کِل آز آ تو؟",
    "question_translation_english": "How old are you?",
    "question_translation_persian": "چند سالته؟",
    "french_answerformal": "J’ai vingt-sept ans.",
    "answerformal_pronunciation_ipa": "[ʒe vɛ̃ sɛt ɑ̃]",
    "answerformal_pronunciation_english": "zhay van-set ahn",
    "answerformal_pronunciation_persian": "ژه وَن سِت آن",
    "answerformal_translation_english": "I’m twenty-seven years old.",
    "answerformal_translation_persian": "بیست و هفت سالمه.",
    "french_answerinformal": "J’ai dix-neuf ans.",
    "answerinformal_pronunciation_ipa": "[ʒe diz nœf ɑ̃]",
    "answerinformal_pronunciation_english": "zhay deez-nuf ahn",
    "answerinformal_pronunciation_persian": "ژه دیز نُف آن",
    "answerinformal_translation_english": "I’m nineteen.",
    "answerinformal_translation_persian": "نوزده سالمه."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu viens d’où ?",
    "question_pronunciation_ipa": "[ty vjɛ̃ du]",
    "question_pronunciation_english": "tew vyen doo?",
    "question_pronunciation_persian": "تو ویَن دو؟",
    "question_translation_english": "Where are you from?",
    "question_translation_persian": "اهل کجایی؟",
    "french_answerformal": "Je viens de France.",
    "answerformal_pronunciation_ipa": "[ʒə vjɛ̃ də fʁɑ̃s]",
    "answerformal_pronunciation_english": "zhuh vyen duh frahnss",
    "answerformal_pronunciation_persian": "ژو ویَن دُ فرانس",
    "answerformal_translation_english": "I’m from France.",
    "answerformal_translation_persian": "من اهل فرانسه هستم.",
    "french_answerinformal": "Moi, je viens d’Italie.",
    "answerinformal_pronunciation_ipa": "[mwa ʒə vjɛ̃ ditali]",
    "answerinformal_pronunciation_english": "mwah zhuh vyen deetah-lee",
    "answerinformal_pronunciation_persian": "موا ژو ویَن دیتالی",
    "answerinformal_translation_english": "Me, I’m from Italy.",
    "answerinformal_translation_persian": "من اهل ایتالیا هستم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel est ton métier ?",
    "question_pronunciation_ipa": "[kɛl ɛ tɔ̃ metje]",
    "question_pronunciation_english": "kel eh ton meh-tyay?",
    "question_pronunciation_persian": "کل اِ تون مِتیه؟",
    "question_translation_english": "What is your job?",
    "question_translation_persian": "شغلت چیه؟",
    "french_answerformal": "Je suis ingénieur.",
    "answerformal_pronunciation_ipa": "[ʒə sɥi ɛ̃ʒenjœʁ]",
    "answerformal_pronunciation_english": "zhuh swee an-zhay-nyur",
    "answerformal_pronunciation_persian": "ژو سوی اَنژِنیوق",
    "answerformal_translation_english": "I’m an engineer.",
    "answerformal_translation_persian": "مهندس هستم.",
    "french_answerinformal": "Je travaille dans une boulangerie.",
    "answerinformal_pronunciation_ipa": "[ʒə tʁavaj dɑ̃z yn bulɑ̃ʒəʁi]",
    "answerinformal_pronunciation_english": "zhuh tra-vai donz un boo-lan-zhuh-ree",
    "answerinformal_pronunciation_persian": "ژو تغاوای دانز یون بولانژغی",
    "answerinformal_translation_english": "I work in a bakery.",
    "answerinformal_translation_persian": "تو نانوایی کار می‌کنم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel est ton plat préféré ?",
    "question_pronunciation_ipa": "[kɛl ɛ tɔ̃ pla pʁefeʁe]",
    "question_pronunciation_english": "kel eh ton plah preh-feh-ray?",
    "question_pronunciation_persian": "کل اِ تون پلا پقِفهغه؟",
    "question_translation_english": "What’s your favorite dish?",
    "question_translation_persian": "غذای مورد علاقه‌ات چیه؟",
    "french_answerformal": "J’adore le couscous.",
    "answerformal_pronunciation_ipa": "[ʒadɔʁ lə kuskus]",
    "answerformal_pronunciation_english": "zhah-dor luh koos-koos",
    "answerformal_pronunciation_persian": "ژادوغ لُ کوسکوس",
    "answerformal_translation_english": "I love couscous.",
    "answerformal_translation_persian": "کوسکوس دوست دارم.",
    "french_answerinformal": "Pizza, c’est trop bon !",
    "answerinformal_pronunciation_ipa": "[pidza sɛ tʁo bɔ̃]",
    "answerinformal_pronunciation_english": "peet-zah, seh troh bon!",
    "answerinformal_pronunciation_persian": "پیتزا، سِه ترو بُن!",
    "answerinformal_translation_english": "Pizza, it’s so good!",
    "answerinformal_translation_persian": "پیتزا، خیلی خوشمزه‌ست!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel est ton genre de musique préféré ?",
    "question_pronunciation_ipa": "[kɛl ɛ tɔ̃ ʒɑ̃ʁ də myzik pʁefeʁe]",
    "question_pronunciation_english": "kel eh ton zhahr duh meu-zeek preh-feh-ray?",
    "question_pronunciation_persian": "کل اِ تون ژاغ دُ موزیک پقِفهغه؟",
    "question_translation_english": "What’s your favorite kind of music?",
    "question_translation_persian": "چه نوع موسیقی دوست داری؟",
    "french_answerformal": "J’aime la musique classique.",
    "answerformal_pronunciation_ipa": "[ʒɛm la myzik klasik]",
    "answerformal_pronunciation_english": "zhem lah meu-zeek klah-seek",
    "answerformal_pronunciation_persian": "ژم لا موزیک کلاسیك",
    "answerformal_translation_english": "I like classical music.",
    "answerformal_translation_persian": "موسیقی کلاسیک دوست دارم.",
    "french_answerinformal": "Le rap, c’est mon style !",
    "answerinformal_pronunciation_ipa": "[lə ʁap sɛ mɔ̃ stil]",
    "answerinformal_pronunciation_english": "luh rap, seh mon steel!",
    "answerinformal_pronunciation_persian": "لُ غپ، سِه مون استیل!",
    "answerinformal_translation_english": "Rap, that’s my style!",
    "answerinformal_translation_persian": "رپ، سبک منه!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel est ton passe-temps préféré ?",
    "question_pronunciation_ipa": "[kɛl ɛ tɔ̃ pas tɑ̃ pʁefeʁe]",
    "question_pronunciation_english": "kel eh ton pahs-tahn preh-feh-ray?",
    "question_pronunciation_persian": "کل اِ تون پَس تام پقِفهغه؟",
    "question_translation_english": "What’s your favorite hobby?",
    "question_translation_persian": "سرگرمی مورد علاقه‌ات چیه؟",
    "french_answerformal": "Je fais de la peinture pendant mon temps libre.",
    "answerformal_pronunciation_ipa": "[ʒə fɛ də la pɛ̃tyʁ pɑ̃dɑ̃ mɔ̃ tɑ̃ libʁ]",
    "answerformal_pronunciation_english": "zhuh feh duh lah pan-teer pahn-dahn mon tan leeb",
    "answerformal_pronunciation_persian": "ژو فه دو لا پنتیوغ پندان مون تان لیبغ",
    "answerformal_translation_english": "I paint in my free time.",
    "answerformal_translation_persian": "در وقت آزادم نقاشی می‌کشم.",
    "french_answerinformal": "J’adore jouer aux jeux vidéo.",
    "answerinformal_pronunciation_ipa": "[ʒadɔʁ ʒwe o ʒø video]",
    "answerinformal_pronunciation_english": "zhah-dor zhway oh zhuh vee-day-oh",
    "answerinformal_pronunciation_persian": "ژادوغ ژوه او ژو ویدئو",
    "answerinformal_translation_english": "I love playing video games.",
    "answerinformal_translation_persian": "بازی ویدیویی دوست دارم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as des frères ou des sœurs ?",
    "question_pronunciation_ipa": "[ty a de fʁɛʁ u de sœʁ]",
    "question_pronunciation_english": "tew ah day frehr oo day suhr?",
    "question_pronunciation_persian": "تو آ دِ فغغ او دِ سوغ؟",
    "question_translation_english": "Do you have any brothers or sisters?",
    "question_translation_persian": "خواهر یا برادر داری؟",
    "french_answerformal": "Oui, j’ai un frère et une sœur.",
    "answerformal_pronunciation_ipa": "[wi ʒe ɛ̃ fʁɛʁ e yn sœʁ]",
    "answerformal_pronunciation_english": "wee zhay uh frehr ay uhn suhr",
    "answerformal_pronunciation_persian": "وی ژه اَن فغغ اِ یون سوغ",
    "answerformal_translation_english": "Yes, I have a brother and a sister.",
    "answerformal_translation_persian": "بله، یک برادر و یک خواهر دارم.",
    "french_answerinformal": "Non, je suis enfant unique.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ ʒə sɥi ɑ̃fɑ̃ ynik]",
    "answerinformal_pronunciation_english": "noh, zhuh swee an-fahn u-neek",
    "answerinformal_pronunciation_persian": "نو ژو سوی انفان یونیک",
    "answerinformal_translation_english": "No, I’m an only child.",
    "answerinformal_translation_persian": "نه، تک فرزندم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quelle est ta couleur préférée ?",
    "question_pronunciation_ipa": "[kɛl ɛ ta kulœʁ pʁefeʁe]",
    "question_pronunciation_english": "kel eh tah koo-luhr preh-feh-ray?",
    "question_pronunciation_persian": "کل اِ تا کولغ پِغِفهغه؟",
    "question_translation_english": "What’s your favorite color?",
    "question_translation_persian": "رنگ مورد علاقه‌ات چیه؟",
    "french_answerformal": "Ma couleur préférée est le bleu.",
    "answerformal_pronunciation_ipa": "[ma kulœʁ pʁefeʁe ɛ lə blø]",
    "answerformal_pronunciation_english": "mah koo-luhr preh-feh-ray eh luh bluh",
    "answerformal_pronunciation_persian": "ما کولغ پِغِفهغه اِ لُ بلو",
    "answerformal_translation_english": "My favorite color is blue.",
    "answerformal_translation_persian": "رنگ مورد علاقه من آبی است.",
    "french_answerinformal": "Le vert, c’est top !",
    "answerinformal_pronunciation_ipa": "[lə vɛʁ sɛ tɔp]",
    "answerinformal_pronunciation_english": "luh ver, seh top!",
    "answerinformal_pronunciation_persian": "لُ وِغ، سه توپ!",
    "answerinformal_translation_english": "Green, it's the best!",
    "answerinformal_translation_persian": "سبز، خیلی عالیه!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu habites où ?",
    "question_pronunciation_ipa": "[ty abit u]",
    "question_pronunciation_english": "tew ah-beet oo?",
    "question_pronunciation_persian": "تو ابیت او؟",
    "question_translation_english": "Where do you live?",
    "question_translation_persian": "کجا زندگی می‌کنی؟",
    "french_answerformal": "J’habite à Paris.",
    "answerformal_pronunciation_ipa": "[ʒabit a paʁi]",
    "answerformal_pronunciation_english": "zhah-beet ah pah-ree",
    "answerformal_pronunciation_persian": "ژابیت آ پاغی",
    "answerformal_translation_english": "I live in Paris.",
    "answerformal_translation_persian": "در پاریس زندگی می‌کنم.",
    "french_answerinformal": "Dans le sud de la France.",
    "answerinformal_pronunciation_ipa": "[dɑ̃ lə syd də la fʁɑ̃s]",
    "answerinformal_pronunciation_english": "don luh sud duh lah frahnss",
    "answerinformal_pronunciation_persian": "دان لُ سود دُ لا فرانس",
    "answerinformal_translation_english": "In the south of France.",
    "answerinformal_translation_persian": "جنوب فرانسه زندگی می‌کنم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu parles quelles langues ?",
    "question_pronunciation_ipa": "[ty paʁl kɛl lɑ̃ɡ]",
    "question_pronunciation_english": "tew parl kel long?",
    "question_pronunciation_persian": "تو پاغل کِل لانگ؟",
    "question_translation_english": "What languages do you speak?",
    "question_translation_persian": "چه زبان‌هایی صحبت می‌کنی؟",
    "french_answerformal": "Je parle français et anglais.",
    "answerformal_pronunciation_ipa": "[ʒə paʁl fʁɑ̃sɛ e ɑ̃ɡlɛ]",
    "answerformal_pronunciation_english": "zhuh parl frahn-say ay ong-lay",
    "answerformal_pronunciation_persian": "ژو پاغل فرانسِ اِ آنگله",
    "answerformal_translation_english": "I speak French and English.",
    "answerformal_translation_persian": "فرانسوی و انگلیسی صحبت می‌کنم.",
    "french_answerinformal": "Un peu d’espagnol aussi.",
    "answerinformal_pronunciation_ipa": "[ɛ̃ pø dɛspaɲɔl osi]",
    "answerinformal_pronunciation_english": "uhn puh deh-spa-nyol oh-see",
    "answerinformal_pronunciation_persian": "اَن پو دِسپانیول اوسی",
    "answerinformal_translation_english": "A bit of Spanish too.",
    "answerinformal_translation_persian": "یه کم اسپانیایی هم بلدم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Qu’est-ce que tu fais ce week-end ?",
    "question_pronunciation_ipa": "[kɛs kə ty fɛ sə wik ɛnd]",
    "question_pronunciation_english": "kes kuh tew feh suh week-end?",
    "question_pronunciation_persian": "کِس کُ تو فه سو ویک‌اِند؟",
    "question_translation_english": "What are you doing this weekend?",
    "question_translation_persian": "آخر هفته چی کار می‌کنی؟",
    "french_answerformal": "Je vais rendre visite à ma famille.",
    "answerformal_pronunciation_ipa": "[ʒə vɛ ʁɑ̃dʁ vizit a ma famij]",
    "answerformal_pronunciation_english": "zhuh veh ron-druh vee-zeet ah mah fah-meey",
    "answerformal_pronunciation_persian": "ژو وِ غاندغ ویزیت آ ما فامی",
    "answerformal_translation_english": "I’m going to visit my family.",
    "answerformal_translation_persian": "میرم دیدن خانواده‌ام.",
    "french_answerinformal": "Je vais à la plage avec des amis.",
    "answerinformal_pronunciation_ipa": "[ʒə vɛ a la plaʒ avɛk dez ami]",
    "answerinformal_pronunciation_english": "zhuh veh ah lah plazh avek dez a-mee",
    "answerinformal_pronunciation_persian": "ژو وِ آ لا پلاژ اوِک دِز آمی",
    "answerinformal_translation_english": "I’m going to the beach with friends.",
    "answerinformal_translation_persian": "با دوستام میرم ساحل."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Comment ça se passe au travail ?",
    "question_pronunciation_ipa": "[kɔmɑ̃ sa sə pas o tʁavaj]",
    "question_pronunciation_english": "koh-mahn sah suh pass oh tra-vai?",
    "question_pronunciation_persian": "کُمان سا سُ پاس او تغاوی؟",
    "question_translation_english": "How’s work going?",
    "question_translation_persian": "کارت چطور پیش میره؟",
    "french_answerformal": "Tout se passe bien, merci.",
    "answerformal_pronunciation_ipa": "[tu sə pas bjɛ̃ mɛʁsi]",
    "answerformal_pronunciation_english": "too suh pass byan, mehr-see",
    "answerformal_pronunciation_persian": "تو سُ پاس بیا، مِغسی",
    "answerformal_translation_english": "Everything’s going well, thank you.",
    "answerformal_translation_persian": "همه چیز خوب پیش میره، ممنون.",
    "french_answerinformal": "C’est un peu stressant en ce moment.",
    "answerinformal_pronunciation_ipa": "[sɛ tɛ̃ pø stʁɛsɑ̃ ɑ̃ sə mɔmɑ̃]",
    "answerinformal_pronunciation_english": "seh tun puh stress-on on suh moh-mahn",
    "answerinformal_pronunciation_persian": "سه تن پو ستغسان آن سُ مومان",
    "answerinformal_translation_english": "It’s a bit stressful at the moment.",
    "answerinformal_translation_persian": "یه کم استرس دارم این روزا."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu te sens bien ?",
    "question_pronunciation_ipa": "[ty tə sɑ̃ bjɛ̃]",
    "question_pronunciation_english": "tew tuh sahn byan?",
    "question_pronunciation_persian": "تو ت سان بیا؟",
    "question_translation_english": "Do you feel well?",
    "question_translation_persian": "حالت خوبه؟",
    "french_answerformal": "Oui, je me sens très bien.",
    "answerformal_pronunciation_ipa": "[wi ʒə mə sɑ̃ tʁɛ bjɛ̃]",
    "answerformal_pronunciation_english": "wee zhuh muh sahn tray byan",
    "answerformal_pronunciation_persian": "وی ژو مِ سان تغه بیا",
    "answerformal_translation_english": "Yes, I feel very well.",
    "answerformal_translation_persian": "بله، خیلی حالم خوبه.",
    "french_answerinformal": "Pas trop, j’ai un peu mal à la tête.",
    "answerinformal_pronunciation_ipa": "[pa tʁo ʒe ɛ̃ pø mal a la tɛt]",
    "answerinformal_pronunciation_english": "pah tro, zhay uh puh mal ah lah tet",
    "answerinformal_pronunciation_persian": "پا ترو، ژه اَن پو مال آ لا تت",
    "answerinformal_translation_english": "Not really, I have a bit of a headache.",
    "answerinformal_translation_persian": "نه خیلی، یکم سردرد دارم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel temps fait-il aujourd’hui ?",
    "question_pronunciation_ipa": "[kɛl tɑ̃ fɛ til oʒuʁdɥi]",
    "question_pronunciation_english": "kel tan feh teel oh-zhoor-dwee?",
    "question_pronunciation_persian": "کِل تان فه تیل اوژوغدویی؟",
    "question_translation_english": "What’s the weather like today?",
    "question_translation_persian": "هوا امروز چطوره؟",
    "french_answerformal": "Il fait beau et ensoleillé.",
    "answerformal_pronunciation_ipa": "[il fɛ bo e ɑ̃sɔlɛje]",
    "answerformal_pronunciation_english": "eel feh boh ay an-so-lay-yay",
    "answerformal_pronunciation_persian": "ایل فه بو اِ آنسولهیه",
    "answerformal_translation_english": "It’s nice and sunny.",
    "answerformal_translation_persian": "هوا خوبه و آفتابیه.",
    "french_answerinformal": "Il pleut beaucoup aujourd’hui.",
    "answerinformal_pronunciation_ipa": "[il plø buku oʒuʁdɥi]",
    "answerinformal_pronunciation_english": "eel pleuh boo-koo oh-zhoor-dwee",
    "answerinformal_pronunciation_persian": "ایل پلو بوکو اوژوغدویی",
    "answerinformal_translation_english": "It’s raining a lot today.",
    "answerinformal_translation_persian": "امروز خیلی بارون میاد."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as un numéro de téléphone ?",
    "question_pronunciation_ipa": "[ty a ɛ̃ nymeʁo də telefɔn]",
    "question_pronunciation_english": "tew ah uh new-may-ro duh tell-ay-fon?",
    "question_pronunciation_persian": "تو ا نمرود تلفن؟",
    "question_translation_english": "Do you have a phone number?",
    "question_translation_persian": "شماره تلفن داری؟",
    "french_answerformal": "Oui, c’est le 06 12 34 56 78.",
    "answerformal_pronunciation_ipa": "[wi sɛ lə zero sis dooz twa kat sɛ sank swa set wit]",
    "answerformal_pronunciation_english": "wee seh luh zero seess dooz twa kat seh sank swah set wheat",
    "answerformal_pronunciation_persian": "وی سه لُ زرو سیس دوز توا کات سه سانک سوا ست ویت",
    "answerformal_translation_english": "Yes, it’s 06 12 34 56 78.",
    "answerformal_translation_persian": "بله، این شماره‌مه: ۰۶۱۲۳۴۵۶۷۸",
    "french_answerinformal": "Non, désolé, je préfère pas donner.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ dezole ʒə pʁefeʁ pa dɔne]",
    "answerinformal_pronunciation_english": "noh day-zoh-lay zhuh preh-fehr pah doh-nay",
    "answerinformal_pronunciation_persian": "نو دِزوله ژو پِغِفهغ پا دُنه",
    "answerinformal_translation_english": "No, sorry, I prefer not to give it.",
    "answerinformal_translation_persian": "نه، متاسفم، نمی‌خوام بدم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as un e-mail ?",
    "question_pronunciation_ipa": "[ty a ɛ̃ imel]",
    "question_pronunciation_english": "tew ah uh ee-mail?",
    "question_pronunciation_persian": "تو ا ن ایمیل؟",
    "question_translation_english": "Do you have an email address?",
    "question_translation_persian": "ایمیل داری؟",
    "french_answerformal": "Oui, c’est pierre@gmail.com.",
    "answerformal_pronunciation_ipa": "[wi sɛ pjɛʁ arobaz ʒi ɛm ɛl pɔ̃ kom]",
    "answerformal_pronunciation_english": "wee seh pyair ah-ro-baz zhee em el pon kom",
    "answerformal_pronunciation_persian": "وی سه پیغ آغباز ژی اِم اِل پون کوم",
    "answerformal_translation_english": "Yes, it’s pierre@gmail.com.",
    "answerformal_translation_persian": "بله، ایمیلم اینه: pierre@gmail.com",
    "french_answerinformal": "Non, je préfère WhatsApp.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ ʒə pʁefeʁ whatsap]",
    "answerinformal_pronunciation_english": "noh zhuh preh-fehr WhatsApp",
    "answerinformal_pronunciation_persian": "نو ژو پِغِفهغ واتساپ",
    "answerinformal_translation_english": "No, I prefer WhatsApp.",
    "answerinformal_translation_persian": "نه، ترجیح می‌دم واتساپ باشه."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Où est-ce que je peux acheter ça ?",
    "question_pronunciation_ipa": "[u ɛs kə ʒə pø aʃte sa]",
    "question_pronunciation_english": "oo es kuh zhuh puh ash-tay sah?",
    "question_pronunciation_persian": "او اس ک ژ پ اشته سا؟",
    "question_translation_english": "Where can I buy this?",
    "question_translation_persian": "از کجا می‌تونم این رو بخرم؟",
    "french_answerformal": "Vous pouvez l’acheter au supermarché.",
    "answerformal_pronunciation_ipa": "[vu puve laʃte o sypɛʁmaʁʃe]",
    "answerformal_pronunciation_english": "voo poo-vay lah-sh-tay oh sue-pair-mar-shay",
    "answerformal_pronunciation_persian": "وو پُوه لاشته او سوپغماغشه",
    "answerformal_translation_english": "You can buy it at the supermarket.",
    "answerformal_translation_persian": "می‌تونید از سوپرمارکت بخرید.",
    "french_answerinformal": "Sur Internet, c’est plus simple.",
    "answerinformal_pronunciation_ipa": "[syʁ ɛ̃tɛʁnɛt sɛ ply sɛ̃pl]",
    "answerinformal_pronunciation_english": "syr an-ter-net, seh ploo sampl",
    "answerinformal_pronunciation_persian": "سور انتغنت سه پلو سنپل",
    "answerinformal_translation_english": "Online, it’s easier.",
    "answerinformal_translation_persian": "آنلاین راحت‌تره."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "C’est combien pour une nuit ?",
    "question_pronunciation_ipa": "[sɛ kɔ̃bjɛ̃ puʁ yn nɥi]",
    "question_pronunciation_english": "seh kohm-byen poor uhn nwee?",
    "question_pronunciation_persian": "سه کمبیَن پوق یون نویی؟",
    "question_translation_english": "How much is it for one night?",
    "question_translation_persian": "شبی چند درمیاد؟",
    "french_answerformal": "C’est 80 euros la nuit.",
    "answerformal_pronunciation_ipa": "[sɛ katʁə vɛ̃ œʁo la nɥi]",
    "answerformal_pronunciation_english": "seh kat-ruh ven uh-roh lah nwee",
    "answerformal_pronunciation_persian": "سه کتغه وَن اورو لا نویی",
    "answerformal_translation_english": "It's 80 euros per night.",
    "answerformal_translation_persian": "هر شب ۸۰ یورو است.",
    "french_answerinformal": "Ça dépend de la saison.",
    "answerinformal_pronunciation_ipa": "[sa depɑ̃ də la sɛzɔ̃]",
    "answerinformal_pronunciation_english": "sah day-pahn duh lah seh-zon",
    "answerinformal_pronunciation_persian": "سا دِپان دُ لا سزون",
    "answerinformal_translation_english": "It depends on the season.",
    "answerinformal_translation_persian": "بسته به فصل داره."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Est-ce que tu peux m’aider à porter ça ?",
    "question_pronunciation_ipa": "[ɛs kə ty pø mɛde a pɔʁte sa]",
    "question_pronunciation_english": "es kuh tew puh meh-day ah por-tay sah?",
    "question_pronunciation_persian": "اِس ک تو پو مه‌ده آ پغته سا؟",
    "question_translation_english": "Can you help me carry this?",
    "question_translation_persian": "میتونی کمک کنی این رو حمل کنم؟",
    "french_answerformal": "Bien sûr, laissez-moi vous aider.",
    "answerformal_pronunciation_ipa": "[bjɛ̃ syʁ lese mwa vu zede]",
    "answerformal_pronunciation_english": "byan sur, lay-say mwah voo zay-day",
    "answerformal_pronunciation_persian": "بیا سور، لسه موا وو زِده",
    "answerformal_translation_english": "Of course, let me help you.",
    "answerformal_translation_persian": "حتما، اجازه بدید کمکتون کنم.",
    "french_answerinformal": "Pas de souci, je te file un coup de main.",
    "answerinformal_pronunciation_ipa": "[pa də susi ʒə tə fil ɛ̃ ku də mɛ̃]",
    "answerinformal_pronunciation_english": "pah duh soo-see, zhuh tuh feel uhn koo duh man",
    "answerinformal_pronunciation_persian": "پا دُ سوسی، ژو تو فیل اَن کو دُ من",
    "answerinformal_translation_english": "No problem, I'll give you a hand.",
    "answerinformal_translation_persian": "مشکلی نیست، کمکت می‌کنم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Où se trouve la pharmacie la plus proche ?",
    "question_pronunciation_ipa": "[u sə tʁuv la faʁmasi la ply pʁɔʃ]",
    "question_pronunciation_english": "oo suh troov lah far-mah-see lah ploo prosh?",
    "question_pronunciation_persian": "او سُ تروف لا فارماسی لا پلوی پروش؟",
    "question_translation_english": "Where is the nearest pharmacy?",
    "question_translation_persian": "نزدیک‌ترین داروخانه کجاست؟",
    "french_answerformal": "Elle est à deux rues d’ici, sur la droite.",
    "answerformal_pronunciation_ipa": "[ɛl ɛ a dø ʁy disi syʁ la dʁwat]",
    "answerformal_pronunciation_english": "el eh ah duh rue dee-see, sur la drwat",
    "answerformal_pronunciation_persian": "اِل اِ آ دو غو دیسی، سور لا دقوات",
    "answerformal_translation_english": "It's two streets from here, on the right.",
    "answerformal_translation_persian": "دو خیابان جلوتر، سمت راست.",
    "french_answerinformal": "Juste là, au coin de la rue.",
    "answerinformal_pronunciation_ipa": "[ʒyst la o kwɛ̃ də la ʁy]",
    "answerinformal_pronunciation_english": "zhust lah oh kwan duh lah rue",
    "answerinformal_pronunciation_persian": "ژوست لا، او کوئن دُ لا غو",
    "answerinformal_translation_english": "Right there, at the street corner.",
    "answerinformal_translation_persian": "سر کوچه است."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "A quelle heure ouvrez-vous ?",
    "question_pronunciation_ipa": "[a kɛl œʁ uvʁe vu]",
    "question_pronunciation_english": "ah kel ur oov-ray voo?",
    "question_pronunciation_persian": "آ کِل اُغ اووره وو؟",
    "question_translation_english": "What time do you open?",
    "question_translation_persian": "چه ساعتی باز می‌کنید؟",
    "french_answerformal": "Nous ouvrons à 9 heures.",
    "answerformal_pronunciation_ipa": "[nu uvʁɔ̃ a nœv œʁ]",
    "answerformal_pronunciation_english": "noo oov-ron ah nuhv ur",
    "answerformal_pronunciation_persian": "نو اووغان آ نُو اُغ",
    "answerformal_translation_english": "We open at 9 o'clock.",
    "answerformal_translation_persian": "ساعت ۹ باز می‌کنیم.",
    "french_answerinformal": "Dès 8 heures, du lundi au samedi.",
    "answerinformal_pronunciation_ipa": "[dɛ zɥit œʁ dy lɛ̃di o samdi]",
    "answerinformal_pronunciation_english": "deh zweet ur du lon-dee oh sam-dee",
    "answerinformal_pronunciation_persian": "ده زویت اُغ دو لاندی او سامدی",
    "answerinformal_translation_english": "From 8 a.m., Monday to Saturday.",
    "answerinformal_translation_persian": "از ساعت ۸ صبح، دوشنبه تا شنبه."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Est-ce que je dois réserver ?",
    "question_pronunciation_ipa": "[ɛs kə ʒə dwa ʁezɛʁve]",
    "question_pronunciation_english": "es kuh zhuh dwa reh-zehr-vay?",
    "question_pronunciation_persian": "اِس ک ژ دوا غزغوه؟",
    "question_translation_english": "Do I have to book/reserve?",
    "question_translation_persian": "باید رزرو کنم؟",
    "french_answerformal": "Oui, il vaut mieux réserver à l’avance.",
    "answerformal_pronunciation_ipa": "[wi il vo mjø ʁezɛʁve a lavɑ̃s]",
    "answerformal_pronunciation_english": "wee eel vo myuh reh-zehr-vay ah lah-vahs",
    "answerformal_pronunciation_persian": "وی ایل وو میو غزغوه آ لاوانس",
    "answerformal_translation_english": "Yes, it's better to reserve in advance.",
    "answerformal_translation_persian": "بله، بهتره از قبل رزرو کنید.",
    "french_answerinformal": "Non, il y a souvent de la place.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ il ja suvɑ̃ də la plas]",
    "answerinformal_pronunciation_english": "noh eel yah soo-von duh lah plass",
    "answerinformal_pronunciation_persian": "نو ایل یا سووان دُ لا پلاس",
    "answerinformal_translation_english": "No, there's usually room.",
    "answerinformal_translation_persian": "نه، معمولا جا هست."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Vous prenez la carte bleue ?",
    "question_pronunciation_ipa": "[vu pʁəne la kaʁt blø]",
    "question_pronunciation_english": "voo pruh-nay lah kart bluh?",
    "question_pronunciation_persian": "وو پرنه لا کارت بلو؟",
    "question_translation_english": "Do you take credit card?",
    "question_translation_persian": "کارت اعتباری قبول می‌کنید؟",
    "french_answerformal": "Oui, toutes les cartes sont acceptées.",
    "answerformal_pronunciation_ipa": "[wi tut le kaʁt sɔ̃t aksɛpte]",
    "answerformal_pronunciation_english": "wee toot lay kart sont ak-sep-tay",
    "answerformal_pronunciation_persian": "وی توت له کارت سون اکسپته",
    "answerformal_translation_english": "Yes, all cards are accepted.",
    "answerformal_translation_persian": "بله، همه کارت‌ها قبول می‌شود.",
    "french_answerinformal": "Non, c’est seulement en espèces.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ sɛ sœlmɑ̃ ɑ̃ ɛspɛs]",
    "answerinformal_pronunciation_english": "noh seh seul-mon on es-pess",
    "answerinformal_pronunciation_persian": "نو سه سُلمان اِن اِسپِس",
    "answerinformal_translation_english": "No, only cash.",
    "answerinformal_translation_persian": "نه، فقط نقدی."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel est le moyen de transport le plus pratique ici ?",
    "question_pronunciation_ipa": "[kɛl ɛ lə mwajɛ̃ də tʁɑ̃spɔʁ lə ply pʁatik isi]",
    "question_pronunciation_english": "kel eh luh mwa-yan duh tran-spor luh ploo prah-teek ee-see?",
    "question_pronunciation_persian": "کِل اِ لُ موایَن دُ تغانسپق لُ پلو پغاتیک ایسی؟",
    "question_translation_english": "What's the most convenient transportation here?",
    "question_translation_persian": "ساده‌ترین وسیله حمل و نقل اینجا چیه؟",
    "french_answerformal": "Le métro est le plus rapide.",
    "answerformal_pronunciation_ipa": "[lə metro ɛ lə ply ʁapid]",
    "answerformal_pronunciation_english": "luh meh-tro eh luh ploo rah-peed",
    "answerformal_pronunciation_persian": "لُ متقو اِ لُ پلو غاپید",
    "answerformal_translation_english": "The metro is the fastest.",
    "answerformal_translation_persian": "مترو سریع‌ترینه.",
    "french_answerinformal": "Le bus, c’est plus économique.",
    "answerinformal_pronunciation_ipa": "[lə bys sɛ ply zekɔnɔmik]",
    "answerinformal_pronunciation_english": "luh bus seh ploo zeh-ko-no-mik",
    "answerinformal_pronunciation_persian": "لُ بوس سه پلو زِکُنُمیک",
    "answerinformal_translation_english": "The bus is more economical.",
    "answerinformal_translation_persian": "اتوبوس مقرون به صرفه‌تره."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quel est ton film préféré ?",
    "question_pronunciation_ipa": "[kɛl ɛ tɔ̃ film pʁefeʁe]",
    "question_pronunciation_english": "kel eh ton film preh-feh-ray?",
    "question_pronunciation_persian": "کِل اِ تون فیلم پِغِفهغه؟",
    "question_translation_english": "What’s your favorite movie?",
    "question_translation_persian": "فیلم مورد علاقه‌ات چیه؟",
    "french_answerformal": "Mon film préféré est Inception.",
    "answerformal_pronunciation_ipa": "[mɔ̃ film pʁefeʁe ɛ ɛ̃sɛpsjɔ̃]",
    "answerformal_pronunciation_english": "mon film preh-feh-ray eh an-sep-syon",
    "answerformal_pronunciation_persian": "مون فیلم پِغِفهغه اِ انسپسیون",
    "answerformal_translation_english": "My favorite movie is Inception.",
    "answerformal_translation_persian": "فیلم مورد علاقه من اینسپشن است.",
    "french_answerinformal": "J’adore les comédies.",
    "answerinformal_pronunciation_ipa": "[ʒadɔʁ le kɔmedi]",
    "answerinformal_pronunciation_english": "zhah-dor lay ko-meh-dee",
    "answerinformal_pronunciation_persian": "ژادوغ له کُمِدی",
    "answerinformal_translation_english": "I love comedies.",
    "answerinformal_translation_persian": "کمدی‌ها رو دوست دارم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu préfères le thé ou le café ?",
    "question_pronunciation_ipa": "[ty pʁefɛʁ lə te u lə kafe]",
    "question_pronunciation_english": "tew preh-fair luh tay oo luh kah-fay?",
    "question_pronunciation_persian": "تو پِغِفغ لُ ته او لُ کافه؟",
    "question_translation_english": "Do you prefer tea or coffee?",
    "question_translation_persian": "چای دوست داری یا قهوه؟",
    "french_answerformal": "Je préfère le café, merci.",
    "answerformal_pronunciation_ipa": "[ʒə pʁefɛʁ lə kafe mɛʁsi]",
    "answerformal_pronunciation_english": "zhuh preh-fair luh kah-fay mehr-see",
    "answerformal_pronunciation_persian": "ژو پِغِفهغ لُ کافه مِغسی",
    "answerformal_translation_english": "I prefer coffee, thank you.",
    "answerformal_translation_persian": "قهوه ترجیح می‌دهم، ممنون.",
    "french_answerinformal": "Le thé, surtout l’hiver !",
    "answerinformal_pronunciation_ipa": "[lə te syʁtu livɛʁ]",
    "answerinformal_pronunciation_english": "luh tay, sur-too lee-ver",
    "answerinformal_pronunciation_persian": "لُ ته، سورتو لیوهغ",
    "answerinformal_translation_english": "Tea, especially in winter!",
    "answerinformal_translation_persian": "چای، مخصوصا زمستون!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "On se retrouve à quelle heure ?",
    "question_pronunciation_ipa": "[ɔ̃ sə ʁətʁuv a kɛl œʁ]",
    "question_pronunciation_english": "on suh ruh-troov ah kel ur?",
    "question_pronunciation_persian": "اُن سُ غتغوف آ کِل اُغ؟",
    "question_translation_english": "What time shall we meet?",
    "question_translation_persian": "چه ساعتی همدیگه رو ببینیم؟",
    "french_answerformal": "À 19 heures devant le restaurant.",
    "answerformal_pronunciation_ipa": "[a diznœf œʁ dəvɑ̃ lə ʁɛstɔʁɑ̃]",
    "answerformal_pronunciation_english": "ah deez-nuf ur duh-vahn luh res-tor-ahn",
    "answerformal_pronunciation_persian": "آ دیزنوف اُغ دُوان لُ غِستوقان",
    "answerformal_translation_english": "At 7 p.m. in front of the restaurant.",
    "answerformal_translation_persian": "ساعت ۷ شب جلوی رستوران.",
    "french_answerinformal": "Vers 18h, ça te va ?",
    "answerinformal_pronunciation_ipa": "[vɛʁ dizɥit œʁ sa tə va]",
    "answerinformal_pronunciation_english": "ver deez-wheet ur, sah tuh vah?",
    "answerinformal_pronunciation_persian": "وِغ دیزویت اُغ، سا تو وا؟",
    "answerinformal_translation_english": "Around 6 p.m., is that okay?",
    "answerinformal_translation_persian": "حدود ۶ عصر، خوبه؟"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu veux sortir ce soir ?",
    "question_pronunciation_ipa": "[ty vø sɔʁtiʁ sə swaʁ]",
    "question_pronunciation_english": "tew vuh sor-teer suh swar?",
    "question_pronunciation_persian": "تو وو سغتیغ سُ سواغ؟",
    "question_translation_english": "Do you want to go out tonight?",
    "question_translation_persian": "امشب می‌خوای بیرون بری؟",
    "french_answerformal": "Oui, pourquoi pas !",
    "answerformal_pronunciation_ipa": "[wi puʁkwa pa]",
    "answerformal_pronunciation_english": "wee poor-kwah pah",
    "answerformal_pronunciation_persian": "وی پوقوا پا",
    "answerformal_translation_english": "Yes, why not!",
    "answerformal_translation_persian": "بله، چرا که نه!",
    "french_answerinformal": "Pas ce soir, je suis fatigué(e).",
    "answerinformal_pronunciation_ipa": "[pa sə swaʁ ʒə sɥi fatiɡe]",
    "answerinformal_pronunciation_english": "pah suh swar, zhuh swee fa-tee-gay",
    "answerinformal_pronunciation_persian": "پا سُ سواغ، ژو سوی فاتیگه",
    "answerinformal_translation_english": "Not tonight, I’m tired.",
    "answerinformal_translation_persian": "نه، امشب خسته‌ام."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Comment tu trouves ce livre ?",
    "question_pronunciation_ipa": "[kɔmɑ̃ ty tʁuv sə livʁ]",
    "question_pronunciation_english": "koh-mahn tew troov suh leevr?",
    "question_pronunciation_persian": "کُمان تو تروف سُ لیوغ؟",
    "question_translation_english": "How do you like this book?",
    "question_translation_persian": "این کتاب رو چطور می‌بینی/دوست داری؟",
    "french_answerformal": "Il est très intéressant.",
    "answerformal_pronunciation_ipa": "[il ɛ tʁɛz ɛ̃teʁesɑ̃]",
    "answerformal_pronunciation_english": "eel eh trez an-teh-ray-sahn",
    "answerformal_pronunciation_persian": "ایل اِ تغهز اِنتهغهسان",
    "answerformal_translation_english": "It's very interesting.",
    "answerformal_translation_persian": "خیلی جالب است.",
    "french_answerinformal": "Bof, ce n’est pas trop mon style.",
    "answerinformal_pronunciation_ipa": "[bɔf sə nɛ pa tʁo mɔ̃ stil]",
    "answerinformal_pronunciation_english": "bof, suh neh pah tro mon steel",
    "answerinformal_pronunciation_persian": "بوف، سُ نه پا ترو مون استیل",
    "answerinformal_translation_english": "Meh, it's not really my style.",
    "answerinformal_translation_persian": "نه زیاد، سلیقه‌ام نیست."
  },
   {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu peux me recommander un bon restaurant ?",
    "question_pronunciation_ipa": "[ty pø mə ʁəkɔmɑ̃de ɛ̃ bɔ̃ ʁɛstɔʁɑ̃]",
    "question_pronunciation_english": "tew puh muh ruh-ko-man-day uhn bon res-tor-ahn?",
    "question_pronunciation_persian": "تو پو مِ رُکُمانده اَن بُن غِستوقان؟",
    "question_translation_english": "Can you recommend a good restaurant?",
    "question_translation_persian": "می‌تونی یه رستوران خوب معرفی کنی؟",
    "french_answerformal": "Le Bistro du Coin est excellent.",
    "answerformal_pronunciation_ipa": "[lə bistro dy kwɛ̃ ɛ tɛksɛlɑ̃]",
    "answerformal_pronunciation_english": "luh bee-stro dew kwen eh tex-se-lan",
    "answerformal_pronunciation_persian": "لُ بیستغو دو کوئن اِ تکسلان",
    "answerformal_translation_english": "Le Bistro du Coin is excellent.",
    "answerformal_translation_persian": "رستوران بیستروی کوئن عالیه.",
    "french_answerinformal": "Oui, essaye le petit italien au bout de la rue.",
    "answerinformal_pronunciation_ipa": "[wi ɛsɛ lə pəti italjɛ̃ o bu də la ʁy]",
    "answerinformal_pronunciation_english": "wee eh-say luh puh-tee ee-tal-yen oh boo duh lah rue",
    "answerinformal_pronunciation_persian": "وی اسه لُ پتی ایتالیَن او بو دُ لا غو",
    "answerinformal_translation_english": "Yes, try the little Italian place down the street.",
    "answerinformal_translation_persian": "آره، اون ایتالیایی کوچیک ته خیابون رو امتحان کن."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "C’est ta première fois ici ?",
    "question_pronunciation_ipa": "[sɛ ta pʁəmjɛʁ fwa isi]",
    "question_pronunciation_english": "seh tah pruh-myair fwah ee-see?",
    "question_pronunciation_persian": "سه تا پخُمیغ فوا ایسی؟",
    "question_translation_english": "Is it your first time here?",
    "question_translation_persian": "اولین بارت اینجاست؟",
    "french_answerformal": "Oui, c’est ma première visite.",
    "answerformal_pronunciation_ipa": "[wi sɛ ma pʁəmjɛʁ vizit]",
    "answerformal_pronunciation_english": "wee seh mah pruh-myair vee-zeet",
    "answerformal_pronunciation_persian": "وی سه ما پخُمیغ ویزیت",
    "answerformal_translation_english": "Yes, it’s my first visit.",
    "answerformal_translation_persian": "بله، اولین بارمه.",
    "french_answerinformal": "Non, je viens souvent.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ ʒə vjɛ̃ suvɑ̃]",
    "answerinformal_pronunciation_english": "noh zhuh vyen soo-vahn",
    "answerinformal_pronunciation_persian": "نو ژو ویَن سووان",
    "answerinformal_translation_english": "No, I come here often.",
    "answerinformal_translation_persian": "نه، زیاد میام اینجا."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Qu’est-ce que tu en penses ?",
    "question_pronunciation_ipa": "[kɛs kə ty ɑ̃ pɑ̃s]",
    "question_pronunciation_english": "kes kuh tew on pons?",
    "question_pronunciation_persian": "کِس کُ تو آن پانس؟",
    "question_translation_english": "What do you think about it?",
    "question_translation_persian": "نظرت چیه؟",
    "french_answerformal": "Je trouve que c’est une bonne idée.",
    "answerformal_pronunciation_ipa": "[ʒə tʁuv kə sɛ tyn bɔn ide]",
    "answerformal_pronunciation_english": "zhuh troov kuh seh tyn bon ee-day",
    "answerformal_pronunciation_persian": "ژو تروف کُ سه تون بُن ایده",
    "answerformal_translation_english": "I think it’s a good idea.",
    "answerformal_translation_persian": "فکر می‌کنم ایده خوبیه.",
    "french_answerinformal": "Je ne sais pas trop, à voir !",
    "answerinformal_pronunciation_ipa": "[ʒə nə sɛ pa tʁo a vwaʁ]",
    "answerinformal_pronunciation_english": "zhuh nuh seh pah troh, ah vwar!",
    "answerinformal_pronunciation_persian": "ژو نه سه پا ترو، آ واغ!",
    "answerinformal_translation_english": "I don’t really know, we’ll see!",
    "answerinformal_translation_persian": "نمیدونم، باید ببینیم!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Excusez-moi, où est la sortie ?",
    "question_pronunciation_ipa": "[ɛkskyze mwa u ɛ la sɔʁti]",
    "question_pronunciation_english": "ex-kew-zay mwah, oo eh lah sor-tee?",
    "question_pronunciation_persian": "اکسکوزه موا، او اِ لا سغتی؟",
    "question_translation_english": "Excuse me, where is the exit?",
    "question_translation_persian": "ببخشید، خروجی کجاست؟",
    "french_answerformal": "La sortie est juste derrière vous.",
    "answerformal_pronunciation_ipa": "[la sɔʁti ɛ ʒyst dɛʁjɛʁ vu]",
    "answerformal_pronunciation_english": "lah sor-tee eh zhust dehr-yer voo",
    "answerformal_pronunciation_persian": "لا سغتی اِ ژوست دقغیهغ وو",
    "answerformal_translation_english": "The exit is right behind you.",
    "answerformal_translation_persian": "خروجی درست پشت سر شماست.",
    "french_answerinformal": "C’est tout droit, puis à gauche.",
    "answerinformal_pronunciation_ipa": "[sɛ tu dʁwa pɥi a ɡoʃ]",
    "answerinformal_pronunciation_english": "seh too drwah, pwee ah gosh",
    "answerinformal_pronunciation_persian": "سه تو دقوا، پویی آ گوش",
    "answerinformal_translation_english": "Straight ahead, then to the left.",
    "answerinformal_translation_persian": "صاف برو جلو، بعدش سمت چپ."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Je peux essayer ça ?",
    "question_pronunciation_ipa": "[ʒə pø ɛsɛje sa]",
    "question_pronunciation_english": "zhuh puh eh-say-yay sah?",
    "question_pronunciation_persian": "ژو پو اسِیه سا؟",
    "question_translation_english": "Can I try this?",
    "question_translation_persian": "میتونم این رو امتحان کنم؟",
    "french_answerformal": "Oui, la cabine d’essayage est là-bas.",
    "answerformal_pronunciation_ipa": "[wi la kabin desɛjaʒ ɛ laba]",
    "answerformal_pronunciation_english": "wee lah kah-been deh-say-ahzh eh lah-bah",
    "answerformal_pronunciation_persian": "وی لا کابین دِسِیاژ اِ لابا",
    "answerformal_translation_english": "Yes, the fitting room is over there.",
    "answerformal_translation_persian": "بله، اتاق پرو اونجاست.",
    "french_answerinformal": "Pas de souci, vas-y !",
    "answerinformal_pronunciation_ipa": "[pa də susi vazi]",
    "answerinformal_pronunciation_english": "pah duh soo-see, vah-zee!",
    "answerinformal_pronunciation_persian": "پا دُ سوسی، وازی!",
    "answerinformal_translation_english": "No problem, go ahead!",
    "answerinformal_translation_persian": "مشکلی نیست، امتحان کن!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Est-ce que je peux payer en plusieurs fois ?",
    "question_pronunciation_ipa": "[ɛs kə ʒə pø pɛje ɑ̃ plyzjœʁ fwa]",
    "question_pronunciation_english": "es kuh zhuh puh pay-yay on plew-zee-ur fwah?",
    "question_pronunciation_persian": "اِس ک ژ پ پَیه آن پلوزیهغ فوا؟",
    "question_translation_english": "Can I pay in several installments?",
    "question_translation_persian": "میشه قسطی پرداخت کنم؟",
    "french_answerformal": "Oui, c’est possible en trois fois.",
    "answerformal_pronunciation_ipa": "[wi sɛ pɔsibl ɑ̃ tʁwa fwa]",
    "answerformal_pronunciation_english": "wee seh po-see-bl on trwa fwah",
    "answerformal_pronunciation_persian": "وی سه پُسیبِل آن تغا فوا",
    "answerformal_translation_english": "Yes, it’s possible in three installments.",
    "answerformal_translation_persian": "بله، در سه قسط ممکنه.",
    "french_answerinformal": "Non, c’est uniquement en une fois.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ sɛ ynikmɑ̃ ɑ̃ yn fwa]",
    "answerinformal_pronunciation_english": "noh seh u-neek-mahn on uhn fwah",
    "answerinformal_pronunciation_persian": "نو سه یونیکمان آن یون فوا",
    "answerinformal_translation_english": "No, only in one payment.",
    "answerinformal_translation_persian": "نه، فقط یکجا باید پرداخت کنید."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as un animal de compagnie ?",
    "question_pronunciation_ipa": "[ty a ɛ̃ animal də kɔ̃paɲi]",
    "question_pronunciation_english": "tew ah uhn a-nee-mal duh kom-pa-nee?",
    "question_pronunciation_persian": "تو اَن انیمال دُ کومپانی؟",
    "question_translation_english": "Do you have a pet?",
    "question_translation_persian": "حیوان خانگی داری؟",
    "french_answerformal": "Oui, j’ai un chat.",
    "answerformal_pronunciation_ipa": "[wi ʒe ɛ̃ ʃa]",
    "answerformal_pronunciation_english": "wee zhay uhn shah",
    "answerformal_pronunciation_persian": "وی ژه اَن شا",
    "answerformal_translation_english": "Yes, I have a cat.",
    "answerformal_translation_persian": "بله، یک گربه دارم.",
    "french_answerinformal": "Non, pas d’animal chez moi.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ pa danimal ʃe mwa]",
    "answerinformal_pronunciation_english": "noh, pah dah-nee-mal shay mwah",
    "answerinformal_pronunciation_persian": "نو، پا دانیمال شه موا",
    "answerinformal_translation_english": "No, no pets at my place.",
    "answerinformal_translation_persian": "نه، حیوان خانگی ندارم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as passé une bonne journée ?",
    "question_pronunciation_ipa": "[ty a pase yn bɔn ʒuʁne]",
    "question_pronunciation_english": "tew ah pah-say uhn bon zhoor-nay?",
    "question_pronunciation_persian": "تو ا پَسه یون بون ژوغنه؟",
    "question_translation_english": "Did you have a good day?",
    "question_translation_persian": "روز خوبی داشتی؟",
    "french_answerformal": "Oui, la journée a été agréable.",
    "answerformal_pronunciation_ipa": "[wi la ʒuʁne a ete aɡʁeabl]",
    "answerformal_pronunciation_english": "wee lah zhoor-nay ah eh-tay ah-gray-ah-bl",
    "answerformal_pronunciation_persian": "وی لا ژوغنه آ اِته اَغغِبْل",
    "answerformal_translation_english": "Yes, the day was pleasant.",
    "answerformal_translation_persian": "بله، روز خوشی داشتم.",
    "french_answerinformal": "Oui, et toi ?",
    "answerinformal_pronunciation_ipa": "[wi e twa]",
    "answerinformal_pronunciation_english": "wee, ay twa?",
    "answerinformal_pronunciation_persian": "وی، اِ توا؟",
    "answerinformal_translation_english": "Yes, and you?",
    "answerinformal_translation_persian": "آره، تو چطور؟"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Bon anniversaire ! Tu fêtes comment ?",
    "question_pronunciation_ipa": "[bɔ̃n anivɛʁsɛʁ ty fɛt kɔmɑ̃]",
    "question_pronunciation_english": "bon an-ee-ver-sair! tew fet koh-mahn?",
    "question_pronunciation_persian": "بُن انیورسغ! تو فِت کُمان؟",
    "question_translation_english": "Happy birthday! How are you celebrating?",
    "question_translation_persian": "تولدت مبارک! چطور جشن می‌گیری؟",
    "french_answerformal": "Merci beaucoup ! Je fête en famille.",
    "answerformal_pronunciation_ipa": "[mɛʁsi buku ʒə fɛt ɑ̃ famij]",
    "answerformal_pronunciation_english": "mehr-see boo-koo! zhuh fet on fah-meey",
    "answerformal_pronunciation_persian": "مغسی بوکو! ژو فِت آن فامی",
    "answerformal_translation_english": "Thank you! I’m celebrating with family.",
    "answerformal_translation_persian": "خیلی ممنون! با خانواده جشن می‌گیرم.",
    "french_answerinformal": "Avec des amis, une petite soirée !",
    "answerinformal_pronunciation_ipa": "[avɛk dez ami yn pətit swaʁe]",
    "answerinformal_pronunciation_english": "ah-vek dez a-mee, uhn puh-teet swah-ray!",
    "answerinformal_pronunciation_persian": "اَوِک دِز آمی، یون پُتیت سُوغِ!",
    "answerinformal_translation_english": "With friends, a little party!",
    "answerinformal_translation_persian": "با دوستام، یه مهمونی کوچیک!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Merci beaucoup pour votre aide.",
    "question_pronunciation_ipa": "[mɛʁsi buku puʁ vɔtʁ ɛd]",
    "question_pronunciation_english": "mehr-see boo-koo poor votr ed",
    "question_pronunciation_persian": "مغسی بوکو پوق وتغ اِد",
    "question_translation_english": "Thank you very much for your help.",
    "question_translation_persian": "خیلی ممنون از کمکتون.",
    "french_answerformal": "Avec plaisir, n’hésitez pas.",
    "answerformal_pronunciation_ipa": "[avɛk plɛziʁ nezite pa]",
    "answerformal_pronunciation_english": "ah-vek pleh-zeer, neh-zee-tay pah",
    "answerformal_pronunciation_persian": "اَوِک پله‌زیغ، نِزیتِ پا",
    "answerformal_translation_english": "With pleasure, don’t hesitate.",
    "answerformal_translation_persian": "باعث افتخار، درنگ نکنید.",
    "french_answerinformal": "De rien ! Bonne journée !",
    "answerinformal_pronunciation_ipa": "[də ʁjɛ̃ bɔn ʒuʁne]",
    "answerinformal_pronunciation_english": "duh ryan! bon zhoor-nay!",
    "answerinformal_pronunciation_persian": "دو غین! بُن ژوغنه!",
    "answerinformal_translation_english": "You're welcome! Have a nice day!",
    "answerinformal_translation_persian": "خواهش می‌کنم! روز خوبی داشته باشی!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Je suis désolé(e), je suis en retard.",
    "question_pronunciation_ipa": "[ʒə sɥi dezɔle ʒə sɥi ɑ̃ ʁətaʁ]",
    "question_pronunciation_english": "zhuh swee day-zo-lay, zhuh swee on ruh-tar",
    "question_pronunciation_persian": "ژو سوی دِزوله، ژو سوی آن غوتاغ",
    "question_translation_english": "I'm sorry, I'm late.",
    "question_translation_persian": "ببخشید، دیر رسیدم.",
    "french_answerformal": "Ce n’est pas grave, ça arrive.",
    "answerformal_pronunciation_ipa": "[sə nɛ pa ɡʁav sa aʁiv]",
    "answerformal_pronunciation_english": "suh neh pah grav, sah ah-reev",
    "answerformal_pronunciation_persian": "سُ نه پا گغاو، سا آغیو",
    "answerformal_translation_english": "It's not a problem, it happens.",
    "answerformal_translation_persian": "اشکالی نداره، پیش میاد.",
    "french_answerinformal": "T’inquiète pas, tout va bien.",
    "answerinformal_pronunciation_ipa": "[tɛ̃kjɛt pa tu va bjɛ̃]",
    "answerinformal_pronunciation_english": "tan-ket pah, too vah byan",
    "answerinformal_pronunciation_persian": "تَنکیت پا، تو و بیا",
    "answerinformal_translation_english": "Don’t worry, it’s all good.",
    "answerinformal_translation_persian": "نگران نباش، همه چی خوبه."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Comment s’est passée ta journée ?",
    "question_pronunciation_ipa": "[kɔmɑ̃ sɛ pase ta ʒuʁne]",
    "question_pronunciation_english": "koh-mahn seh pah-say tah zhoor-nay?",
    "question_pronunciation_persian": "کُمان سه پاسه تا ژوغنه؟",
    "question_translation_english": "How was your day?",
    "question_translation_persian": "روزت چطور گذشت؟",
    "french_answerformal": "Elle s’est bien passée, merci.",
    "answerformal_pronunciation_ipa": "[ɛl sɛ bjɛ̃ pase mɛʁsi]",
    "answerformal_pronunciation_english": "el seh byan pah-say mehr-see",
    "answerformal_pronunciation_persian": "اِل سه بیا پاسه مِغسی",
    "answerformal_translation_english": "It went well, thank you.",
    "answerformal_translation_persian": "خوب گذشت، ممنون.",
    "french_answerinformal": "Un peu fatiguante, mais ça va !",
    "answerinformal_pronunciation_ipa": "[ɛ̃ pø fatiɡɑ̃t mɛ sa va]",
    "answerinformal_pronunciation_english": "uhn puh fa-tee-gant, may sah vah!",
    "answerinformal_pronunciation_persian": "اَن پو فاتیگانت، مِه سا وا!",
    "answerinformal_translation_english": "A bit tiring, but I'm okay!",
    "answerinformal_translation_persian": "یه کم خسته‌کننده بود، ولی خوبم!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Quoi de neuf ?",
    "question_pronunciation_ipa": "[kwa də nœf]",
    "question_pronunciation_english": "kwah duh nuf?",
    "question_pronunciation_persian": "کوا د نُف؟",
    "question_translation_english": "What's new?",
    "question_translation_persian": "چه خبر؟",
    "french_answerformal": "Pas grand-chose, et vous ?",
    "answerformal_pronunciation_ipa": "[pa ɡʁɑ̃ ʃoz e vu]",
    "answerformal_pronunciation_english": "pah grahn shoz, ay voo?",
    "answerformal_pronunciation_persian": "پا گغان شوز، اِ وو؟",
    "answerformal_translation_english": "Not much, and you?",
    "answerformal_translation_persian": "خبر خاصی نیست، شما چطور؟",
    "french_answerinformal": "Tout va bien, merci !",
    "answerinformal_pronunciation_ipa": "[tu va bjɛ̃ mɛʁsi]",
    "answerinformal_pronunciation_english": "too vah byan, mehr-see!",
    "answerinformal_pronunciation_persian": "تو و بیا، مِغسی!",
    "answerinformal_translation_english": "All good, thanks!",
    "answerinformal_translation_persian": "همه چی خوبه، مرسی!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu veux boire quelque chose ?",
    "question_pronunciation_ipa": "[ty vø bwaʁ kɛlkə ʃoz]",
    "question_pronunciation_english": "tew vuh bwar kel-kuh shoz?",
    "question_pronunciation_persian": "تو وو بواغ کِلک شوز؟",
    "question_translation_english": "Would you like something to drink?",
    "question_translation_persian": "می‌خوای چیزی بنوشی؟",
    "french_answerformal": "Oui, un café s’il vous plaît.",
    "answerformal_pronunciation_ipa": "[wi ɛ̃ kafe sil vu plɛ]",
    "answerformal_pronunciation_english": "wee, uhn kah-fay seel voo pleh",
    "answerformal_pronunciation_persian": "وی، اَن کافه سیل وو پله",
    "answerformal_translation_english": "Yes, a coffee please.",
    "answerformal_translation_persian": "بله، یک قهوه لطفاً.",
    "french_answerinformal": "Non merci, j’ai déjà bu.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ mɛʁsi ʒe deʒa by]",
    "answerinformal_pronunciation_english": "noh mehr-see, zhay deh-zha bew",
    "answerinformal_pronunciation_persian": "نو مِغسی، ژه دِژا بو",
    "answerinformal_translation_english": "No thanks, I’ve already had something.",
    "answerinformal_translation_persian": "نه ممنون، قبلاً خوردم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "On y va ?",
    "question_pronunciation_ipa": "[ɔ̃ i va]",
    "question_pronunciation_english": "on ee vah?",
    "question_pronunciation_persian": "اُن ای وا؟",
    "question_translation_english": "Shall we go?",
    "question_translation_persian": "بریم؟",
    "french_answerformal": "Oui, je suis prêt(e).",
    "answerformal_pronunciation_ipa": "[wi ʒə sɥi pʁɛt]",
    "answerformal_pronunciation_english": "wee, zhuh swee pret",
    "answerformal_pronunciation_persian": "وی، ژو سوی پغت",
    "answerformal_translation_english": "Yes, I’m ready.",
    "answerformal_translation_persian": "بله، آماده‌ام.",
    "french_answerinformal": "Attends une seconde !",
    "answerinformal_pronunciation_ipa": "[atɑ̃ yn səɡɔ̃d]",
    "answerinformal_pronunciation_english": "ah-tan uhn suh-gond!",
    "answerinformal_pronunciation_persian": "اتان یون سُگون!",
    "answerinformal_translation_english": "Wait a second!",
    "answerinformal_translation_persian": "یک لحظه صبر کن!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Qu’est-ce que tu fais dans la vie ?",
    "question_pronunciation_ipa": "[kɛs kə ty fɛ dɑ̃ la vi]",
    "question_pronunciation_english": "kes kuh tew feh don lah vee?",
    "question_pronunciation_persian": "کِس ک تو فه دان لا وی؟",
    "question_translation_english": "What do you do for a living?",
    "question_translation_persian": "شغلت چیه؟",
    "french_answerformal": "Je travaille dans une banque.",
    "answerformal_pronunciation_ipa": "[ʒə tʁavaj dɑ̃z yn bɑ̃k]",
    "answerformal_pronunciation_english": "zhuh tra-vai donz un bonk",
    "answerformal_pronunciation_persian": "ژو تغاوای دانز یون بانک",
    "answerformal_translation_english": "I work in a bank.",
    "answerformal_translation_persian": "تو بانک کار می‌کنم.",
    "french_answerinformal": "Je suis étudiant(e).",
    "answerinformal_pronunciation_ipa": "[ʒə sɥi etydjɑ̃]",
    "answerinformal_pronunciation_english": "zhuh swee eh-tyu-dyan",
    "answerinformal_pronunciation_persian": "ژو سوی اتیدیان",
    "answerinformal_translation_english": "I’m a student.",
    "answerinformal_translation_persian": "دانشجو هستم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as faim ?",
    "question_pronunciation_ipa": "[ty a fɛ̃]",
    "question_pronunciation_english": "tew ah fan?",
    "question_pronunciation_persian": "تو آ فَن؟",
    "question_translation_english": "Are you hungry?",
    "question_translation_persian": "گرسنه‌ای؟",
    "french_answerformal": "Un peu, oui.",
    "answerformal_pronunciation_ipa": "[ɛ̃ pø wi]",
    "answerformal_pronunciation_english": "uhn puh, wee",
    "answerformal_pronunciation_persian": "اَن پو، وی",
    "answerformal_translation_english": "A little, yes.",
    "answerformal_translation_persian": "یه کم، بله.",
    "french_answerinformal": "Non, j’ai bien mangé.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ ʒe bjɛ̃ mɑ̃ʒe]",
    "answerinformal_pronunciation_english": "noh zhay byan mahn-zhay",
    "answerinformal_pronunciation_persian": "نو ژه بیا مانژه",
    "answerinformal_translation_english": "No, I ate well.",
    "answerinformal_translation_persian": "نه، خوب خوردم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu veux sortir ce week-end ?",
    "question_pronunciation_ipa": "[ty vø sɔʁtiʁ sə wik ɛnd]",
    "question_pronunciation_english": "tew vuh sor-teer suh week-end?",
    "question_pronunciation_persian": "تو وو سغتیغ سُ ویک‌اند؟",
    "question_translation_english": "Do you want to go out this weekend?",
    "question_translation_persian": "این آخر هفته می‌خوای بیرون بری؟",
    "french_answerformal": "Oui, ça me ferait plaisir.",
    "answerformal_pronunciation_ipa": "[wi sa mə fʁɛ plezir]",
    "answerformal_pronunciation_english": "wee, sah muh freh pleh-zeer",
    "answerformal_pronunciation_persian": "وی، سا مِ فغه پله‌زیغ",
    "answerformal_translation_english": "Yes, I’d like that.",
    "answerformal_translation_persian": "بله، خوشحال میشم.",
    "french_answerinformal": "Non, j’ai déjà des plans.",
    "answerinformal_pronunciation_ipa": "[nɔ̃ ʒe deʒa de plɑ̃]",
    "answerinformal_pronunciation_english": "noh zhay deh-zha deh plon",
    "answerinformal_pronunciation_persian": "نو ژه دِژا دِ پلان",
    "answerinformal_translation_english": "No, I already have plans.",
    "answerinformal_translation_persian": "نه، برنامه دارم."
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu as compris ?",
    "question_pronunciation_ipa": "[ty a kɔ̃pʁi]",
    "question_pronunciation_english": "tew ah kom-pree?",
    "question_pronunciation_persian": "تو آ کمپقی؟",
    "question_translation_english": "Did you understand?",
    "question_translation_persian": "فهمیدی؟",
    "french_answerformal": "Oui, merci pour l’explication.",
    "answerformal_pronunciation_ipa": "[wi mɛʁsi puʁ lɛksplikasjɔ̃]",
    "answerformal_pronunciation_english": "wee mehr-see poor lex-plee-ka-syon",
    "answerformal_pronunciation_persian": "وی مِغسی پوق لکسپلیکاسیون",
    "answerformal_translation_english": "Yes, thank you for the explanation.",
    "answerformal_translation_persian": "بله، ممنون بابت توضیح.",
    "french_answerinformal": "Pas tout, tu peux répéter ?",
    "answerinformal_pronunciation_ipa": "[pa tu ty pø ʁepete]",
    "answerinformal_pronunciation_english": "pah too, tew puh reh-pay-tay?",
    "answerinformal_pronunciation_persian": "پا تو، تو پو غپته؟",
    "answerinformal_translation_english": "Not all, can you repeat?",
    "answerinformal_translation_persian": "نه همشو، می‌تونی تکرار کنی؟"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Tu veux un coup de main ?",
    "question_pronunciation_ipa": "[ty vø ɛ̃ ku də mɛ̃]",
    "question_pronunciation_english": "tew vuh uhn koo duh man?",
    "question_pronunciation_persian": "تو وو اَن کو دُ من؟",
    "question_translation_english": "Do you want a hand (some help)?",
    "question_translation_persian": "کمک می‌خوای؟",
    "french_answerformal": "Oui, ce serait gentil.",
    "answerformal_pronunciation_ipa": "[wi sə səʁɛ ʒɑ̃ti]",
    "answerformal_pronunciation_english": "wee, suh suh-reh zhan-tee",
    "answerformal_pronunciation_persian": "وی، سُ سغِ ژانتی",
    "answerformal_translation_english": "Yes, that would be kind.",
    "answerformal_translation_persian": "بله، لطف می‌کنی.",
    "french_answerinformal": "Non merci, je gère !",
    "answerinformal_pronunciation_ipa": "[nɔ̃ mɛʁsi ʒə ʒɛʁ]",
    "answerinformal_pronunciation_english": "noh mehr-see, zhuh zhair!",
    "answerinformal_pronunciation_persian": "نو مِغسی، ژو ژغ!",
    "answerinformal_translation_english": "No thanks, I’ve got it!",
    "answerinformal_translation_persian": "نه ممنون، خودم بلدم!"
  },
  {
    "topic": "Everyday",
    "role": "Customer",
    "french_question": "Ça te dit d’aller au cinéma ce soir ?",
    "question_pronunciation_ipa": "[sa tə di dale o sinema sə swaʁ]",
    "question_pronunciation_english": "sah tuh dee dah-lay oh see-neh-mah suh swar?",
    "question_pronunciation_persian": "سا تِ دی داله او سینِما سُ سواغ؟",
    "question_translation_english": "Do you feel like going to the movies tonight?",
    "question_translation_persian": "امشب می‌خوای بریم سینما؟",
    "french_answerformal": "Oui, volontiers !",
    "answerformal_pronunciation_ipa": "[wi vɔlɔ̃tje]",
    "answerformal_pronunciation_english": "wee voh-lon-tyay!",
    "answerformal_pronunciation_persian": "وی وُلُنتیه!",
    "answerformal_translation_english": "Yes, I’d love to!",
    "answerformal_translation_persian": "بله، با کمال میل!",
    "french_answerinformal": "Désolé, pas ce soir.",
    "answerinformal_pronunciation_ipa": "[dezole pa sə swaʁ]",
    "answerinformal_pronunciation_english": "day-zoh-lay, pah suh swar",
    "answerinformal_pronunciation_persian": "دِزوله، پا سُ سواغ",
    "answerinformal_translation_english": "Sorry, not tonight.",
    "answerinformal_translation_persian": "متاسفم، امشب نمی‌تونم."
  }
    // Add more question objects here
];